// Compiled shader for all platforms, uncompressed size: 75.5KB

Shader "Futile/HoloGrid" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 278 math, 13 texture, 43 branch
 //       gles3 : 278 math, 13 texture, 43 branch
 //   glesdesktop : 278 math, 13 texture, 43 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 157 math, 13 texture, 17 branch
 //       metal : 278 math, 13 texture, 43 branch
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {
// Platform opengl had shader errors
//   <no keywords>
// Platform d3d9 had shader errors
//   <no keywords>
SubProgram "d3d11 " {
// Stats: 157 math, 13 textures, 17 branches
SetTexture 0 [_LevelTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_NoiseTex2] 2D 2
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedhlhnflpcijgogdneaknbfgjifpoeobenabaaaaaagibmaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcheblaaaaeaaaaaaannagaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaoaaaaaadiaaaaaidcaabaaa
aaaaaaaaogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaadaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaaaaaaaalmcaabaaaaaaaaaaa
agbebaiaebaaaaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaadpaaaaaadp
apaaaaahecaabaaaaaaaaaaaogakbaaaaaaaaaaaogakbaaaaaaaaaaaelaaaaaf
ecaabaaaaaaaaaaackaabaaaaaaaaaaadcaaaaakecaabaaaaaaaaaaackaabaaa
aaaaaaaaabeaaaaaaaaaaaeadkbabaiaebaaaaaaacaaaaaaaacaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaabaaaaaa
egaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaajicaabaaa
aaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaa
abaaaaaadkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaa
aaaaaaaadkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaadkaabaaa
abaaaaaadkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabiaaaaakhcaabaaa
abaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
abaaaaahbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaah
bcaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaadhaaaaajicaabaaa
aaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaiadpdkaabaaaaaaaaaaadbaaaaah
bcaabaaaabaaaaaaabeaaaaamnmmemdodkaabaaaaaaaaaaadcaaaaapgcaabaaa
abaaaaaakgblbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaialpaaaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaaaaaefaaaaajpcaabaaaacaaaaaa
jgafbaaaabaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabpaaaeadakaabaaa
abaaaaaadbaaaaahbcaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaaacaaaaaa
djaaaaakgcaabaaaabaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadmaaaaahbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaa
abaaaaaadmaaaaahbcaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaa
dgaaaaafccaabaaaabaaaaaaabeaaaaamnmmemdobcaaaaabdgaaaaafbcaabaaa
abaaaaaaabeaaaaaaaaaaaaabfaaaaabdhaaaaajicaabaaaaaaaaaaaakaabaaa
abaaaaaabkaabaaaabaaaaaadkaabaaaaaaaaaaabnaaaaahbcaabaaaabaaaaaa
dkaabaaaaaaaaaaaabeaaaaahhlohpdpaaaaaaakgcaabaaaabaaaaaaagabbaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaaalpmdpfcilpaaaaaaaaaaaaaaakdcaabaaa
acaaaaaaegbabaaaabaaaaaaaceaaaaaaaaaaalpaaaaaalpaaaaaaaaaaaaaaaa
diaaaaakdcaabaaaacaaaaaaegaabaaaacaaaaaaaceaaaaamnmmmmdomnmmmmdo
aaaaaaaaaaaaaaaadcaaaaamgcaabaaaabaaaaaafgagbaaaabaaaaaaaceaaaaa
aaaaaaaamnmmmmdomnmmmmdoaaaaaaaaagabbaaaacaaaaaadcaaaaajgcaabaaa
abaaaaaafgagbaaaabaaaaaapgapbaaaaaaaaaaaagbbbaaaabaaaaaaaaaaaaai
dcaabaaaacaaaaaajgafbaaaabaaaaaaegbabaiaebaaaaaaacaaaaaaapaaaaah
icaabaaaabaaaaaaegaabaaaacaaaaaaegaabaaaacaaaaaaeeaaaaaficaabaaa
abaaaaaadkaabaaaabaaaaaadiaaaaahdcaabaaaacaaaaaapgapbaaaabaaaaaa
egaabaaaacaaaaaaaaaaaaaiicaabaaaabaaaaaadkaabaiaebaaaaaaaaaaaaaa
abeaaaaamnmmemdodiaaaaahicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaaa
abaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaamnmmmmdm
abeaaaaamnmmemdodcaaaaajicaabaaaabaaaaaackbabaaaacaaaaaadkaabaaa
abaaaaaaabeaaaaamnmmemlodcaaaaakdcaabaaaadaaaaaaegaabaiaebaaaaaa
acaaaaaapgapbaaaabaaaaaaogbkbaaaabaaaaaadcaaaaakdcaabaaaaaaaaaaa
egaabaiaebaaaaaaacaaaaaapgapbaaaabaaaaaaegaabaaaaaaaaaaaefaaaaaj
pcaabaaaacaaaaaaegaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaa
aaaaaaaiecaabaaaadaaaaaabkaabaiaebaaaaaaadaaaaaaabeaaaaaaaaaiadp
efaaaaajpcaabaaaaeaaaaaaigaabaaaadaaaaaaeghobaaaabaaaaaaaagabaaa
aaaaaaaaaaaaaaakpcaabaaaafaaaaaaegaebaaaaaaaaaaaaceaaaaaohdodllk
aaaaaaaaohdodldkaaaaaaaaaoaaaaaldcaabaaaagaaaaaaaceaaaaaaaaaialp
aaaaialpaaaaaaaaaaaaaaaaegiacaaaaaaaaaaaadaaaaaadgaaaaafecaabaaa
agaaaaaaabeaaaaaaaaaaaaaaaaaaaahdcaabaaaahaaaaaaegaabaaaadaaaaaa
igaabaaaagaaaaaaefaaaaajpcaabaaaaiaaaaaaegaabaaaafaaaaaaeghobaaa
aaaaaaaaaagabaaaabaaaaaaaaaaaaaiecaabaaaahaaaaaabkaabaiaebaaaaaa
ahaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaahaaaaaaigaabaaaahaaaaaa
eghobaaaabaaaaaaaagabaaaaaaaaaaaaoaaaaaldcaabaaaajaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaiadpegiacaaaaaaaaaaaadaaaaaadgaaaaaf
ecaabaaaajaaaaaaabeaaaaaaaaaaaaaaaaaaaahdcaabaaaakaaaaaaegaabaaa
adaaaaaaigaabaaaajaaaaaaefaaaaajpcaabaaaafaaaaaaogakbaaaafaaaaaa
eghobaaaaaaaaaaaaagabaaaabaaaaaaaaaaaaakpcaabaaaalaaaaaaegaebaaa
aaaaaaaaaceaaaaaaaaaaaaaaknhkddkaaaaaaaaaknhkdlkaaaaaaaiecaabaaa
akaaaaaabkaabaiaebaaaaaaakaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaa
akaaaaaaigaabaaaakaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaaaaaaaaah
dcaabaaaajaaaaaaegaabaaaadaaaaaaggakbaaaajaaaaaaefaaaaajpcaabaaa
amaaaaaaegaabaaaalaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaaaaaaaaai
ecaabaaaajaaaaaabkaabaiaebaaaaaaajaaaaaaabeaaaaaaaaaiadpefaaaaaj
pcaabaaaajaaaaaaigaabaaaajaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaa
aaaaaaahdcaabaaaadaaaaaaegaabaaaadaaaaaaggakbaaaagaaaaaaefaaaaaj
pcaabaaaagaaaaaaogakbaaaalaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaa
diaaaaakdcaabaaaalaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaiaeaaaaaaaeb
aaaaaaaaaaaaaaaaaaaaaaaiecaabaaaadaaaaaabkaabaiaebaaaaaaadaaaaaa
abeaaaaaaaaaiadpefaaaaajpcaabaaaadaaaaaaigaabaaaadaaaaaaeghobaaa
abaaaaaaaagabaaaaaaaaaaadcaaaaalecaabaaaalaaaaaaakiacaiaebaaaaaa
aaaaaaaaabaaaaaaabeaaaaaaaaacaebbkaabaaaalaaaaaaefaaaaajpcaabaaa
alaaaaaaigaabaaaalaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaabpaaaead
akaabaaaabaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadoaaaaabbfaaaaabdbaaaaahbcaabaaaaaaaaaaaabeaaaaa
ipmcpfdmdkaabaaaaaaaaaaadiaaaaakdcaabaaaabaaaaaajgafbaaaabaaaaaa
aceaaaaaaaaajgedaaaajgedaaaaaaaaaaaaaaaaebaaaaafdcaabaaaabaaaaaa
egaabaaaabaaaaaadiaaaaakpcaabaaaanaaaaaaagafbaaaabaaaaaaaceaaaaa
aaaakaebaaaakaebaaaakaebaaaakaebbnaaaaaipcaabaaaanaaaaaaegaobaaa
anaaaaaafgapbaiaebaaaaaaanaaaaaadhaaaaappcaabaaaanaaaaaaegaobaaa
anaaaaaaaceaaaaaaaaakaebmnmmemdnaaaakaebmnmmemdnaceaaaaaaaaakamb
mnmmemlnaaaakambmnmmemlndiaaaaahdcaabaaaabaaaaaaegaabaaaabaaaaaa
ngafbaaaanaaaaaabkaaaaafdcaabaaaabaaaaaaegaabaaaabaaaaaadiaaaaah
dcaabaaaabaaaaaaegaabaaaabaaaaaaigaabaaaanaaaaaabiaaaaakdcaabaaa
abaaaaaaegaabaaaabaaaaaaaceaaaaaaaaacaebaaaacaebaaaaaaaaaaaaaaaa
dmaaaaahicaabaaaaaaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaah
bcaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaddddlddodcaaaaajicaabaaaaaaaaaaa
akaabaaaacaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaibcaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaa
dkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaaakaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabiaaaaakhcaabaaaabaaaaaa
egacbaaaacaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaah
bcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaahbcaabaaa
abaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaadhaaaaajicaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaaiadpdkaabaaaaaaaaaaadbaaaaahbcaabaaa
abaaaaaaabeaaaaamnmmemdodkaabaaaaaaaaaaabpaaaeadakaabaaaabaaaaaa
dbaaaaahbcaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaaaeaaaaaadjaaaaak
gcaabaaaabaaaaaafgagbaaaaeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadmaaaaahbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
dmaaaaahbcaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaadgaaaaaf
ccaabaaaabaaaaaaabeaaaaamnmmemdobcaaaaabdgaaaaafbcaabaaaabaaaaaa
abeaaaaaaaaaaaaabfaaaaabdhaaaaajicaabaaaaaaaaaaaakaabaaaabaaaaaa
bkaabaaaabaaaaaadkaabaaaaaaaaaaadbaaaaakhcaabaaaabaaaaaaaceaaaaa
mnmmmmdnopoooodolmlldldpaaaaaaaapgapbaaaaaaaaaaadbaaaaakhcaabaaa
acaaaaaapgapbaaaaaaaaaaaaceaaaaaopoogodobbbbbbdpmnmmemdpaaaaaaaa
abaaaaahhcaabaaaabaaaaaaegacbaaaabaaaaaaegacbaaaacaaaaaadmaaaaah
bcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaadmaaaaahbcaabaaa
abaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaabpaaaeadakaabaaaabaaaaaa
dcaaaaajbcaabaaaabaaaaaaakaabaaaaiaaaaaaabeaaaaaaaaahpedabeaaaaa
aaaaialpdiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaijiiaidn
bnaaaaaiccaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
bkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaadhaaaaakbcaabaaa
abaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
biaaaaakocaabaaaabaaaaaaagajbaaaaiaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaiadpaaaaiadpabaaaaahccaabaaaabaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaaabaaaaahccaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaabaaaaaa
dhaaaaajbcaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaiadpakaabaaa
abaaaaaadbaaaaahccaabaaaabaaaaaaabeaaaaamnmmemdoakaabaaaabaaaaaa
bpaaaeadbkaabaaaabaaaaaadbaaaaahccaabaaaabaaaaaaabeaaaaaibiaiadl
akaabaaaahaaaaaadjaaaaakmcaabaaaabaaaaaafgajbaaaahaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaabaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaadmaaaaahccaabaaaabaaaaaadkaabaaaabaaaaaa
bkaabaaaabaaaaaadgaaaaafecaabaaaabaaaaaaabeaaaaamnmmemdobcaaaaab
dgaaaaafccaabaaaabaaaaaaabeaaaaaaaaaaaaabfaaaaabdhaaaaajbcaabaaa
abaaaaaabkaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaadcaaaaaj
ccaabaaaabaaaaaaakaabaaaafaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialp
diaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaijiiaidnbnaaaaai
ecaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaabkaaaaag
ccaabaaaabaaaaaabkaabaiaibaaaaaaabaaaaaadhaaaaakccaabaaaabaaaaaa
ckaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaabiaaaaak
ocaabaaaacaaaaaaagajbaaaafaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaiadp
aaaaiadpabaaaaahecaabaaaabaaaaaackaabaaaacaaaaaabkaabaaaacaaaaaa
abaaaaahecaabaaaabaaaaaadkaabaaaacaaaaaackaabaaaabaaaaaadhaaaaaj
ccaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaaaaaiadpbkaabaaaabaaaaaa
dbaaaaahecaabaaaabaaaaaaabeaaaaamnmmemdobkaabaaaabaaaaaabpaaaead
ckaabaaaabaaaaaadbaaaaahecaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaa
akaaaaaadjaaaaakgcaabaaaacaaaaaafgagbaaaakaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadmaaaaahecaabaaaabaaaaaackaabaaaabaaaaaa
bkaabaaaacaaaaaadmaaaaahecaabaaaabaaaaaackaabaaaacaaaaaackaabaaa
abaaaaaadgaaaaaficaabaaaabaaaaaaabeaaaaamnmmemdobcaaaaabdgaaaaaf
ecaabaaaabaaaaaaabeaaaaaaaaaaaaabfaaaaabdhaaaaajccaabaaaabaaaaaa
ckaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaabaaaaaadbaaaaahdcaabaaa
abaaaaaapgapbaaaaaaaaaaaegaabaaaabaaaaaadmaaaaahbcaabaaaabaaaaaa
bkaabaaaabaaaaaaakaabaaaabaaaaaadcaaaaajccaabaaaabaaaaaaakaabaaa
amaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaabeaaaaaijiiaidnbnaaaaaiecaabaaaabaaaaaabkaabaaa
abaaaaaabkaabaiaebaaaaaaabaaaaaabkaaaaagccaabaaaabaaaaaabkaabaia
ibaaaaaaabaaaaaadhaaaaakccaabaaaabaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaabkaabaiaebaaaaaaabaaaaaabiaaaaakocaabaaaacaaaaaaagajbaaa
amaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaiadpaaaaiadpabaaaaahecaabaaa
abaaaaaackaabaaaacaaaaaabkaabaaaacaaaaaaabaaaaahecaabaaaabaaaaaa
dkaabaaaacaaaaaackaabaaaabaaaaaadhaaaaajccaabaaaabaaaaaackaabaaa
abaaaaaaabeaaaaaaaaaiadpbkaabaaaabaaaaaadbaaaaahecaabaaaabaaaaaa
abeaaaaamnmmemdobkaabaaaabaaaaaabpaaaeadckaabaaaabaaaaaadbaaaaah
ecaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaaajaaaaaadjaaaaakgcaabaaa
acaaaaaafgagbaaaajaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
dmaaaaahecaabaaaabaaaaaackaabaaaabaaaaaabkaabaaaacaaaaaadmaaaaah
ecaabaaaabaaaaaackaabaaaacaaaaaackaabaaaabaaaaaadgaaaaaficaabaaa
abaaaaaaabeaaaaamnmmemdobcaaaaabdgaaaaafecaabaaaabaaaaaaabeaaaaa
aaaaaaaabfaaaaabdhaaaaajccaabaaaabaaaaaackaabaaaabaaaaaadkaabaaa
abaaaaaabkaabaaaabaaaaaadbaaaaahccaabaaaabaaaaaadkaabaaaaaaaaaaa
bkaabaaaabaaaaaadmaaaaahbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaa
abaaaaaadcaaaaajccaabaaaabaaaaaaakaabaaaagaaaaaaabeaaaaaaaaahped
abeaaaaaaaaaialpdiaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaa
ijiiaidnbnaaaaaiecaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaa
abaaaaaabkaaaaagccaabaaaabaaaaaabkaabaiaibaaaaaaabaaaaaadhaaaaak
ccaabaaaabaaaaaackaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaa
abaaaaaabiaaaaakocaabaaaacaaaaaaagajbaaaagaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaiadpaaaaiadpabaaaaahecaabaaaabaaaaaackaabaaaacaaaaaa
bkaabaaaacaaaaaaabaaaaahecaabaaaabaaaaaadkaabaaaacaaaaaackaabaaa
abaaaaaadhaaaaajccaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaaaaaiadp
bkaabaaaabaaaaaadbaaaaahecaabaaaabaaaaaaabeaaaaamnmmemdobkaabaaa
abaaaaaabpaaaeadckaabaaaabaaaaaadbaaaaahecaabaaaabaaaaaaabeaaaaa
ibiaiadlakaabaaaadaaaaaadjaaaaakgcaabaaaacaaaaaafgagbaaaadaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahecaabaaaabaaaaaa
ckaabaaaabaaaaaabkaabaaaacaaaaaadmaaaaahecaabaaaabaaaaaackaabaaa
acaaaaaackaabaaaabaaaaaadgaaaaaficaabaaaabaaaaaaabeaaaaamnmmemdo
bcaaaaabdgaaaaafecaabaaaabaaaaaaabeaaaaaaaaaaaaabfaaaaabdhaaaaaj
ccaabaaaabaaaaaackaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaabaaaaaa
dbaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaadmaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaadhaaaaajbcaabaaa
abaaaaaaakaabaaaacaaaaaaabeaaaaaaaaaiadpabeaaaaaddddlddodhaaaaaj
bcaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaaakaabaaaaaaaaaaa
diaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaackaabaaaaaaaaaaabfaaaaab
aaaaaaahicaabaaaaaaaaaaaakaabaaaalaaaaaaakaabaaaalaaaaaadiaaaaah
bcaabaaaabaaaaaadkbabaaaacaaaaaadkbabaaaacaaaaaadcaaaaakccaabaaa
abaaaaaackaabaiaebaaaaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaiadp
dcaaaaakicaabaaaaaaaaaaaakaabaiaebaaaaaaabaaaaaabkaabaaaabaaaaaa
dkaabaaaaaaaaaaadcaaaaalccaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaa
abaaaaaaabeaaaaajkjjbjdobkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaamiedeaaaaaafccaabaaaaaaaaaaabkaabaaa
aaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaklkkkkdo
bnaaaaaibcaabaaaabaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
bkaaaaagccaabaaaaaaaaaaabkaabaiaibaaaaaaaaaaaaaadhaaaaakccaabaaa
aaaaaaaaakaabaaaabaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
biaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaaadcaaaaaj
bcaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaaghggogloabeaaaaajkjjbjdp
aaaaaaahbcaabaaaabaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaadhaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaadkaabaaaaaaaaaaa
diaaaaahicaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaaaaaaaadpdbaaaaah
ccaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaabpaaaeadbkaabaaa
aaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadoaaaaabbfaaaaabaaaaaaaiccaabaaaaaaaaaaackaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpdiaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaaaaaaaaadiaaaaahiccabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaa
jkjjbjdpdgaaaaaihccabaaaaaaaaaaaaceaaaaafclifodpomfbdidpddddlddo
aaaaaaaadoaaaaab"
}




}
 }
}
}