// Compiled shader for all platforms, uncompressed size: 39.7KB

Shader "Futile/WaterLight" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 97 math, 6 texture, 7 branch
 //       gles3 : 97 math, 6 texture, 7 branch
 //   glesdesktop : 97 math, 6 texture, 7 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 55 math, 6 texture, 9 branch
 //        d3d9 : 131 math, 6 texture, 4 branch
 //       metal : 97 math, 6 texture, 7 branch
 //      opengl : 119 math, 6 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 96
Vector 80 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedkioagoejkaaojogofkbibfacjaabnikgabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaagaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaafaaaaaa
ogikcaaaaaaaaaaaafaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 55 math, 6 textures, 9 branches
SetTexture 0 [_LevelTex] 2D 2
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_NoiseTex] 2D 3
SetTexture 3 [_MainTex] 2D 1
ConstBuffer "$Globals" 96
Float 16 [_waterPosition]
Float 20 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
Vector 64 [_camInRoomRect]
BindCB  "$Globals" 0
"ps_4_0
eefiecedjnfaajmkmmbkfpjdcodfbefjaekannneabaaaaaaoaakaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcomajaaaaeaaaaaaahlacaaaafjaaaaae
egiocaaaaaaaaaaaafaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaae
aahabaaaacaaaaaaffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaagcbaaaad
dcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadicbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacahaaaaaadiaaaaaihcaabaaaaaaaaaaa
ogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafhcaabaaaaaaaaaaa
egacbaaaaaaaaaaaaoaaaaaihcaabaaaaaaaaaaaegacbaaaaaaaaaaaegiacaaa
aaaaaaaaadaaaaaaaaaaaaajhcaabaaaaaaaaaaaegacbaaaaaaaaaaaegiacaia
ebaaaaaaaaaaaaaaacaaaaaaaaaaaaakhcaabaaaabaaaaaaegiacaiaebaaaaaa
aaaaaaaaacaaaaaaogikcaaaaaaaaaaaacaaaaaaaoaaaaahhcaabaaaaaaaaaaa
egacbaaaaaaaaaaaegacbaaaabaaaaaaefaaaaajpcaabaaaabaaaaaaggakbaaa
aaaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadcaaaaajicaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaa
dkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaadkaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaadbaaaaahicaabaaaabaaaaaa
dkaabaaaaaaaaaaaabeaaaaaijiiiidnbiaaaaaibcaabaaaacaaaaaaakiacaaa
aaaaaaaaabaaaaaaabeaaaaaaaaaaaaaabaaaaahicaabaaaabaaaaaadkaabaaa
abaaaaaaakaabaaaacaaaaaadcaaaaapdcaabaaaacaaaaaaogbkbaaaabaaaaaa
aceaaaaaaaaaiadpaaaaialpaaaaaaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaaaaaaaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaaeghobaaa
abaaaaaaaagabaaaaaaaaaaadiaaaaakdcaabaaaadaaaaaapgapbaaaaaaaaaaa
aceaaaaakmkkkkdomommemdoaaaaaaaaaaaaaaaaaaaaaaalhcaabaaaaeaaaaaa
ggakbaiaebaaaaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaaaa
dcaaaaajncaabaaaadaaaaaaagaebaaaadaaaaaaagajbaaaaeaaaaaaagajbaaa
aaaaaaaadiaaaaakfcaabaaaaaaaaaaaagadbaaaadaaaaaaaceaaaaaggggagea
aaaaaaaaggggkgdpaaaaaaaadcaaaaamdcaabaaaafaaaaaapgapbaaaaaaaaaaa
aceaaaaamommmmdncgejbcdoaaaaaaaaaaaaaaaaigaabaaaaaaaaaaadcaaaaak
bcaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmmmdnbkaabaaa
adaaaaaadcaaaaajecaabaaaafaaaaaackaabaaaadaaaaaaabeaaaaaggggagea
akaabaaaaaaaaaaaefaaaaajpcaabaaaadaaaaaaigaabaaaafaaaaaaeghobaaa
acaaaaaaaagabaaaadaaaaaadiaaaaakfcaabaaaaaaaaaaapgapbaaaaaaaaaaa
aceaaaaaaaaaaadoaaaaaaaakmkkckdoaaaaaaaadcaaaaakbcaabaaaaaaaaaaa
bkiacaaaaaaaaaaaabaaaaaaabeaaaaadnakfhloakaabaaaaaaaaaaadcaaaaaj
ccaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaeaaaaaabkaabaaaaaaaaaaa
dcaaaaajicaabaaaafaaaaaabkaabaaaaaaaaaaaabeaaaaaggggkgdpakaabaaa
aaaaaaaaefaaaaajpcaabaaaaeaaaaaangafbaaaafaaaaaaeghobaaaacaaaaaa
aagabaaaadaaaaaaaaaaaaaibcaabaaaaaaaaaaabkbabaaaabaaaaaabkiacaaa
aaaaaaaaabaaaaaadcaaaaajccaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
mommmmdnakaabaaaaaaaaaaadgaaaaafbcaabaaaaaaaaaaaakbabaaaabaaaaaa
efaaaaajpcaabaaaafaaaaaaegaabaaaaaaaaaaaeghobaaaacaaaaaaaagabaaa
adaaaaaadcaaaaaldcaabaaaaaaaaaaaogikcaaaaaaaaaaaaeaaaaaaogbkbaaa
abaaaaaaegiacaaaaaaaaaaaaeaaaaaaefaaaaajpcaabaaaagaaaaaaegaabaaa
aaaaaaaaeghobaaaadaaaaaaaagabaaaabaaaaaabpaaaeaddkaabaaaabaaaaaa
dgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
doaaaaabbfaaaaabdbaaaaahbcaabaaaaaaaaaaaabeaaaaamnmmemdodkaabaaa
aaaaaaaabpaaaeadakaabaaaaaaaaaaadjaaaaakhcaabaaaaaaaaaaaegacbaaa
acaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahbcaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaahbcaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadgaaaaai
pccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaab
bfaaaaabbfaaaaabbiaaaaakhcaabaaaaaaaaaaaegacbaaaabaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaaaaaaaaabkaabaaa
aaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabdiaaaaal
dcaabaaaaaaaaaaafgifcaaaaaaaaaaaabaaaaaaaceaaaaaaaaamaeamnmmcmea
aaaaaaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaadaaaaaaabeaaaaa
aaaaoaeaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaamdpfmieaenaaaaagbcaabaaaaaaaaaaaaanaaaaaakaabaaaaaaaaaaa
dcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaa
aaaaaadpdcaaaaajccaabaaaaaaaaaaaakaabaaaaeaaaaaaabeaaaaafmipmkea
bkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
mdpfmieaenaaaaagccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadp
deaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaacpaaaaaf
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaadmecbjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
aaaaaaaiccaabaaaaaaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
diaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaaakaabaaaafaaaaaaakaabaaaafaaaaaadiaaaaahbcaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaa
ckaabaaaagaaaaaaakaabaaaaaaaaaaadbaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaamnmmmmdnbpaaaeadakaabaaaaaaaaaaadgaaaaaipccabaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaab
dgaaaaaihccabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
diaaaaahiccabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaamnmmemdndoaaaaab
"
}




}
 }
}
}