// Compiled shader for all platforms, uncompressed size: 53.9KB

Shader "Futile/SceneOverlay" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 141 math, 11 texture, 8 branch
 //       gles3 : 141 math, 11 texture, 8 branch
 //   glesdesktop : 141 math, 11 texture, 8 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 58 math, 11 texture, 4 branch
 //        d3d9 : 119 math, 11 texture, 8 branch
 //       metal : 141 math, 11 texture, 8 branch
 //      opengl : 341 math, 43 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 64
Vector 48 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedobbfnlbielpdbdjbfkojielgagjmifddabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaaeaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaadaaaaaa
ogikcaaaaaaaaaaaadaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 58 math, 11 textures, 4 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 64
Float 16 [_BlurDepth]
Vector 20 [_MenuCamPos] 2
Float 28 [_BlurRange]
BindCB  "$Globals" 0
"ps_4_0
eefiecedogfbkgjmdmohhoahigolijalfgimcllmabaaaaaabeamaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefccaalaaaaeaaaaaaamiacaaaafjaaaaae
egiocaaaaaaaaaaaacaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaad
pcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacajaaaaaadiaaaaah
bcaabaaaaaaaaaaackbabaaaacaaaaaaabeaaaaaaaaacaebdcaaaaapgcaabaaa
aaaaaaaaagbbbaaaacaaaaaaaceaaaaaaaaaaaaaaaoakoeeaamaeheeaaaaaaaa
aceaaaaaaaaaaaaaaaaaiadpaaaaiadpaaaaaaaadiaaaaakdcaabaaaabaaaaaa
egbabaaaabaaaaaaaceaaaaaaaaaiadpaaaaaadpaaaaaaaaaaaaaaaaefaaaaaj
pcaabaaaabaaaaaaegaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaa
aaaaaaaiicaabaaaaaaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
dcaaaaajbcaabaaaabaaaaaabkbabaaaabaaaaaaabeaaaaaaaaaaadpabeaaaaa
aaaaaadpaaaaaaajgcaabaaaabaaaaaaagbbbaiaebaaaaaaabaaaaaafgigcaaa
aaaaaaaaabaaaaaadiaaaaahgcaabaaaabaaaaaapgapbaaaaaaaaaaafgagbaaa
abaaaaaadcaaaaakecaabaaaacaaaaaabkaabaiaebaaaaaaabaaaaaaabeaaaaa
mnmmmmdmakbabaaaabaaaaaadcaaaaakbcaabaaaabaaaaaackaabaiaebaaaaaa
abaaaaaaabeaaaaamnmmmmdmakaabaaaabaaaaaaaoaaaaakccaabaaaabaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaah
ccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaadpdeaaaaahccaabaaa
acaaaaaaakaabaaaabaaaaaabkaabaaaabaaaaaaefaaaaajpcaabaaaadaaaaaa
ggakbaaaacaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaaaoaaaaahccaabaaa
aaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaaaeaakaabaaaaaaaaaaaaaaaaaajbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaaabaaaaaadicaaaaj
bcaabaaaaaaaaaaaakaabaiaibaaaaaaaaaaaaaadkiacaaaaaaaaaaaabaaaaaa
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaagpbciddkdgaaaaaf
pcaabaaaaeaaaaaaegaobaaaadaaaaaadgaaaaaimcaabaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaiadpaaaaiadpdgaaaaaifcaabaaaabaaaaaaaceaaaaa
aaaaiadpaaaaaaaaaaaaaaaaaaaaaaaadaaaaaabcbaaaaahicaabaaaabaaaaaa
ckaabaaaabaaaaaaabeaaaaaafaaaaaaadaaaeaddkaabaaaabaaaaaaaaaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaiadpdiaaaaahicaabaaa
abaaaaaadkaabaaaaaaaaaaaabeaaaaabpifgldpdiaaaaahbcaabaaaafaaaaaa
akaabaaaaaaaaaaaakaabaaaabaaaaaadcaaaaakicaabaaaacaaaaaaakaabaia
ebaaaaaaabaaaaaaakaabaaaaaaaaaaabkaabaaaacaaaaaadbaaaaahccaabaaa
afaaaaaabkaabaaaabaaaaaadkaabaaaacaaaaaaefaaaaajpcaabaaaagaaaaaa
ogakbaaaacaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaabpaaaeadbkaabaaa
afaaaaaadcaaaaajpcaabaaaaeaaaaaaegaobaaaagaaaaaapgapbaaaabaaaaaa
egaobaaaaeaaaaaadcaaaaajecaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
bpifgldpckaabaaaaaaaaaaabfaaaaabdcaaaaakbcaabaaaacaaaaaaakaabaia
ebaaaaaaafaaaaaabkaabaaaaaaaaaaackaabaaaacaaaaaaefaaaaajpcaabaaa
agaaaaaaegaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaaj
pcaabaaaagaaaaaaegaobaaaagaaaaaapgapbaaaabaaaaaaegaobaaaaeaaaaaa
dcaaaaajbcaabaaaacaaaaaaakaabaaaafaaaaaabkaabaaaaaaaaaaackaabaaa
acaaaaaaefaaaaajpcaabaaaahaaaaaaegaabaaaacaaaaaaeghobaaaaaaaaaaa
aagabaaaabaaaaaadcaaaaajpcaabaaaagaaaaaaegaobaaaahaaaaaapgapbaaa
abaaaaaaegaobaaaagaaaaaadcaaaaajicaabaaaacaaaaaaakaabaaaabaaaaaa
akaabaaaaaaaaaaabkaabaaaacaaaaaaefaaaaajpcaabaaaahaaaaaaogakbaaa
acaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaajpcaabaaaagaaaaaa
egaobaaaahaaaaaapgapbaaaabaaaaaaegaobaaaagaaaaaadcaaaaajbcaabaaa
acaaaaaadkaabaaaaaaaaaaaabeaaaaanhkddaeackaabaaaaaaaaaaadiaaaaah
icaabaaaacaaaaaaakaabaaaafaaaaaaabeaaaaaomfbdidpdcaaaaakecaabaaa
ahaaaaaaakaabaiaebaaaaaaafaaaaaaabeaaaaaomfbdidpbkaabaaaacaaaaaa
dbaaaaahccaabaaaafaaaaaabkaabaaaabaaaaaackaabaaaahaaaaaadcaaaaak
ccaabaaaahaaaaaadkaabaiaebaaaaaaacaaaaaabkaabaaaaaaaaaaackaabaaa
acaaaaaaefaaaaajpcaabaaaaiaaaaaajgafbaaaahaaaaaaeghobaaaaaaaaaaa
aagabaaaabaaaaaabpaaaeadbkaabaaaafaaaaaadcaaaaajpcaabaaaagaaaaaa
egaobaaaaiaaaaaapgapbaaaabaaaaaaegaobaaaagaaaaaadcaaaaajbcaabaaa
acaaaaaadkaabaaaaaaaaaaaabeaaaaabpifgldpakaabaaaacaaaaaabfaaaaab
dcaaaaajbcaabaaaahaaaaaadkaabaaaacaaaaaabkaabaaaaaaaaaaackaabaaa
acaaaaaaefaaaaajpcaabaaaaiaaaaaaigaabaaaahaaaaaaeghobaaaaaaaaaaa
aagabaaaabaaaaaabpaaaeadbkaabaaaafaaaaaadcaaaaajpcaabaaaagaaaaaa
egaobaaaaiaaaaaapgapbaaaabaaaaaaegaobaaaagaaaaaadcaaaaajbcaabaaa
acaaaaaadkaabaaaaaaaaaaaabeaaaaabpifgldpakaabaaaacaaaaaabfaaaaab
dcaaaaajicaabaaaahaaaaaaakaabaaaafaaaaaaabeaaaaaomfbdidpbkaabaaa
acaaaaaaefaaaaajpcaabaaaafaaaaaangafbaaaahaaaaaaeghobaaaaaaaaaaa
aagabaaaabaaaaaadcaaaaajpcaabaaaafaaaaaaegaobaaaafaaaaaapgapbaaa
abaaaaaaegaobaaaagaaaaaaefaaaaajpcaabaaaagaaaaaamgaabaaaahaaaaaa
eghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaajpcaabaaaaeaaaaaaegaobaaa
agaaaaaapgapbaaaabaaaaaaegaobaaaafaaaaaadcaaaaajecaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaabpifoldpakaabaaaacaaaaaaboaaaaahecaabaaa
abaaaaaackaabaaaabaaaaaaabeaaaaaabaaaaaadgaaaaaficaabaaaaaaaaaaa
dkaabaaaabaaaaaabgaaaaabaoaaaaahpcaabaaaaaaaaaaaegaobaaaaeaaaaaa
kgakbaaaaaaaaaaadiaaaaahbcaabaaaabaaaaaadkbabaaaacaaaaaadkbabaaa
acaaaaaadcaaaaapgcaabaaaabaaaaaakgblbaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaialpaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaaaaa
efaaaaajpcaabaaaacaaaaaajgafbaaaabaaaaaaeghobaaaabaaaaaaaagabaaa
aaaaaaaadbaaaaakocaabaaaabaaaaaaagajbaaaacaaaaaaaceaaaaaaaaaaaaa
aaaaaadpaaaaaadpaaaaaadpapaaaaahicaabaaaacaaaaaaagaabaaaacaaaaaa
agaabaaaaaaaaaaaaaaaaaalhcaabaaaadaaaaaaegacbaiaebaaaaaaaaaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaaaaaaaahhcaabaaaadaaaaaa
egacbaaaadaaaaaaegacbaaaadaaaaaaaaaaaaalhcaabaaaaeaaaaaaegacbaia
ebaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadcaaaaan
hcaabaaaadaaaaaaegacbaiaebaaaaaaadaaaaaaegacbaaaaeaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaaaaadhaaaaajbccabaaaaaaaaaaabkaabaaa
abaaaaaadkaabaaaacaaaaaaakaabaaaadaaaaaaapaaaaahbcaabaaaaaaaaaaa
fgafbaaaacaaaaaafgafbaaaaaaaaaaadhaaaaajcccabaaaaaaaaaaackaabaaa
abaaaaaaakaabaaaaaaaaaaabkaabaaaadaaaaaaapaaaaahbcaabaaaaaaaaaaa
kgakbaaaacaaaaaakgakbaaaaaaaaaaadhaaaaajeccabaaaaaaaaaaadkaabaaa
abaaaaaaakaabaaaaaaaaaaackaabaaaadaaaaaadiaaaaahiccabaaaaaaaaaaa
dkaabaaaaaaaaaaaakaabaaaabaaaaaadoaaaaab"
}




}
 }
}
}