// Compiled shader for all platforms, uncompressed size: 36.3KB

Shader "Futile/Map" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 80 math, 3 texture, 10 branch
 //       gles3 : 80 math, 3 texture, 10 branch
 //   glesdesktop : 80 math, 3 texture, 10 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 58 math, 2 texture, 14 branch
 //        d3d9 : 121 math, 3 texture, 7 branch
 //       metal : 80 math, 3 texture, 10 branch
 //      opengl : 116 math, 2 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 58 math, 2 textures, 14 branches
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_mapFogTexture] 2D 1
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 20 [_screenSize] 2
Vector 32 [_mapSize] 2
Vector 40 [_mapPan] 2
Vector 48 [_MapCol]
BindCB  "$Globals" 0
"ps_4_0
eefiecedmhhabkijalegncnjigpibbncpjibefekabaaaaaahiakaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcieajaaaaeaaaaaaagbacaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaad
pcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacadaaaaaaaaaaaaak
pcaabaaaaaaaaaaaogbebaaaabaaaaaaaceaaaaaaaaaaalpaaaaaalpaaaaaalp
aaaaaalpapaaaaahbcaabaaaabaaaaaaegaabaaaaaaaaaaaegaabaaaaaaaaaaa
elaaaaafccaabaaaabaaaaaaakaabaaaabaaaaaaddaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaabeaaaaaaaaaiadpeeaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaadiaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaaagaabaaaabaaaaaa
diaaaaakdcaabaaaaaaaaaaaegaabaaaaaaaaaaaaceaaaaamnmmimdomnmmimdo
aaaaaaaaaaaaaaaacpaaaaafbcaabaaaabaaaaaabkaabaaaabaaaaaadiaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaamdpfeieabjaaaaafbcaabaaa
abaaaaaaakaabaaaabaaaaaadiaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
agaabaaaabaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
klkkckdodiaaaaaldcaabaaaabaaaaaaegiacaaaaaaaaaaaacaaaaaaaceaaaaa
gpbcaddlgpbcaddlaaaaaaaaaaaaaaaaaoaaaaahdcaabaaaacaaaaaaegaabaaa
aaaaaaaaegaabaaaabaaaaaabiaaaaakdcaabaaaaaaaaaaakgbkbaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaaiadpabeaaaaaaaaaaadpdhaaaaajbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaaabkaabaaaaaaaaaaaaoaaaaaj
dcaabaaaabaaaaaajgifcaaaaaaaaaaaabaaaaaaegiacaaaaaaaaaaaacaaaaaa
diaaaaahgcaabaaaaaaaaaaakgalbaaaaaaaaaaaagabbaaaabaaaaaadcaaaaaj
icaabaaaaaaaaaaabkbabaaaacaaaaaaabeaaaaaaaaamadpabeaaaaaaaaafaea
aoaaaaahgcaabaaaaaaaaaaafgagbaaaaaaaaaaapgapbaaaaaaaaaaaaaaaaaai
bcaabaaaabaaaaaabkaabaaaaaaaaaaackiacaaaaaaaaaaaacaaaaaadiaaaaah
ccaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdpdcaaaaakicaabaaa
aaaaaaaadkiacaaaaaaaaaaaacaaaaaaabeaaaaaklkkkkdobkaabaaaaaaaaaaa
dcaaaaajccaabaaaabaaaaaackaabaaaaaaaaaaaabeaaaaaklkkkkdodkaabaaa
aaaaaaaaaaaaaaaidcaabaaaabaaaaaaegaabaiaebaaaaaaacaaaaaaegaabaaa
abaaaaaadbaaaaahecaabaaaaaaaaaaabkaabaaaabaaaaaabkaabaaaaaaaaaaa
dcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaeaabeaaaaa
aaaaiadpdiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkkkdo
dbaaaaahicaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaabaaaaaadhaaaaaj
bcaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaabaaaaaa
dhaaaaajecaabaaaabaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaa
aaaaaaaaefaaaaajpcaabaaaaaaaaaaaigaabaaaabaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaadbaaaaahicaabaaaaaaaaaaaabeaaaaaaaaaaadpbkaabaaa
aaaaaaaaefaaaaajpcaabaaaacaaaaaaigaabaaaabaaaaaaeghobaaaabaaaaaa
aagabaaaabaaaaaadbaaaaahccaabaaaabaaaaaaakaabaaaacaaaaaaabeaaaaa
aaaaaadpdmaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaa
bpaaaeaddkaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaadkbabaaaacaaaaaa
abeaaaaadddddddpaaaaaaaiccaabaaaabaaaaaaakbabaiaebaaaaaaacaaaaaa
abeaaaaaaaaaiadpdiaaaaahiccabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaa
abaaaaaadgaaaaaihccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadoaaaaabbfaaaaabbnaaaaahicaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaajkjjjjdobnaaaaahccaabaaaabaaaaaaabeaaaaadddddddpakaabaaa
aaaaaaaaabaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaa
biaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaaaabaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaaaaaaaaaabpaaaeadbkaabaaa
aaaaaaaadgaaaaaihccabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaaaaadgaaaaaficcabaaaaaaaaaaadkbabaaaacaaaaaadoaaaaabbcaaaaab
dbaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaajkjjjjdobpaaaead
bkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaa
dddddddpaaaaaaaiicaabaaaaaaaaaaaakbabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdiaaaaahiccabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaa
dgaaaaaihccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
doaaaaabbcaaaaabdiaaaaaiccaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaa
abeaaaaaaaaajgecaoaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaa
aaaaaaaaacaaaaaaaaaaaaaiccaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
akaabaaaabaaaaaadiaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaa
aaaaaaaaacaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaiadoenaaaaagccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaammmmmmdoabeaaaaaaaaaaadp
diaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadbaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaa
aaaaaaaadcaaaaajbcaabaaaaaaaaaaaakbabaaaacaaaaaaabeaaaaamnmmmmlo
abeaaaaaaaaaaadpdiaaaaahiccabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaa
acaaaaaadgaaaaaihccabaaaaaaaaaaaaceaaaaamnmmemdnmnmmemdnmnmmemdp
aaaaaaaadoaaaaabbcaaaaabdbaaaaahbcaabaaaaaaaaaaaakaabaaaacaaaaaa
abeaaaaahbdnakdpbpaaaeadakaabaaaaaaaaaaadgaaaaaghccabaaaaaaaaaaa
egiccaaaaaaaaaaaadaaaaaadgaaaaaficcabaaaaaaaaaaadkbabaaaacaaaaaa
doaaaaabbcaaaaabdiaaaaahbcaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaa
mnmmmmdoaaaaaaaiccaabaaaaaaaaaaaakbabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdiaaaaahiccabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaa
dgaaaaaihccabaaaaaaaaaaaaceaaaaaaaaaiadoaaaaiadoaaaaiadoaaaaaaaa
doaaaaabbfaaaaabbfaaaaabbfaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}