// Compiled shader for all platforms, uncompressed size: 36.3KB

Shader "Futile/Rainbow" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 90 math, 6 texture, 3 branch
 //       gles3 : 90 math, 6 texture, 3 branch
 //   glesdesktop : 90 math, 6 texture, 3 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 55 math, 6 texture, 3 branch
 //        d3d9 : 127 math, 6 texture, 2 branch
 //       metal : 90 math, 6 texture, 3 branch
 //      opengl : 116 math, 6 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 55 math, 6 textures, 3 branches
SetTexture 0 [_NoiseTex2] 2D 4
SetTexture 1 [_NoiseTex] 2D 3
SetTexture 2 [_MainTex] 2D 1
SetTexture 3 [_LevelTex] 2D 2
SetTexture 4 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedaaoikgjjhpafilfpgaddplmldbikdikbabaaaaaammakaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapajaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcniajaaaaeaaaaaaahgacaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafkaaaaad
aagabaaaaeaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaa
abaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaafibiaaaeaahabaaa
adaaaaaaffffaaaafibiaaaeaahabaaaaeaaaaaaffffaaaagcbaaaaddcbabaaa
abaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadjcbabaaaacaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacaiaaaaaadiaaaaaidcaabaaaaaaaaaaaogbkbaaa
abaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaaaaaaaaaaegaabaaa
aaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaa
adaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaa
aaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaiaebaaaaaaaaaaaaaa
acaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaaaaaaaaaaegaabaaa
aaaaaaaaogakbaaaaaaaaaaaaaaaaaakmcaabaaaaaaaaaaaagbebaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaalpaaaaaalpapaaaaahecaabaaaaaaaaaaa
ogakbaaaaaaaaaaaogakbaaaaaaaaaaaelaaaaafecaabaaaaaaaaaaackaabaaa
aaaaaaaaaaaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaackaabaaaaaaaaaaa
dbaaaaahbcaabaaaabaaaaaaabeaaaaaaaaaaadpckaabaaaaaaaaaaadbaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaakbabaaaacaaaaaadmaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaadiaaaaakfcaabaaaabaaaaaa
agaabaaaaaaaaaaaaceaaaaaaaaapaebaaaaaaaaaaaaiaeaaaaaaaaadiaaaaal
hcaabaaaacaaaaaaagiacaaaaaaaaaaaabaaaaaaaceaaaaaipmcpfdnaknhcddn
hcpjipdoaaaaaaaadcaaaaamdcaabaaaadaaaaaafgafbaaaaaaaaaaaaceaaaaa
aaaahaebaaaahaebaaaaaaaaaaaaaaaaigaabaaaacaaaaaadgaaaaaficaabaaa
abaaaaaaakaabaaaadaaaaaaefaaaaajpcaabaaaaeaaaaaamgaabaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaaeaaaaaadcaaaaajccaabaaaacaaaaaabkaabaaa
aaaaaaaaabeaaaaaaaaaaaeabkaabaaaacaaaaaadgaaaaafbcaabaaaacaaaaaa
ckaabaaaabaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaaeghobaaa
abaaaaaaaagabaaaadaaaaaadcaaaaakecaabaaaaaaaaaaackaabaaaaaaaaaaa
abeaaaaaaaaaaaeaakbabaiaebaaaaaaacaaaaaaaaaaaaaiccaabaaaabaaaaaa
akbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpaocaaaahccaabaaaafaaaaaa
ckaabaaaaaaaaaaabkaabaaaabaaaaaadgaaaaafbcaabaaaafaaaaaaabeaaaaa
aaaaaadpefaaaaajpcaabaaaagaaaaaaegaabaaaafaaaaaaeghobaaaacaaaaaa
aagabaaaabaaaaaaefaaaaajpcaabaaaahaaaaaaegaabaaaaaaaaaaaeghobaaa
adaaaaaaaagabaaaacaaaaaadgaaaaafecaabaaaadaaaaaaakaabaaaabaaaaaa
efaaaaajpcaabaaaabaaaaaaggakbaaaadaaaaaaeghobaaaaaaaaaaaaagabaaa
aeaaaaaadcaaaaapdcaabaaaaaaaaaaaogbkbaaaabaaaaaaaceaaaaaaaaaiadp
aaaaialpaaaaaaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaa
efaaaaajpcaabaaaadaaaaaaegaabaaaaaaaaaaaeghobaaaaeaaaaaaaagabaaa
aaaaaaaabpaaaeaddkaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabdcaaaaajbcaabaaa
aaaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaeaeaakaabaaaacaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaadeddhlebenaaaaagbcaabaaa
aaaaaaaaaanaaaaaakaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdiaaaaahccaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaeaeaebaaaaafccaabaaaaaaaaaaabkaabaaa
aaaaaaaadcaaaaakbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaeaea
bkaabaiaebaaaaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaaadpabeaaaaaaaaaaadpdbaaaaahccaabaaaaaaaaaaaabeaaaaa
ljpmhpdpakaabaaaaaaaaaaabpaaaeadbkaabaaaaaaaaaaadcaaaaajccaabaaa
aaaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaeaeaabeaaaaaaaaaiadpdicaaaah
hcaabaaaagaaaaaafgafbaaaaaaaaaaaegacbaaaagaaaaaaaaaaaaahccaabaaa
aaaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaiadpdiaaaaahbcaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaadgaaaaaficaabaaaagaaaaaaabeaaaaa
aaaaiadpbfaaaaabdiaaaaahccaabaaaaaaaaaaabkaabaaaafaaaaaaabeaaaaa
mdpfeieaenaaaaagccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaamadpddaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahbcaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadkaabaaaagaaaaaadiaaaaahccaabaaaaaaaaaaaakaabaaaahaaaaaa
abeaaaaaaaaahoedblaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaah
ecaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaiaceaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaaeoaaaaaiaanaaaaa
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaboaaaaaaciaaaaaficaabaaa
aaaaaaaabkaabaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaackaabaaaaaaaaaaa
dkaabaaaaaaaaaaabkaabaaaaaaaaaaaclaaaaafccaabaaaaaaaaaaabkaabaaa
aaaaaaaabiaaaaakhcaabaaaabaaaaaaegacbaaaahaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaaaaaabaaaaahecaabaaaaaaaaaaabkaabaaaabaaaaaa
akaabaaaabaaaaaaabaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaackaabaaa
aaaaaaaadcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaijiiaidn
abeaaaaamnmmemlodiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaamadpdeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaaa
dhaaaaajccaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaajkjjjjdpbkaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaa
aaaaaaalocaabaaaaaaaaaaaagajbaiaebaaaaaaadaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaiadpaaaaiadpdcaaaaanhcaabaaaabaaaaaaegacbaiaebaaaaaa
agaaaaaaagaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
dcaaaaanhccabaaaaaaaaaaajgahbaiaebaaaaaaaaaaaaaaegacbaaaabaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadgaaaaaficcabaaaaaaaaaaa
dkbabaaaacaaaaaadoaaaaab"
}




}
 }
}
}