// Compiled shader for all platforms, uncompressed size: 41.0KB

Shader "Futile/HazerHaze" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 99 math, 6 texture, 5 branch
 //       gles3 : 99 math, 6 texture, 5 branch
 //   glesdesktop : 99 math, 6 texture, 5 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 81 math, 6 texture, 5 branch
 //        d3d9 : 145 math, 6 texture, 2 branch
 //       metal : 99 math, 6 texture, 5 branch
 //      opengl : 137 math, 6 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 81 math, 6 textures, 5 branches
SetTexture 0 [_NoiseTex] 2D 2
SetTexture 1 [_NoiseTex2] 2D 3
SetTexture 2 [_CloudsTex] 2D 4
SetTexture 3 [_LevelTex] 2D 1
SetTexture 4 [_GrabTexture] 2D 0
SetTexture 5 [_PalTex] 2D 5
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
Float 56 [_waterLevel]
BindCB  "$Globals" 0
"ps_4_0
eefiecedmmgcjbdllphgajnmhjpgfooffjhmjgmcabaaaaaapeanaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapajaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcaaanaaaaeaaaaaaaeaadaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafkaaaaad
aagabaaaaeaaaaaafkaaaaadaagabaaaafaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaa
ffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaafibiaaaeaahabaaaaeaaaaaa
ffffaaaafibiaaaeaahabaaaafaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaa
gcbaaaadmcbabaaaabaaaaaagcbaaaadjcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaadiaaaaaidcaabaaaaaaaaaaaogbkbaaaabaaaaaa
egiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
aoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaaadaaaaaa
aaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaaaaaaaaaa
acaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaiaebaaaaaaaaaaaaaaacaaaaaa
kgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
ogakbaaaaaaaaaaaaaaaaaakmcaabaaaaaaaaaaaagbebaaaabaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaalpaaaaaalpapaaaaahecaabaaaaaaaaaaaogakbaaa
aaaaaaaaogakbaaaaaaaaaaaelaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaa
dcaaaaakecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaaaea
abeaaaaaaaaaiadpdeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
aaaaaaaadiaaaaakpcaabaaaabaaaaaaagaebaaaaaaaaaaaaceaaaaaaaaaeaea
aaaamadpddddhdebddddpdeadiaaaaaiicaabaaaaaaaaaaaakiacaaaaaaaaaaa
abaaaaaaabeaaaaajkjjbjdodcaaaaalccaabaaaacaaaaaaakiacaiaebaaaaaa
aaaaaaaaabaaaaaaabeaaaaamnmmmmdnbkaabaaaaaaaaaaadgaaaaaffcaabaaa
acaaaaaafgagbaaaabaaaaaaefaaaaajpcaabaaaadaaaaaaegaabaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaacaaaaaadcaaaaakecaabaaaabaaaaaaakiacaaa
aaaaaaaaabaaaaaaabeaaaaamnmmemdoakaabaaaadaaaaaadiaaaaahecaabaaa
abaaaaaackaabaaaabaaaaaaabeaaaaadeddhlebenaaaaagecaabaaaabaaaaaa
aanaaaaackaabaaaabaaaaaaaaaaaaaldcaabaaaacaaaaaaegaabaiaebaaaaaa
aaaaaaaaaceaaaaaaaaaaadpmdpfcidpaaaaaaaaaaaaaaaadiaaaaakdcaabaaa
acaaaaaaegaabaaaacaaaaaaaceaaaaaipmchflnipmchflnaaaaaaaaaaaaaaaa
cpaaaaafbcaabaaaadaaaaaackaabaaaaaaaaaaadiaaaaahbcaabaaaadaaaaaa
akaabaaaadaaaaaaabeaaaaaddddlddobjaaaaafbcaabaaaadaaaaaaakaabaaa
adaaaaaaaaaaaaaiccaabaaaadaaaaaackaabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaiadpdcaaaaajbcaabaaaadaaaaaaakaabaaaadaaaaaabkaabaaaadaaaaaa
ckaabaaaabaaaaaadcaaaaakicaabaaaacaaaaaaakiacaaaaaaaaaaaabaaaaaa
abeaaaaamnmmemlodkaabaaaabaaaaaaefaaaaajpcaabaaaaeaaaaaaogakbaaa
acaaaaaaeghobaaaabaaaaaaaagabaaaadaaaaaaaaaaaaaiicaabaaaabaaaaaa
dkbabaiaebaaaaaaacaaaaaaabeaaaaajkjjnjdpdcaaaaakicaabaaaabaaaaaa
akaabaiaebaaaaaaaeaaaaaadkaabaaaabaaaaaaakaabaaaadaaaaaadcaaaaak
ccaabaaaabaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaeaeadkaabaiaebaaaaaa
aaaaaaaadcaaaaajdcaabaaaabaaaaaaegaabaaaacaaaaaakgakbaaaabaaaaaa
egaabaaaabaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaabaaaaaaeghobaaa
acaaaaaaaagabaaaaeaaaaaadiaaaaahicaabaaaaaaaaaaaakaabaaaacaaaaaa
abeaaaaaaaaamadpdcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaadkaabaaa
aaaaaaaadkaabaaaabaaaaaadiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
dkbabaaaacaaaaaadiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaadkaabaaa
aaaaaaaaefaaaaajpcaabaaaabaaaaaaegaabaaaaaaaaaaaeghobaaaadaaaaaa
aagabaaaabaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaa
aaaahoedblaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahccaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaiaceaaaaaibcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaiaebaaaaaaaaaaaaaaeoaaaaaiaanaaaaabcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaboaaaaaaciaaaaaficaabaaaaaaaaaaa
akaabaaaaaaaaaaadhaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaa
aaaaaaaaakaabaaaaaaaaaaaclaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaijiiaidnbiaaaaak
hcaabaaaabaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaaaaaabaaaaahccaabaaaaaaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
abaaaaahccaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaaaaaaaaaadhaaaaaj
bcaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaomfbdidpakaabaaaaaaaaaaa
dbaaaaahccaabaaaaaaaaaaaabeaaaaamnmmemdoakaabaaaaaaaaaaaaaaaaaai
icaabaaaaaaaaaaadkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadpdcaaaaap
dcaabaaaabaaaaaaogbkbaaaabaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaaaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaaefaaaaajpcaabaaa
abaaaaaaegaabaaaabaaaaaaeghobaaaaeaaaaaaaagabaaaaaaaaaaabpaaaead
bkaabaaaaaaaaaaadbaaaaahccaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaa
abaaaaaadjaaaaakdcaabaaaabaaaaaajgafbaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaabaaaaaadmaaaaahccaabaaaaaaaaaaabkaabaaaabaaaaaabkaabaaa
aaaaaaaadhaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaamnmmemdo
akaabaaaaaaaaaaabfaaaaabaaaaaaaiccaabaaaaaaaaaaackiacaaaaaaaaaaa
adaaaaaaabeaaaaaaknhcddoaaaaaaaiccaabaaaaaaaaaaadkaabaiaebaaaaaa
aaaaaaaabkaabaaaaaaaaaaadicaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaacaebdiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaackaabaaa
aaaaaaaacpaaaaafecaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaajkjjbjdpbjaaaaafecaabaaaaaaaaaaa
ckaabaaaaaaaaaaadcaaaaajecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
mnmmemdpabeaaaaamnmmemdodiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
bkaabaaaaaaaaaaadbaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
mnmmemdobpaaaeadckaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabeeaaaaafccaabaaa
aaaaaaaabkaabaaaaaaaaaaaaoaaaaakccaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpbkaabaaaaaaaaaaaaaaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaamnmmemdodcaaaaakbcaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaaabeaaaaajkjjjjdobkaabaaaaaaaaaaaefaaaaampcaabaaa
abaaaaaaaceaaaaaaaaaiadmaaaahadpaaaaaaaaaaaaaaaaeghobaaaafaaaaaa
aagabaaaafaaaaaadcaaaaajccaabaaaaaaaaaaaakbabaaaacaaaaaaabeaaaaa
aaaaaadpabeaaaaaaaaaaadpaaaaaaalhcaabaaaacaaaaaaegacbaiaebaaaaaa
abaaaaaaaceaaaaamnmmmmdnmnmmmmdnmnmmemdoaaaaaaaadiaaaaahhcaabaaa
adaaaaaafgafbaaaaaaaaaaaegacbaaaacaaaaaadbaaaaahecaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaaadpbpaaaeadckaabaaaaaaaaaaadiaaaaah
ecaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaamaeaeaaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
abeaaaaaklkkkkdodcaaaaajhccabaaaaaaaaaaakgakbaaaaaaaaaaaegacbaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadp
doaaaaabbfaaaaabdcaaaaajocaabaaaaaaaaaaafgafbaaaaaaaaaaaagajbaaa
acaaaaaaagajbaaaabaaaaaaaaaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaaalpdiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaa
acaaaaaaeeaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaaoaaaaakbcaabaaa
aaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpakaabaaaaaaaaaaa
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaamaeaeaaaaaaf
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaiadoaaaaaaalhcaabaaaabaaaaaajgahbaiaebaaaaaa
aaaaaaaaaceaaaaamnmmemdnmnmmemdnmnmmmmdnaaaaaaaadcaaaaajhccabaaa
aaaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaajgahbaaaaaaaaaaadgaaaaaf
iccabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab"
}




}
 }
}
}