// Compiled shader for all platforms, uncompressed size: 71.9KB

Shader "Futile/Decal" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 226 math, 11 texture, 16 branch
 //       gles3 : 226 math, 11 texture, 16 branch
 //   glesdesktop : 226 math, 11 texture, 16 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 133 math, 11 texture, 9 branch
 //        d3d9 : 245 math, 11 texture, 6 branch
 //       metal : 226 math, 11 texture, 16 branch
 //      opengl : 238 math, 11 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 112
Vector 96 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedpenjlbbpmejpnecgfecobllklbmkepmkabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaahaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaagaaaaaa
ogikcaaaaaaaaaaaagaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 133 math, 11 textures, 9 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_NoiseTex] 2D 2
SetTexture 2 [_LevelTex] 2D 4
SetTexture 3 [_GrabTexture] 2D 0
SetTexture 4 [_PalTex] 2D 5
SetTexture 5 [_NoiseTex2] 2D 3
ConstBuffer "$Globals" 112
Float 20 [_RAIN]
Float 24 [_light]
Vector 32 [_spriteRect]
Vector 48 [_lightDirAndPixelSize]
Float 64 [_fogAmount]
Float 68 [_waterLevel]
Float 80 [_WetTerrain]
Float 84 [_cloudsSpeed]
Vector 88 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedbobknagogbjhkjlghpmmdnljlkmfdnllabaaaaaaaebhaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcbabgaaaaeaaaaaaaieafaaaafjaaaaae
egiocaaaaaaaaaaaagaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafkaaaaad
aagabaaaaeaaaaaafkaaaaadaagabaaaafaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaa
ffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaafibiaaaeaahabaaaaeaaaaaa
ffffaaaafibiaaaeaahabaaaafaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaa
gcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacajaaaaaadiaaaaaidcaabaaaaaaaaaaaogbkbaaaabaaaaaa
ogikcaaaaaaaaaaaafaaaaaaebaaaaafdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
aoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaogikcaaaaaaaaaaaafaaaaaa
aaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaaaaaaaaaa
acaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaiaebaaaaaaaaaaaaaaacaaaaaa
kgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
ogakbaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaegaabaaaaaaaaaaaeghobaaa
aaaaaaaaaagabaaaabaaaaaadiaaaaahicaabaaaaaaaaaaaakaabaaaabaaaaaa
abeaaaaafgffdfeabnaaaaaibcaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaia
ebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaadkaabaiaibaaaaaaaaaaaaaa
dhaaaaakicaabaaaaaaaaaaaakaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaia
ebaaaaaaaaaaaaaadcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaaleecabeaaaaaaaaaialpdiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaijiiaidnbnaaaaaibcaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaia
ebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaadkaabaiaibaaaaaaaaaaaaaa
dhaaaaakicaabaaaaaaaaaaaakaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaia
ebaaaaaaaaaaaaaadiaaaaakdcaabaaaabaaaaaaegaabaaaaaaaaaaaaceaaaaa
aaaamadpaaaaiadoaaaaaaaaaaaaaaaadcaaaaandcaabaaaabaaaaaapgapbaia
ebaaaaaaaaaaaaaaaceaaaaamnmmmmdnmnmmmmdnaaaaaaaaaaaaaaaaegaabaaa
abaaaaaadiaaaaaiicaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaa
mnmmmmdndcaaaaandcaabaaaabaaaaaafgifcaaaaaaaaaaaabaaaaaaaceaaaaa
aknhcddmmnmmemdnaaaaaaaaaaaaaaaaegaabaaaabaaaaaaefaaaaajpcaabaaa
abaaaaaaegaabaaaabaaaaaaeghobaaaabaaaaaaaagabaaaacaaaaaaaaaaaaah
bcaabaaaabaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaaaaaaaaahbcaabaaa
abaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaadcaaaaakbcaabaaaabaaaaaa
bkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmmmdnakaabaaaabaaaaaadiaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaafclibgebenaaaaagbcaabaaa
abaaaaaaaanaaaaaakaabaaaabaaaaaaaaaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaddddhdlpdicaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaaaaaakaebdbaaaaaiccaabaaaabaaaaaaakiacaaaaaaaaaaaafaaaaaa
abeaaaaaaaaaaadpaaaaaaaiecaabaaaabaaaaaadkbabaiaebaaaaaaabaaaaaa
abeaaaaaaaaaiadpdbaaaaaiicaabaaaabaaaaaabkiacaaaaaaaaaaaaeaaaaaa
ckaabaaaabaaaaaadmaaaaahccaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaa
abaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaagpbciddk
dhaaaaajbcaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaaaaakaabaaa
abaaaaaaaaaaaaahecaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaa
efaaaaajpcaabaaaacaaaaaaigaabaaaaaaaaaaaeghobaaaacaaaaaaaagabaaa
aeaaaaaabiaaaaaklcaabaaaabaaaaaaegaibaaaacaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaaaaaaaaaiadpabaaaaahecaabaaaaaaaaaaabkaabaaaabaaaaaa
akaabaaaabaaaaaaabaaaaahecaabaaaaaaaaaaadkaabaaaabaaaaaackaabaaa
aaaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaacaaaaaaabeaaaaaaaaahped
blaaaaafbcaabaaaacaaaaaaakaabaaaabaaaaaadiaaaaaiccaabaaaabaaaaaa
dkaabaaaaaaaaaaabkiacaaaaaaaaaaaafaaaaaadcaaaaajccaabaaaabaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaaadpbkaabaaaabaaaaaaedaaaaafbcaabaaa
abaaaaaaakaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaaijiiaidnbnaaaaaiicaabaaaabaaaaaaakaabaaaabaaaaaaakaabaia
ebaaaaaaabaaaaaabkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaa
dhaaaaakbcaabaaaabaaaaaadkaabaaaabaaaaaaakaabaaaabaaaaaaakaabaia
ebaaaaaaabaaaaaadcaaaaakbcaabaaaadaaaaaaakaabaiaebaaaaaaabaaaaaa
abeaaaaaomfblidnbkaabaaaabaaaaaadcaaaaakccaabaaaabaaaaaabkaabaia
ebaaaaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaiadpdiaaaaajicaabaaa
abaaaaaabkiacaaaaaaaaaaaabaaaaaabkiacaaaaaaaaaaaafaaaaaadcaaaaaj
ccaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaamnmmemdobkaabaaaabaaaaaa
dcaaaaakccaabaaaadaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaaomfblidn
bkaabaaaabaaaaaaefaaaaajpcaabaaaadaaaaaaegaabaaaadaaaaaaeghobaaa
abaaaaaaaagabaaaacaaaaaadcaaaaakicaabaaaaaaaaaaadkaabaaaaaaaaaaa
bkiacaaaaaaaaaaaafaaaaaaakaabaaaadaaaaaaaaaaaaaiicaabaaaaaaaaaaa
bkaabaiaebaaaaaaaaaaaaaadkaabaaaaaaaaaaabnaaaaaibcaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaa
dkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaaakaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaamdpfmieaenaaaaagicaabaaaaaaaaaaaaanaaaaa
dkaabaaaaaaaaaaadcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaaeaeaabeaaaaaaaaaaadpdccaaaalccaabaaaabaaaaaackiacaiaebaaaaaa
aaaaaaaaabaaaaaaabeaaaaaaaaaiaeadkaabaaaaaaaaaaaccaaaaahicaabaaa
aaaaaaaaabeaaaaafkaaaaaaakaabaaaacaaaaaaboaaaaahbcaabaaaabaaaaaa
akaabaaaacaaaaaaabeaaaaakgppppppdgaaaaafccaabaaaacaaaaaaabeaaaaa
aaaaiadpdhaaaaajdcaabaaaabaaaaaapgapbaaaaaaaaaaabgafbaaaabaaaaaa
bgafbaaaacaaaaaaboaaaaahicaabaaaaaaaaaaabkaabaaaabaaaaaaabeaaaaa
ppppppppclaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnebaaaaafccaabaaaabaaaaaa
dkaabaaaaaaaaaaadeaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaa
aaaaaaaaddaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaaea
blaaaaaficaabaaaabaaaaaabkaabaaaabaaaaaabnaaaaaibcaabaaaacaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaa
dkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaaakaabaaaacaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaapaebblaaaaafbcaabaaaacaaaaaadkaabaaa
aaaaaaaaedaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaakfcaabaaa
adaaaaaapgapbaaaaaaaaaaaaceaaaaaaaaaaadnaaaaaaaaaknhcddmaaaaaaaa
diaaaaakgcaabaaaacaaaaaakgilcaaaaaaaaaaaadaaaaaaagibcaiaebaaaaaa
aaaaaaaaadaaaaaaboaaaaahicaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaa
plppppppclaaaaaficaabaaaacaaaaaadkaabaaaacaaaaaadcaaaaajbcaabaaa
aeaaaaaabkaabaaaacaaaaaadkaabaaaacaaaaaackbabaaaabaaaaaadcaaaaaj
ccaabaaaaeaaaaaackaabaaaacaaaaaadkaabaaaacaaaaaackaabaaaabaaaaaa
aaaaaaakgcaabaaaacaaaaaaagabbaaaaeaaaaaaaceaaaaaaaaaaaaaaaaaaalp
jkjjjjloaaaaaaaaaaaaaaahecaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaakamadcaaaaajecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaadfhiaodl
abeaaaaaaaaaiadpdcaaaaamgcaabaaaacaaaaaafgagbaaaacaaaaaakgakbaaa
abaaaaaaaceaaaaaaaaaaaaaaaaaaadpjkjjjjdoaaaaaaaaefaaaaajpcaabaaa
aeaaaaaajgafbaaaacaaaaaaeghobaaaadaaaaaaaagabaaaaaaaaaaaboaaaaah
ecaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaadaaaaaaclaaaaafecaabaaa
abaaaaaackaabaaaabaaaaaaaaaaaaakgcaabaaaabaaaaaafgagbaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaadpaaaaaadpaaaaaaaadiaaaaakkcaabaaaadaaaaaa
fgajbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaadoaaaaaaaaaaaaaadoefaaaaaj
pcaabaaaafaaaaaamgaabaaaadaaaaaaeghobaaaaeaaaaaaaagabaaaafaaaaaa
efaaaaajpcaabaaaagaaaaaaegaabaaaadaaaaaaeghobaaaaeaaaaaaaagabaaa
afaaaaaadcaaaaapgcaabaaaabaaaaaakgblbaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaialpaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaaaaa
efaaaaajpcaabaaaahaaaaaajgafbaaaabaaaaaaeghobaaaadaaaaaaaagabaaa
aaaaaaaaaaaaaaakgcaabaaaabaaaaaaagbbbaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaaalpaaaaaalpaaaaaaaadcaaaaajccaabaaaacaaaaaadkaabaaaaaaaaaaa
abeaaaaaijiiiidmabeaaaaaaaaaiadpdcaaaaamdcaabaaaaiaaaaaajgafbaaa
abaaaaaafgafbaaaacaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaaaaaaaaaaaa
diaaaaahccaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaacpeeebaaaaaf
ccaabaaaabaaaaaabkaabaaaabaaaaaadiaaaaahecaabaaaabaaaaaabkaabaaa
abaaaaaaabeaaaaaohdolldkdcaaaaakbcaabaaaaaaaaaaabkaabaiaebaaaaaa
abaaaaaaabeaaaaaohdolldkakaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaaadpckaabaaaabaaaaaadiaaaaahbcaabaaa
adaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiaeadcaaaaajccaabaaaadaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaknhcddmckaabaaaadaaaaaaefaaaaajpcaabaaa
adaaaaaaegaabaaaadaaaaaaeghobaaaafaaaaaaaagabaaaadaaaaaaaaaaaaah
bcaabaaaaaaaaaaaakaabaaaadaaaaaaabeaaaaaaaaaaalpdeaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaaaaaaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaaaaaaaaaaaaaaaaiccaabaaaaaaaaaaackbabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaeaeacpaaaaafbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaa
bjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaackbabaaaacaaaaaadcaaaaajecaabaaaaiaaaaaaakaabaaa
aaaaaaaaabeaaaaajkjjjjdobkaabaaaaiaaaaaaefaaaaajpcaabaaaadaaaaaa
igaabaaaaiaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaabpaaaeadckaabaaa
aaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadoaaaaabbcaaaaabdiaaaaahbcaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaijiiaidndbaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaaakbabaaa
acaaaaaadbaaaaahbcaabaaaaaaaaaaabkbabaaaacaaaaaaakaabaaaaaaaaaaa
dmaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaabpaaaead
akaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadoaaaaabbfaaaaabdjaaaaahbcaabaaaaaaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaaiadpcbaaaaahccaabaaaaaaaaaaaakaabaaaacaaaaaa
abeaaaaaafaaaaaaabaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaa
aaaaaaaabpaaaeadakaabaaaaaaaaaaadjaaaaakhcaabaaaacaaaaaaegacbaaa
aeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahbcaabaaa
aaaaaaaabkaabaaaacaaaaaaakaabaaaacaaaaaadmaaaaahbcaabaaaaaaaaaaa
ckaabaaaacaaaaaaakaabaaaaaaaaaaadhaaaaajbcaabaaaabaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaiadpakaabaaaabaaaaaabfaaaaabbpaaaeadbkaabaaa
aaaaaaaadbaaaaahbcaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaaahaaaaaa
djaaaaakgcaabaaaaaaaaaaafgagbaaaahaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadmaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaa
aaaaaaaadmaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaa
bpaaaeadakaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabbfaaaaabaaaaaaaihcaabaaa
aaaaaaaaegacbaiaebaaaaaaafaaaaaaegacbaaaagaaaaaadcaaaaajhcaabaaa
aaaaaaaaagaabaaaabaaaaaaegacbaaaaaaaaaaaegacbaaaafaaaaaaefaaaaam
pcaabaaaacaaaaaaaceaaaaaaaaaeadnaaaahadpaaaaaaaaaaaaaaaaeghobaaa
aeaaaaaaaagabaaaafaaaaaadiaaaaaiicaabaaaaaaaaaaadkaabaaaaaaaaaaa
akiacaaaaaaaaaaaaeaaaaaadicaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaijiiaidnaaaaaaaihcaabaaaacaaaaaaegacbaiaebaaaaaaaaaaaaaa
egacbaaaacaaaaaadcaaaaajhcaabaaaaaaaaaaapgapbaaaaaaaaaaaegacbaaa
acaaaaaaegacbaaaaaaaaaaaaaaaaaaihcaabaaaacaaaaaaegacbaiaebaaaaaa
aaaaaaaaegacbaaaadaaaaaadcaaaaamhcaabaaaacaaaaaaegacbaaaacaaaaaa
aceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaaaaegacbaaaaaaaaaaaaaaaaaal
hcaabaaaaeaaaaaaegacbaiaebaaaaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadp
aaaaiadpaaaaaaaaaaaaaaalhcaabaaaafaaaaaaegacbaiaebaaaaaaadaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadcaaaaanhcaabaaaaeaaaaaa
egacbaiaebaaaaaaaeaaaaaaegacbaaaafaaaaaaaceaaaaaaaaaiadpaaaaiadp
aaaaiadpaaaaaaaaaaaaaaaiicaabaaaaaaaaaaaakaabaiaebaaaaaaabaaaaaa
abeaaaaaaaaaiadpcaaaaaahccaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
acaaaaaadhaaaaajccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaggggggdp
abeaaaaaaaaaiadodiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaa
abaaaaaaaaaaaaaiocaabaaaabaaaaaaagajbaiaebaaaaaaacaaaaaaagajbaaa
aeaaaaaadcaaaaajocaabaaaabaaaaaapgapbaaaaaaaaaaafgaobaaaabaaaaaa
agajbaaaacaaaaaadcaaaaajicaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaa
mommmmdnabeaaaaamnmmemdodcaaaaakhcaabaaaaaaaaaaaegacbaaaaaaaaaaa
egacbaaaadaaaaaajgahbaiaebaaaaaaabaaaaaadcaaaaajhccabaaaaaaaaaaa
pgapbaaaaaaaaaaaegacbaaaaaaaaaaajgahbaaaabaaaaaadcaaaaajbcaabaaa
aaaaaaaadkbabaaaacaaaaaaabeaaaaaaaaaiadoabeaaaaaaaaaealpdcaaaaaj
bcaabaaaaaaaaaaaakaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadp
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaadaaaaaadiaaaaah
iccabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaaacaaaaaadoaaaaabbfaaaaab
doaaaaab"
}




}
 }
}
}