// Compiled shader for all platforms, uncompressed size: 60.3KB

Shader "Futile/LightSource" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 170 math, 7 texture, 21 branch
 //       gles3 : 170 math, 7 texture, 21 branch
 //   glesdesktop : 170 math, 7 texture, 21 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 125 math, 7 texture, 5 branch
 //        d3d9 : 260 math, 7 texture, 4 branch
 //       metal : 170 math, 7 texture, 21 branch
 //      opengl : 232 math, 7 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 125 math, 7 textures, 5 branches
SetTexture 0 [_LevelTex] 2D 2
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_MainTex] 2D 1
ConstBuffer "$Globals" 80
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecednfmfielcalghhmjkcgkbblppogcjoofiabaaaaaafabeaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcfmbdaaaaeaaaaaaanhaeaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaiaaaaaadiaaaaaidcaabaaa
aaaaaaaaogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaadaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaa
egaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadiaaaaahecaabaaa
aaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaahpeddcaaaaajicaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaagicaabaaaaaaaaaaa
dkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaadkaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabiaaaaakncaabaaaabaaaaaa
agajbaaaabaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaiadpaaaaiadpabaaaaah
bcaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaahbcaabaaa
abaaaaaadkaabaaaabaaaaaaakaabaaaabaaaaaadhaaaaajicaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaaiadpdkaabaaaaaaaaaaaaaaaaaakfcaabaaa
abaaaaaaagbbbaaaabaaaaaaaceaaaaaaaaaaalpaaaaaaaaaaaaaalpaaaaaaaa
apaaaaahicaabaaaabaaaaaaigaabaaaabaaaaaaigaabaaaabaaaaaaeeaaaaaf
bcaabaaaacaaaaaadkaabaaaabaaaaaadiaaaaahfcaabaaaabaaaaaaagacbaaa
abaaaaaaagaabaaaacaaaaaaelaaaaaficaabaaaabaaaaaadkaabaaaabaaaaaa
ddaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaadpcpaaaaaf
bcaabaaaacaaaaaadkaabaaaabaaaaaadiaaaaahbcaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaaaaakadpbjaaaaafbcaabaaaacaaaaaaakaabaaaacaaaaaa
diaaaaahdcaabaaaacaaaaaaigaabaaaabaaaaaaagaabaaaacaaaaaadiaaaaah
ecaabaaaacaaaaaadkaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaahmcaabaaa
acaaaaaakgakbaaaacaaaaaaagaebaaaacaaaaaadcaaaaanmcaabaaaacaaaaaa
kgaobaiaebaaaaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaajkjjjjdojkjjjjdo
agaebaaaaaaaaaaadiaaaaakdcaabaaaadaaaaaaigaabaaaabaaaaaaaceaaaaa
kgjleedlkgjleedlaaaaaaaaaaaaaaaaaaaaaaahecaabaaaadaaaaaadkaabaaa
abaaaaaadkaabaaaabaaaaaacpaaaaaficaabaaaadaaaaaackaabaaaadaaaaaa
diaaaaahbcaabaaaaeaaaaaadkaabaaaadaaaaaaabeaaaaaaaaaiadobjaaaaaf
bcaabaaaaeaaaaaaakaabaaaaeaaaaaadcaaaaakdcaabaaaadaaaaaaegaabaia
ebaaaaaaadaaaaaaagaabaaaaeaaaaaaegaabaaaaaaaaaaacpaaaaafbcaabaaa
aeaaaaaadkaabaaaaaaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaaaaaamadpbjaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaadiaaaaah
dcaabaaaacaaaaaaegaabaaaacaaaaaaagaabaaaaeaaaaaadcaaaaandcaabaaa
aeaaaaaaegaabaiaebaaaaaaacaaaaaaaceaaaaajkjjjjdojkjjjjdoaaaaaaaa
aaaaaaaaogbkbaaaabaaaaaaefaaaaajpcaabaaaacaaaaaaogakbaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaacaaaaaaefaaaaajpcaabaaaafaaaaaaegaabaaa
adaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadbaaaaahicaabaaaacaaaaaa
abeaaaaaklkkckdodkaabaaaaaaaaaaadcaaaaapdcaabaaaadaaaaaaogbkbaaa
abaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaaaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaaaaaaaaaaaaaefaaaaajpcaabaaaagaaaaaaegaabaaaadaaaaaa
eghobaaaabaaaaaaaagabaaaaaaaaaaaaaaaaaaiecaabaaaaeaaaaaabkaabaia
ebaaaaaaaeaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaaeaaaaaaigaabaaa
aeaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaadiaaaaahfcaabaaaabaaaaaa
pgapbaaaabaaaaaaagacbaaaabaaaaaadcaaaaandcaabaaaaaaaaaaaigaabaia
ebaaaaaaabaaaaaaaceaaaaaaknhcddmaknhcddmaaaaaaaaaaaaaaaaegaabaaa
aaaaaaaaefaaaaajpcaabaaaahaaaaaaegaabaaaaaaaaaaaeghobaaaaaaaaaaa
aagabaaaacaaaaaabpaaaeaddkaabaaaacaaaaaadbaaaaahbcaabaaaaaaaaaaa
abeaaaaaibiaiadlakaabaaaagaaaaaadjaaaaakfcaabaaaabaaaaaafgagbaaa
agaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaadmaaaaahbcaabaaaaaaaaaaa
ckaabaaaabaaaaaaakaabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadgaaaaai
pccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaab
bfaaaaabbfaaaaabblaaaaafbcaabaaaaaaaaaaackaabaaaaaaaaaaaabaaaaah
ccaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaiaceaaaaaibcaabaaa
aaaaaaaaakaabaaaaaaaaaaaakaabaiaebaaaaaaaaaaaaaaeoaaaaaiaanaaaaa
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaafkaaaaaaciaaaaafecaabaaa
aaaaaaaaakaabaaaaaaaaaaadhaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaaaaaaaaaclaaaaafbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaijiiaidn
ebaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaablaaaaafbcaabaaaaaaaaaaa
akaabaaaaaaaaaaabnaaaaahccaabaaaaaaaaaaabkaabaaaabaaaaaaabeaaaaa
ibiaiadndhaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaadaaaaaa
akaabaaaaaaaaaaadcaaaaajecaabaaaaaaaaaaaakaabaaaacaaaaaaabeaaaaa
aaaahpedabeaaaaaaaaaialpdiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
abeaaaaaijiiaidnbnaaaaaibcaabaaaabaaaaaackaabaaaaaaaaaaackaabaia
ebaaaaaaaaaaaaaabkaaaaagecaabaaaaaaaaaaackaabaiaibaaaaaaaaaaaaaa
dhaaaaakecaabaaaaaaaaaaaakaabaaaabaaaaaackaabaaaaaaaaaaackaabaia
ebaaaaaaaaaaaaaabiaaaaakhcaabaaaabaaaaaaegacbaaaacaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaabaaaaaabkaabaaa
abaaaaaaakaabaaaabaaaaaaabaaaaahbcaabaaaabaaaaaackaabaaaabaaaaaa
akaabaaaabaaaaaadhaaaaajecaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaa
aaaaiadpckaabaaaaaaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaafaaaaaa
abeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaijiiaidnbnaaaaaiccaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaiaebaaaaaaabaaaaaabkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaa
abaaaaaadhaaaaakbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaiaebaaaaaaabaaaaaabiaaaaakhcaabaaaacaaaaaaegacbaaaafaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahccaabaaaabaaaaaa
bkaabaaaacaaaaaaakaabaaaacaaaaaaabaaaaahccaabaaaabaaaaaackaabaaa
acaaaaaabkaabaaaabaaaaaadhaaaaajbcaabaaaabaaaaaabkaabaaaabaaaaaa
abeaaaaaaaaaiadpakaabaaaabaaaaaadbaaaaahccaabaaaabaaaaaaabeaaaaa
klkkckdockaabaaaaaaaaaaabpaaaeadbkaabaaaabaaaaaadbaaaaahccaabaaa
abaaaaaaabeaaaaaibiaiadlakaabaaaaeaaaaaadjaaaaakdcaabaaaacaaaaaa
jgafbaaaaeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaah
ccaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaacaaaaaadmaaaaahccaabaaa
abaaaaaabkaabaaaacaaaaaabkaabaaaabaaaaaadhaaaaajecaabaaaaaaaaaaa
bkaabaaaabaaaaaaabeaaaaamnmmemdockaabaaaaaaaaaaabfaaaaabaaaaaaai
ecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaadkaabaaaaaaaaaaacaaaaaak
gcaabaaaabaaaaaaagaabaaaaaaaaaaaaceaaaaaaaaaaaaaabaaaaaaacaaaaaa
aaaaaaaadhaaaaajccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaaia
abeaaaaaijiiiilnaacaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaa
abaaaaaaaaaaaaaiccaabaaaabaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaa
aaaaiadpaaaaaaaibcaabaaaacaaaaaabkaabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaaadpdcaaaaajccaabaaaabaaaaaaakaabaaaacaaaaaaabeaaaaaaaaaaadp
bkaabaaaabaaaaaacpaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaabaaaaaabjaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaaaaaaaaakdcaabaaaacaaaaaapgapbaaaaaaaaaaa
aceaaaaamnmmemdnmnmmemloaaaaaaaaaaaaaaaadbaaaaahbcaabaaaabaaaaaa
akaabaaaacaaaaaaakaabaaaabaaaaaadiaaaaahccaabaaaabaaaaaadkaabaaa
abaaaaaaabeaaaaamdpfmieaenaaaaagccaabaaaabaaaaaaaanaaaaabkaabaaa
abaaaaaaabaaaaahecaabaaaaeaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
bpaaaaadakaabaaaaaaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaahaaaaaa
abeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaijiiaidnbnaaaaaiccaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaiaebaaaaaaabaaaaaabkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaa
abaaaaaadhaaaaakbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaiaebaaaaaaabaaaaaadbaaaaahccaabaaaabaaaaaaakaabaaaabaaaaaa
dkaabaaaaaaaaaaaaaaaaaahbcaabaaaacaaaaaadkaabaaaaaaaaaaaabeaaaaa
mnmmmmlndbaaaaahbcaabaaaabaaaaaaakaabaaaacaaaaaaakaabaaaabaaaaaa
abaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaabkaabaaaabaaaaaadcaaaaak
ccaabaaaabaaaaaadkaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiaeaabeaaaaa
aaaacaeadiaaaaahccaabaaaabaaaaaadkaabaaaadaaaaaabkaabaaaabaaaaaa
bjaaaaafccaabaaaabaaaaaabkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaa
ckaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdcaaaaajccaabaaaabaaaaaa
bkaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaaaaaaaaadhaaaaajecaabaaa
aaaaaaaaakaabaaaabaaaaaabkaabaaaabaaaaaackaabaaaaaaaaaaabfaaaaab
dbaaaaahbcaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaamnmmemdodcaaaaak
ccaabaaaabaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaakaeaabeaaaaa
aaaaiadpcpaaaaafccaabaaaabaaaaaabkaabaaaabaaaaaadiaaaaahccaabaaa
abaaaaaabkaabaaaabaaaaaaabeaaaaaddddlddobjaaaaafccaabaaaabaaaaaa
bkaabaaaabaaaaaadicaaaahicaabaaaabaaaaaabkaabaaaacaaaaaaabeaaaaa
ggggkgdpdhaaaaajbcaabaaaabaaaaaaakaabaaaabaaaaaabkaabaaaabaaaaaa
dkaabaaaabaaaaaaaaaaaaaibcaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
abeaaaaaaaaaiadpdcaaaaakccaabaaaabaaaaaackaabaiaebaaaaaaadaaaaaa
ckaabaaaadaaaaaaabeaaaaaaaaaiadpcpaaaaafccaabaaaabaaaaaabkaabaaa
abaaaaaadiaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaagaea
dcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaeaeaabeaaaaa
aaaaaadpdiaaaaahicaabaaaaaaaaaaabkaabaaaabaaaaaadkaabaaaaaaaaaaa
bjaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaakaabaaaabaaaaaadcaaaaakicaabaaaaaaaaaaackaabaaa
aaaaaaaadkaabaiaebaaaaaaaaaaaaaadkaabaaaaaaaaaaadccaaaakccaabaaa
aeaaaaaackaabaiaebaaaaaaaaaaaaaaabeaaaaajkjjjjdodkaabaaaaaaaaaaa
cpaaaaafecaabaaaaaaaaaaabkaabaaaaeaaaaaadiaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaabeaaaaamnmmemdpbjaaaaafbcaabaaaaeaaaaaackaabaaa
aaaaaaaadiaaaaahccaabaaaacaaaaaabkaabaaaaeaaaaaaabeaaaaamnmmemdo
dgaaaaafecaabaaaacaaaaaaabeaaaaaaaaaaaaadhaaaaajgcaabaaaaaaaaaaa
fgafbaaaaaaaaaaafgagbaaaacaaaaaafgagbaaaaeaaaaaadhaaaaajgcaabaaa
aaaaaaaakgakbaaaabaaaaaaagacbaaaaeaaaaaafgagbaaaaaaaaaaadiaaaaah
icaabaaaaeaaaaaabkaabaaaaeaaaaaaabeaaaaamnmmemdpdhaaaaajdcaabaaa
aaaaaaaaagaabaaaaaaaaaaajgafbaaaaaaaaaaalgapbaaaaeaaaaaaefaaaaaj
pcaabaaaabaaaaaaegbabaaaabaaaaaaeghobaaaacaaaaaaaagabaaaabaaaaaa
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaaacaaaaaadcaaaaajccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaddddlddoabeaaaaaggggcgdpdiaaaaah
iccabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadgaaaaafhccabaaa
aaaaaaaaegbcbaaaacaaaaaadoaaaaab"
}




}
 }
}
}