// Compiled shader for all platforms, uncompressed size: 50.2KB

Shader "Futile/LightAndSkyBloom" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 148 math, 11 texture, 13 branch
 //       gles3 : 148 math, 11 texture, 13 branch
 //   glesdesktop : 148 math, 11 texture, 13 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 80 math, 10 texture, 1 branch
 //        d3d9 : 183 math, 11 texture, 5 branch
 //       metal : 148 math, 11 texture, 13 branch
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {
// Platform opengl had shader errors
//   <no keywords>

SubProgram "d3d11 " {
// Stats: 80 math, 10 textures, 1 branches
SetTexture 0 [_PalTex] 2D 2
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_LevelTex] 2D 1
ConstBuffer "$Globals" 80
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedebbgjoepodehajgjafgmkanohbdghkddabaaaaaacmbaaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcdiapaaaaeaaaaaaamoadaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaadmcbabaaaabaaaaaagcbaaaadicbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacaoaaaaaaaaaaaaajdcaabaaaaaaaaaaaogbkbaaaabaaaaaa
egiacaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaaaaaaaaiecaabaaaaaaaaaaa
dkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadpdcaaaaapdcaabaaaabaaaaaa
ogbkbaaaabaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaaaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaaaalmcaabaaaabaaaaaaagaebaia
ebaaaaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaamnmmemdomnmmemdoapaaaaah
icaabaaaaaaaaaaaogakbaaaabaaaaaaogakbaaaabaaaaaaelaaaaaficaabaaa
aaaaaaaadkaabaaaaaaaaaaaaaaaaaaiicaabaaaaaaaaaaadkaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpdeaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaaaaaaaaaeeaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaaoaaaaak
icaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpdkaabaaa
aaaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaadkbabaaaacaaaaaa
aoaaaaajecaabaaaabaaaaaabkiacaaaaaaaaaaaadaaaaaaakiacaaaaaaaaaaa
adaaaaaaefaaaaampcaabaaaacaaaaaaaceaaaaaaaaaaaaaaaaaoaeaaaaaaaaa
aaaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaaefaaaaajpcaabaaaadaaaaaa
egaabaaaabaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaadgaaaaailcaabaaa
abaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaaipcaabaaa
aeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaiadpdgaaaaaficaabaaa
acaaaaaaabeaaaaaaaaaiadpdgaaaaaiocaabaaaafaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaiadpaaaaaaaadgaaaaafbcaabaaaagaaaaaaabeaaaaaaaaaaaaa
daaaaaabcbaaaaahccaabaaaagaaaaaaakaabaaaagaaaaaaabeaaaaaagaaaaaa
adaaaeadbkaabaaaagaaaaaaaaaaaaahicaabaaaafaaaaaadkaabaaaafaaaaaa
abeaaaaaaaaaiadpdiaaaaahccaabaaaagaaaaaadkaabaaaacaaaaaaabeaaaaa
fclibodpdiaaaaahecaabaaaagaaaaaadkaabaaaafaaaaaaabeaaaaapkonoldk
dcaaaaakccaabaaaahaaaaaackaabaiaebaaaaaaagaaaaaackaabaaaabaaaaaa
ckbabaaaabaaaaaadcaaaaakecaabaaaahaaaaaadkaabaiaebaaaaaaafaaaaaa
abeaaaaapkonoldkckaabaaaaaaaaaaaefaaaaajpcaabaaaaiaaaaaajgafbaaa
ahaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabiaaaaahhcaabaaaajaaaaaa
egacbaaaacaaaaaaegacbaaaaiaaaaaaabaaaaahicaabaaaagaaaaaabkaabaaa
ajaaaaaaakaabaaaajaaaaaaabaaaaahicaabaaaagaaaaaackaabaaaajaaaaaa
dkaabaaaagaaaaaadcaaaaajpcaabaaaajaaaaaaegaobaaaaiaaaaaafgafbaaa
agaaaaaaegaobaaaaeaaaaaadcaaaaajccaabaaaakaaaaaadkaabaaaacaaaaaa
abeaaaaafclibodpbkaabaaaafaaaaaadhaaaaajhcaabaaaalaaaaaapgapbaaa
agaaaaaaegacbaaaajaaaaaaegacbaaaaeaaaaaadgaaaaafbcaabaaaakaaaaaa
dkaabaaaajaaaaaadgaaaaafbcaabaaaafaaaaaadkaabaaaaeaaaaaadhaaaaaj
dcaabaaaajaaaaaapgapbaaaagaaaaaaegaabaaaakaaaaaaegaabaaaafaaaaaa
dcaaaaakccaabaaaakaaaaaackaabaiaebaaaaaaagaaaaaackaabaaaabaaaaaa
akaabaaaaaaaaaaadcaaaaakecaabaaaakaaaaaadkaabaiaebaaaaaaafaaaaaa
abeaaaaapkonoldkbkaabaaaaaaaaaaaefaaaaajpcaabaaaamaaaaaajgafbaaa
akaaaaaaeghobaaaacaaaaaaaagabaaaabaaaaaadbaaaaahicaabaaaagaaaaaa
abeaaaaalfleledoakaabaaaamaaaaaadbaaaaahicaabaaaaiaaaaaaakaabaaa
amaaaaaaabeaaaaaaaaaiadpabaaaaahicaabaaaagaaaaaadkaabaaaagaaaaaa
dkaabaaaaiaaaaaadeaaaaahhcaabaaaaiaaaaaaegacbaaaadaaaaaaegacbaaa
aiaaaaaadcaaaaajhcaabaaaaiaaaaaaegacbaaaaiaaaaaakgakbaaaafaaaaaa
egadbaaaabaaaaaadhaaaaajhcaabaaaaiaaaaaapgapbaaaagaaaaaaegacbaaa
aiaaaaaaegadbaaaabaaaaaadcaaaaajbcaabaaaahaaaaaackaabaaaagaaaaaa
ckaabaaaabaaaaaackbabaaaabaaaaaaefaaaaajpcaabaaaamaaaaaaigaabaaa
ahaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabiaaaaahhcaabaaaanaaaaaa
egacbaaaacaaaaaaegacbaaaamaaaaaaabaaaaahicaabaaaagaaaaaabkaabaaa
anaaaaaaakaabaaaanaaaaaaabaaaaahicaabaaaagaaaaaackaabaaaanaaaaaa
dkaabaaaagaaaaaadgaaaaaficaabaaaalaaaaaaakaabaaaajaaaaaadcaaaaaj
pcaabaaaanaaaaaaegaobaaaamaaaaaafgafbaaaagaaaaaaegaobaaaalaaaaaa
dcaaaaajecaabaaaahaaaaaadkaabaaaacaaaaaaabeaaaaafclibodpbkaabaaa
ajaaaaaadhaaaaajpcaabaaaalaaaaaapgapbaaaagaaaaaaegaobaaaanaaaaaa
egaobaaaalaaaaaadhaaaaajicaabaaaagaaaaaadkaabaaaagaaaaaackaabaaa
ahaaaaaabkaabaaaajaaaaaadcaaaaajbcaabaaaakaaaaaackaabaaaagaaaaaa
ckaabaaaabaaaaaaakaabaaaaaaaaaaaefaaaaajpcaabaaaajaaaaaaigaabaaa
akaaaaaaeghobaaaacaaaaaaaagabaaaabaaaaaadbaaaaahecaabaaaagaaaaaa
abeaaaaalfleledoakaabaaaajaaaaaadbaaaaahecaabaaaahaaaaaaakaabaaa
ajaaaaaaabeaaaaaaaaaiadpabaaaaahecaabaaaagaaaaaackaabaaaagaaaaaa
ckaabaaaahaaaaaadeaaaaahhcaabaaaajaaaaaaegacbaaaadaaaaaaegacbaaa
amaaaaaadcaaaaajhcaabaaaajaaaaaaegacbaaaajaaaaaakgakbaaaafaaaaaa
egacbaaaaiaaaaaadhaaaaajhcaabaaaaiaaaaaakgakbaaaagaaaaaaegacbaaa
ajaaaaaaegacbaaaaiaaaaaadcaaaaajicaabaaaahaaaaaadkaabaaaafaaaaaa
abeaaaaapkonoldkckaabaaaaaaaaaaaefaaaaajpcaabaaaajaaaaaamgaabaaa
ahaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabiaaaaahhcaabaaaamaaaaaa
egacbaaaacaaaaaaegacbaaaajaaaaaaabaaaaahecaabaaaagaaaaaabkaabaaa
amaaaaaaakaabaaaamaaaaaaabaaaaahecaabaaaagaaaaaackaabaaaamaaaaaa
ckaabaaaagaaaaaadcaaaaajpcaabaaaamaaaaaaegaobaaaajaaaaaafgafbaaa
agaaaaaaegaobaaaalaaaaaadcaaaaajbcaabaaaahaaaaaadkaabaaaacaaaaaa
abeaaaaafclibodpdkaabaaaagaaaaaadhaaaaajpcaabaaaalaaaaaakgakbaaa
agaaaaaaegaobaaaamaaaaaaegaobaaaalaaaaaadhaaaaajccaabaaaamaaaaaa
ckaabaaaagaaaaaaakaabaaaahaaaaaadkaabaaaagaaaaaadcaaaaajicaabaaa
akaaaaaadkaabaaaafaaaaaaabeaaaaapkonoldkbkaabaaaaaaaaaaaefaaaaaj
pcaabaaaanaaaaaamgaabaaaakaaaaaaeghobaaaacaaaaaaaagabaaaabaaaaaa
dbaaaaahecaabaaaagaaaaaaabeaaaaalfleledoakaabaaaanaaaaaadbaaaaah
icaabaaaagaaaaaaakaabaaaanaaaaaaabeaaaaaaaaaiadpabaaaaahecaabaaa
agaaaaaadkaabaaaagaaaaaackaabaaaagaaaaaadeaaaaahhcaabaaaajaaaaaa
egacbaaaadaaaaaaegacbaaaajaaaaaadcaaaaajhcaabaaaajaaaaaaegacbaaa
ajaaaaaakgakbaaaafaaaaaaegacbaaaaiaaaaaadhaaaaajhcaabaaaaiaaaaaa
kgakbaaaagaaaaaaegacbaaaajaaaaaaegacbaaaaiaaaaaaefaaaaajpcaabaaa
ahaaaaaangafbaaaahaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabiaaaaah
hcaabaaaajaaaaaaegacbaaaacaaaaaaegacbaaaahaaaaaaabaaaaahecaabaaa
agaaaaaabkaabaaaajaaaaaaakaabaaaajaaaaaaabaaaaahecaabaaaagaaaaaa
ckaabaaaajaaaaaackaabaaaagaaaaaadcaaaaajpcaabaaaajaaaaaaegaobaaa
ahaaaaaafgafbaaaagaaaaaaegaobaaaalaaaaaadcaaaaajccaabaaaanaaaaaa
dkaabaaaacaaaaaaabeaaaaafclibodpbkaabaaaamaaaaaadhaaaaajhcaabaaa
aeaaaaaakgakbaaaagaaaaaaegacbaaaajaaaaaaegacbaaaalaaaaaadgaaaaaf
bcaabaaaanaaaaaadkaabaaaajaaaaaadgaaaaafbcaabaaaamaaaaaadkaabaaa
alaaaaaadhaaaaajdcaabaaaafaaaaaakgakbaaaagaaaaaaegaabaaaanaaaaaa
egaabaaaamaaaaaaefaaaaajpcaabaaaajaaaaaangafbaaaakaaaaaaeghobaaa
acaaaaaaaagabaaaabaaaaaadbaaaaahecaabaaaagaaaaaaabeaaaaalfleledo
akaabaaaajaaaaaadbaaaaahicaabaaaagaaaaaaakaabaaaajaaaaaaabeaaaaa
aaaaiadpabaaaaahecaabaaaagaaaaaadkaabaaaagaaaaaackaabaaaagaaaaaa
deaaaaahhcaabaaaahaaaaaaegacbaaaadaaaaaaegacbaaaahaaaaaadcaaaaaj
hcaabaaaahaaaaaaegacbaaaahaaaaaakgakbaaaafaaaaaaegacbaaaaiaaaaaa
dhaaaaajlcaabaaaabaaaaaakgakbaaaagaaaaaaegaibaaaahaaaaaaegaibaaa
aiaaaaaadiaaaaahecaabaaaafaaaaaackaabaaaafaaaaaaabeaaaaaggggggdp
boaaaaahbcaabaaaagaaaaaaakaabaaaagaaaaaaabeaaaaaabaaaaaadgaaaaaf
icaabaaaaeaaaaaaakaabaaaafaaaaaadgaaaaaficaabaaaacaaaaaabkaabaaa
agaaaaaabgaaaaabdcaaaaampcaabaaaacaaaaaaegaobaaaaeaaaaaaaceaaaaa
aaaaaadpaaaaaadpaaaaaadpaaaaaadpegaobaaaadaaaaaadiaaaaahbcaabaaa
aaaaaaaabkaabaaaafaaaaaaabeaaaaaaaaaeadpaaaaaaahhcaabaaaadaaaaaa
egacbaaaaeaaaaaaegacbaaaacaaaaaaaoaaaaahhcaabaaaaaaaaaaaegacbaaa
adaaaaaaagaabaaaaaaaaaaadeaaaaahhcaabaaaaaaaaaaaegacbaaaaaaaaaaa
egacbaaaacaaaaaadcaaaaajecaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaa
ddddldloabeaaaaadddddddpaaaaaaaihcaabaaaabaaaaaakgakbaiaebaaaaaa
abaaaaaaegadbaaaabaaaaaadeaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadiaaaaakhcaabaaaacaaaaaa
egacbaaaabaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaaaadbaaaaah
hcaabaaaacaaaaaaegacbaaaaaaaaaaaegacbaaaacaaaaaadcaaaaanhcaabaaa
abaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaaaa
egacbaiaebaaaaaaaaaaaaaadcaaaaajhcaabaaaabaaaaaapgapbaaaaaaaaaaa
egacbaaaabaaaaaaegacbaaaaaaaaaaadhaaaaajhccabaaaaaaaaaaaegacbaaa
acaaaaaaegacbaaaabaaaaaaegacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaa
dkaabaaaacaaaaaadoaaaaab"
}




}
 }
}
}