// Compiled shader for all platforms, uncompressed size: 27.0KB

Shader "Futile/ColoredSprite2" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 37 math, 5 texture, 4 branch
 //       gles3 : 37 math, 5 texture, 4 branch
 //   glesdesktop : 37 math, 5 texture, 4 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 34 math, 5 texture, 3 branch
 //        d3d9 : 66 math, 5 texture, 2 branch
 //       metal : 37 math, 5 texture, 4 branch
 //      opengl : 68 math, 5 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 34 math, 5 textures, 3 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_LevelTex] 2D 2
SetTexture 2 [_GrabTexture] 2D 0
SetTexture 3 [_PalTex] 2D 3
ConstBuffer "$Globals" 80
Float 16 [_fogAmount]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedfklihkclmlboboeggecnoccjbkglofokabaaaaaalaahaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefclmagaaaaeaaaaaaakpabaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaae
aahabaaaacaaaaaaffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaagcbaaaad
dcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacadaaaaaadiaaaaaidcaabaaaaaaaaaaa
ogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaaaaaaaaaa
egaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaa
aaaaaaaaadaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaia
ebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaiaebaaaaaa
aaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaaaaaaaaaa
egaabaaaaaaaaaaaogakbaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaegbabaaa
abaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaaaaaaaaaiecaabaaaaaaaaaaa
dkbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpaaaaaaaiicaabaaaaaaaaaaa
ckaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdcaaaaajecaabaaaaaaaaaaa
akaabaaaabaaaaaadkaabaaaaaaaaaaackaabaaaaaaaaaaaefaaaaajpcaabaaa
acaaaaaaegaabaaaaaaaaaaaeghobaaaabaaaaaaaagabaaaacaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaacaaaaaaabeaaaaaaaaahpedblaaaaafbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaaaiaceaaaaaibcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaaeoaaaaaiaanaaaaabcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaboaaaaaaciaaaaaficaabaaaaaaaaaaaakaabaaaaaaaaaaadhaaaaaj
bcaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaaaaaaaaa
claaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaijiiaidndbaaaaahbcaabaaaaaaaaaaaabeaaaaa
aaaamaeaakaabaaaaaaaaaaadcaaaaapdcaabaaaabaaaaaaogbkbaaaabaaaaaa
aceaaaaaaaaaiadpaaaaialpaaaaaaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaaaaaaaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaabaaaaaaeghobaaa
acaaaaaaaagabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadbaaaaahbcaabaaa
aaaaaaaaabeaaaaaibiaiadlakaabaaaacaaaaaadjaaaaakdcaabaaaabaaaaaa
jgafbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaadmaaaaahbcaabaaa
aaaaaaaabkaabaaaabaaaaaaakaabaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaamnmmemdobkaabaaaaaaaaaaabfaaaaabdbaaaaah
bcaabaaaaaaaaaaabkaabaaaaaaaaaaackaabaaaaaaaaaaadcaaaaajccaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaoiebabeaaaaaaaaaaadpdiaaaaah
bcaabaaaabaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadndcaaaaajccaabaaa
aaaaaaaackaabaaaabaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaaadpdiaaaaah
ccaabaaaabaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadoefaaaaajpcaabaaa
acaaaaaaegaabaaaabaaaaaaeghobaaaadaaaaaaaagabaaaadaaaaaabpaaaead
akaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadoaaaaabbfaaaaabdbaaaaaklcaabaaaaaaaaaaaegbibaaa
acaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaiadpdmaaaaahbcaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaahbcaabaaaaaaaaaaa
dkaabaaaaaaaaaaaakaabaaaaaaaaaaaaaaaaaaihcaabaaaabaaaaaaegacbaia
ebaaaaaaacaaaaaaegbcbaaaacaaaaaadcaaaaamhcaabaaaabaaaaaaegacbaaa
abaaaaaaaceaaaaaaaaaiadoaaaaiadoaaaaiadoaaaaaaaaegacbaaaacaaaaaa
dhaaaaajlcaabaaaaaaaaaaaagaabaaaaaaaaaaaegaibaaaabaaaaaaegaibaaa
acaaaaaaefaaaaampcaabaaaacaaaaaaaceaaaaaaaaaeadnaaaahadpaaaaaaaa
aaaaaaaaeghobaaaadaaaaaaaagabaaaadaaaaaadiaaaaaiecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaaaaaaaaaihcaabaaaabaaaaaa
egadbaiaebaaaaaaaaaaaaaaegacbaaaacaaaaaadcaaaaajhccabaaaaaaaaaaa
kgakbaaaaaaaaaaaegacbaaaabaaaaaaegadbaaaaaaaaaaadgaaaaaficcabaaa
aaaaaaaadkaabaaaabaaaaaadoaaaaab"
}




}
 }
}
}