// Compiled shader for all platforms, uncompressed size: 55.8KB

Shader "Futile/LevelMelt" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 5 math
 //        d3d9 : 6 math
 //        gles : 160 math, 13 texture, 12 branch
 //       gles3 : 160 math, 13 texture, 12 branch
 //   glesdesktop : 160 math, 13 texture, 12 branch
 //       metal : 3 math
 //      opengl : 6 math
 // Stats for Fragment shader:
 //       d3d11 : 105 math, 13 texture, 8 branch
 //        d3d9 : 208 math, 13 texture, 7 branch
 //       metal : 160 math, 13 texture, 12 branch
 //      opengl : 211 math, 11 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 96
Vector 80 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedfokgkoliopnhdegadlbaonholdeaahdgabaaaaaamiacaaaaadaaaaaa
cmaaaaaapeaaaaaagiabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheogmaaaaaaadaaaaaa
aiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaagfaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaacaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaedepemepfcaaklfdeieefcfiabaaaaeaaaabaafgaaaaaafjaaaaaeegiocaaa
aaaaaaaaagaaaaaafjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaa
aaaaaaaafpaaaaaddcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadpccabaaa
acaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaa
afaaaaaaogikcaaaaaaaaaaaafaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaa
afaaaaaadoaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 105 math, 13 textures, 8 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_NoiseTex] 2D 3
SetTexture 3 [_PalTex] 2D 2
ConstBuffer "$Globals" 96
Float 20 [_RAIN]
Vector 32 [_spriteRect]
Float 64 [_fogAmount]
BindCB  "$Globals" 0
"ps_4_0
eefiecedehadkbcpojofamdnkpjmdgchnlcdmklmabaaaaaaimbdaaaaadaaaaaa
cmaaaaaakaaaaaaaneaaaaaaejfdeheogmaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaagfaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaiaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
epfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaa
aaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieefclabcaaaaeaaaaaaa
kmaeaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaafkaaaaadaagabaaaaaaaaaaa
fkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaa
adaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaafibiaaaeaahabaaaadaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadicbabaaaacaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacahaaaaaaaaaaaaakdcaabaaaaaaaaaaaegiacaia
ebaaaaaaaaaaaaaaacaaaaaaogikcaaaaaaaaaaaacaaaaaadcaaaaakfcaabaaa
aaaaaaaaagbbbaaaabaaaaaaagabbaaaaaaaaaaaagibcaaaaaaaaaaaacaaaaaa
efaaaaajpcaabaaaabaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaa
abaaaaaadiaaaaakdcaabaaaacaaaaaaegaabaaaabaaaaaaaceaaaaaaaaahped
aaaahpedaaaaaaaaaaaaaaaabiaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaabaaaaaa
bkaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaahbcaabaaaabaaaaaackaabaaa
abaaaaaaakaabaaaabaaaaaablaaaaafdcaabaaaacaaaaaaegaabaaaacaaaaaa
cbaaaaahccaabaaaabaaaaaabkaabaaaacaaaaaaabeaaaaabaaaaaaaboaaaaak
dcaabaaaadaaaaaabgafbaaaacaaaaaaaceaaaaapappppppppppppppaaaaaaaa
aaaaaaaadgaaaaafecaabaaaadaaaaaaabeaaaaaaaaaaaaadgaaaaafecaabaaa
acaaaaaaabeaaaaaaaaaiadpdhaaaaajmcaabaaaabaaaaaafgafbaaaabaaaaaa
agaibaaaadaaaaaafgajbaaaacaaaaaaclaaaaafbcaabaaaacaaaaaabkaabaaa
adaaaaaadiaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaaijiiaidn
bnaaaaaiccaabaaaacaaaaaaakaabaaaacaaaaaaakaabaiaebaaaaaaacaaaaaa
bkaaaaagbcaabaaaacaaaaaaakaabaiaibaaaaaaacaaaaaadhaaaaakbcaabaaa
acaaaaaabkaabaaaacaaaaaaakaabaaaacaaaaaaakaabaiaebaaaaaaacaaaaaa
diaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaaaaaapaebblaaaaaf
bcaabaaaacaaaaaaakaabaaaacaaaaaacbaaaaahicaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaafaaaaaaaaaaaaaiicaabaaaaaaaaaaackaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaadaaaaaamgaabaaaaaaaaaaa
eghobaaaabaaaaaaaagabaaaaaaaaaaabpaaaeaddkaabaaaacaaaaaadbaaaaah
icaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaaadaaaaaadjaaaaakdcaabaaa
adaaaaaajgafbaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
dmaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaadaaaaaadmaaaaah
icaabaaaaaaaaaaabkaabaaaadaaaaaadkaabaaaaaaaaaaadhaaaaajbcaabaaa
acaaaaaadkaabaaaaaaaaaaaabeaaaaaafaaaaaaakaabaaaacaaaaaabfaaaaab
diaaaaakdcaabaaaadaaaaaafgbfbaaaabaaaaaaaceaaaaailombaecilomeiec
aaaaaaaaaaaaaaaadiaaaaalmcaabaaaadaaaaaafgifcaaaaaaaaaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaagnohpldndgkldododcaaaaamdcaabaaaaeaaaaaa
fgbfbaaaabaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaaaaaaaaaaaaogakbaaa
adaaaaaadgaaaaafecaabaaaaeaaaaaaakbabaaaabaaaaaaefaaaaajpcaabaaa
afaaaaaacgakbaaaaeaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaadcaaaaaj
icaabaaaaaaaaaaaakaabaaaafaaaaaaabeaaaaamdpfmiebakaabaaaadaaaaaa
dcaaaaakicaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaaomfbciea
dkaabaaaaaaaaaaaclaaaaaficaabaaaacaaaaaaakaabaaaacaaaaaadcaaaaaj
icaabaaaaaaaaaaadkaabaaaacaaaaaaabeaaaaandjeikdodkaabaaaaaaaaaaa
enaaaaagicaabaaaaaaaaaaaaanaaaaadkaabaaaaaaaaaaadcaaaaajicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaaj
icaabaaaaeaaaaaaakbabaaaabaaaaaaabeaaaaaaaaaaamaabeaaaaaaaaaaaea
efaaaaajpcaabaaaaeaaaaaahgapbaaaaeaaaaaaeghobaaaacaaaaaaaagabaaa
adaaaaaadcaaaaajbcaabaaaadaaaaaaakaabaaaaeaaaaaaabeaaaaamdpfmieb
bkaabaaaadaaaaaadcaaaaakbcaabaaaadaaaaaabkiacaaaaaaaaaaaabaaaaaa
abeaaaaadfcejieaakaabaaaadaaaaaadcaaaaajicaabaaaacaaaaaadkaabaaa
acaaaaaaabeaaaaandjeikdoakaabaaaadaaaaaaenaaaaagicaabaaaacaaaaaa
aanaaaaadkaabaaaacaaaaaadcaaaaajicaabaaaacaaaaaadkaabaaaacaaaaaa
abeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaakicaabaaaaaaaaaaadkaabaia
ebaaaaaaaaaaaaaadkaabaaaacaaaaaaabeaaaaaaaaaiadpcpaaaaaficaabaaa
aaaaaaaadkaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaaaaapaebbjaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaaj
icaabaaaacaaaaaadkaabaaaaaaaaaaaabeaaaaaipmcpfdmabeaaaaaaknhcdlm
dcaaaaajccaabaaaadaaaaaadkaabaaaacaaaaaadkbabaaaacaaaaaabkbabaaa
abaaaaaadgaaaaafbcaabaaaadaaaaaaakbabaaaabaaaaaaefaaaaajpcaabaaa
aeaaaaaaegaabaaaadaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadiaaaaah
icaabaaaacaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaahpedblaaaaaficaabaaa
acaaaaaadkaabaaaacaaaaaaboaaaaahicaabaaaacaaaaaadkaabaaaacaaaaaa
abeaaaaappppppppclaaaaaficaabaaaacaaaaaadkaabaaaacaaaaaadiaaaaah
icaabaaaacaaaaaadkaabaaaacaaaaaaabeaaaaaijiiaidnbnaaaaaibcaabaaa
adaaaaaadkaabaaaacaaaaaadkaabaiaebaaaaaaacaaaaaabkaaaaagicaabaaa
acaaaaaadkaabaiaibaaaaaaacaaaaaadhaaaaakicaabaaaacaaaaaaakaabaaa
adaaaaaadkaabaaaacaaaaaadkaabaiaebaaaaaaacaaaaaadiaaaaahicaabaaa
acaaaaaadkaabaaaacaaaaaaabeaaaaaaaaapaebedaaaaafbcaabaaaadaaaaaa
dkaabaaaacaaaaaadiaaaaahecaabaaaadaaaaaadkaabaaaabaaaaaaakaabaaa
adaaaaaadiaaaaahbcaabaaaaeaaaaaackaabaaaadaaaaaaabeaaaaaaaaaaadn
dgaaaaafccaabaaaaeaaaaaaabeaaaaaaaaaiadnefaaaaajpcaabaaaafaaaaaa
egaabaaaaeaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaabpaaaeadakaabaaa
abaaaaaadgaaaaaiocaabaaaagaaaaaaaceaaaaaaaaaaaaaaaaaialpaaaaialp
aaaaialpdgaaaaaihcaabaaaacaaaaaaaceaaaaabpaaaaaaaaaaialpaaaaaaaa
aaaaaaaabcaaaaabdcaaaaakccaabaaaaaaaaaaabkaabaaaadaaaaaabkaabaaa
aaaaaaaabkiacaaaaaaaaaaaacaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaa
aaaaaaaaabeaaaaaaamakkeeebaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaa
aaaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaadpdiaaaaah
bcaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaadoidpdkdiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaeaeeebaaaaafccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaaaaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaadpdiaaaaahecaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaklkkkkdk
blaaaaafccaabaaaaaaaaaaadkaabaaaacaaaaaaaaaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaaalpdcaaaaakicaabaaaaaaaaaaadkaabaia
mbaaaaaaaaaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaiadpaaaaaaaibcaabaaa
abaaaaaadkbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpaaaaaaaiicaabaaa
aaaaaaaadkaabaaaaaaaaaaaakaabaiaebaaaaaaabaaaaaadeaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaaaadcaaaaajbcaabaaaabaaaaaa
dkbabaaaacaaaaaaabeaaaaaaaaabambabeaaaaaaaaacaebcpaaaaaficaabaaa
aaaaaaaadkaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
akaabaaaabaaaaaabjaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaccaaaaah
bcaabaaaabaaaaaaabeaaaaaaaaaaaaackaabaaaabaaaaaaccaaaaahecaabaaa
abaaaaaackaabaaaabaaaaaaabeaaaaaadaaaaaaabaaaaahbcaabaaaabaaaaaa
ckaabaaaabaaaaaaakaabaaaabaaaaaadeaaaaahecaabaaaabaaaaaackaabaaa
aeaaaaaadkaabaaaaaaaaaaadhaaaaajecaabaaaacaaaaaaakaabaaaabaaaaaa
ckaabaaaabaaaaaadkaabaaaaaaaaaaaefaaaaampcaabaaaaeaaaaaaaceaaaaa
aaaaeadnaaaahadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaa
ccaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaakaaaaaaabaaaaah
icaabaaaaaaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaadpaaaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaadkaabaaaabaaaaaadhaaaaajccaabaaaaaaaaaaa
bkaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaadaaaaaadiaaaaaiccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakiacaaaaaaaaaaaaeaaaaaadicaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaijiiaidnaaaaaaaipcaabaaaabaaaaaaegaobaia
ebaaaaaaafaaaaaaegaobaaaaeaaaaaadcaaaaajpcaabaaaagaaaaaafgafbaaa
aaaaaaaaegaobaaaabaaaaaaegaobaaaafaaaaaadgaaaaafccaabaaaacaaaaaa
akaabaaaagaaaaaabfaaaaabcbaaaaahccaabaaaaaaaaaaaakaabaaaacaaaaaa
abeaaaaaafaaaaaaaaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpefaaaaajpcaabaaaabaaaaaaigaabaaaaaaaaaaaeghobaaa
abaaaaaaaagabaaaaaaaaaaabpaaaeadbkaabaaaaaaaaaaadbaaaaahbcaabaaa
aaaaaaaaabeaaaaaibiaiadlakaabaaaabaaaaaadjaaaaakgcaabaaaaaaaaaaa
fgagbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaah
bcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaahbcaabaaa
aaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaadhaaaaajocaabaaaagaaaaaa
agaabaaaaaaaaaaafgaobaaaabaaaaaafgaobaaaagaaaaaadgaaaaaigcaabaaa
abaaaaaaaceaaaaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaaaadhaaaaajhcaabaaa
acaaaaaaagaabaaaaaaaaaaabgagbaaaabaaaaaaegacbaaaacaaaaaadgaaaaaf
bcaabaaaagaaaaaabkaabaaaacaaaaaabcaaaaabdgaaaaafbcaabaaaagaaaaaa
bkaabaaaacaaaaaabfaaaaabbiaaaaahbcaabaaaaaaaaaaaakaabaaaagaaaaaa
abeaaaaaaaaaialpbpaaaeadakaabaaaaaaaaaaaefaaaaampcaabaaaagaaaaaa
aceaaaaaaaaaiadmaaaahadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaa
acaaaaaaaaaaaaaibcaabaaaaaaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaiadpdiaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaaaaaaaaa
diaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaadpdiaaaaahecaabaaa
acaaaaaaakaabaaaaaaaaaaadkbabaaaacaaaaaabfaaaaabclaaaaafbcaabaaa
aaaaaaaaakaabaaaacaaaaaadiaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaijiiaidndiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaa
acaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaphefkdl
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadp
dcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaackaabaaa
acaaaaaadbaaaaahecaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaeadp
bpaaaeadckaabaaaaaaaaaaaefaaaaampcaabaaaabaaaaaaaceaaaaaaaaahmdp
aaaadadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaaefaaaaam
pcaabaaaacaaaaaaaceaaaaaaaaahedpaaaabadpaaaaaaaaaaaaaaaaeghobaaa
adaaaaaaaagabaaaacaaaaaaaaaaaaaipcaabaaaacaaaaaaegaobaiaebaaaaaa
abaaaaaaegaobaaaacaaaaaadcaaaaajpcaabaaaabaaaaaafgafbaaaaaaaaaaa
egaobaaaacaaaaaaegaobaaaabaaaaaadiaaaaahecaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaklkkkkdpaaaaaaaipcaabaaaabaaaaaaegaobaiaebaaaaaa
agaaaaaaegaobaaaabaaaaaadcaaaaajpccabaaaaaaaaaaakgakbaaaaaaaaaaa
egaobaaaabaaaaaaegaobaaaagaaaaaabcaaaaabefaaaaampcaabaaaabaaaaaa
aceaaaaaaaaahmdpaaaadadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaa
acaaaaaaefaaaaampcaabaaaacaaaaaaaceaaaaaaaaahedpaaaabadpaaaaaaaa
aaaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaaaaaaaaaipcaabaaaacaaaaaa
egaobaiaebaaaaaaabaaaaaaegaobaaaacaaaaaadcaaaaajpcaabaaaabaaaaaa
fgafbaaaaaaaaaaaegaobaaaacaaaaaaegaobaaaabaaaaaaaaaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaealpaaaaaaalpcaabaaaacaaaaaa
egaobaiaebaaaaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadp
dcaaaaajpccabaaaaaaaaaaaagaabaaaaaaaaaaaegaobaaaacaaaaaaegaobaaa
abaaaaaabfaaaaabdoaaaaab"
}




}
 }
}
}