// Compiled shader for all platforms, uncompressed size: 37.0KB

Shader "Futile/MapAerial" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 83 math, 3 texture, 10 branch
 //       gles3 : 83 math, 3 texture, 10 branch
 //   glesdesktop : 83 math, 3 texture, 10 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 61 math, 2 texture, 14 branch
 //        d3d9 : 127 math, 3 texture, 5 branch
 //       metal : 83 math, 3 texture, 10 branch
 //      opengl : 119 math, 2 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 61 math, 2 textures, 14 branches
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_mapFogTexture] 2D 1
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 20 [_screenSize] 2
Vector 32 [_mapSize] 2
Vector 40 [_mapPan] 2
Vector 48 [_MapCol]
BindCB  "$Globals" 0
"ps_4_0
eefiecedcgkcpcblfbdbpiflknkofcgjomdjcflpabaaaaaammakaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcniajaaaaeaaaaaaahgacaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaad
pcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacadaaaaaaaaaaaaak
pcaabaaaaaaaaaaaogbebaaaabaaaaaaaceaaaaaaaaaaalpaaaaaalpaaaaaalp
aaaaaalpapaaaaahbcaabaaaabaaaaaaegaabaaaaaaaaaaaegaabaaaaaaaaaaa
elaaaaafccaabaaaabaaaaaaakaabaaaabaaaaaaddaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaabeaaaaaaaaaiadpeeaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaadiaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaaagaabaaaabaaaaaa
aaaaaaaibcaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
diaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaaagaabaaaabaaaaaadcaaaaaj
bcaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaiaea
cpaaaaafccaabaaaabaaaaaabkaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaa
bkaabaaaabaaaaaaakaabaaaabaaaaaabjaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaadiaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaaagaabaaaabaaaaaa
aaaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaklkkkkdodiaaaaaldcaabaaa
abaaaaaaegiacaaaaaaaaaaaacaaaaaaaceaaaaagpbcaddlgpbcaddlaaaaaaaa
aaaaaaaaaoaaaaahdcaabaaaacaaaaaaegaabaaaaaaaaaaaegaabaaaabaaaaaa
biaaaaakdcaabaaaaaaaaaaakgbkbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaiadpabeaaaaaaaaaaadpdhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaaaaabkaabaaaaaaaaaaaaoaaaaajdcaabaaaabaaaaaajgifcaaa
aaaaaaaaabaaaaaaegiacaaaaaaaaaaaacaaaaaadiaaaaahgcaabaaaaaaaaaaa
kgalbaaaaaaaaaaaagabbaaaabaaaaaadcaaaaajicaabaaaaaaaaaaabkbabaaa
acaaaaaaabeaaaaaaaaamadpabeaaaaaaaaafaeaaoaaaaahgcaabaaaaaaaaaaa
fgagbaaaaaaaaaaapgapbaaaaaaaaaaaaaaaaaaibcaabaaaabaaaaaabkaabaaa
aaaaaaaackiacaaaaaaaaaaaacaaaaaadiaaaaahccaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaklkkckdpdcaaaaakicaabaaaaaaaaaaadkiacaaaaaaaaaaa
acaaaaaaabeaaaaaklkkkkdobkaabaaaaaaaaaaadcaaaaajccaabaaaabaaaaaa
ckaabaaaaaaaaaaaabeaaaaaklkkkkdodkaabaaaaaaaaaaaaaaaaaaidcaabaaa
abaaaaaaegaabaiaebaaaaaaacaaaaaaegaabaaaabaaaaaadbaaaaahecaabaaa
aaaaaaaabkaabaaaabaaaaaabkaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaiadpdiaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkkkdodbaaaaahicaabaaaaaaaaaaa
akaabaaaaaaaaaaabkaabaaaabaaaaaadhaaaaajbcaabaaaaaaaaaaadkaabaaa
aaaaaaaaakaabaaaaaaaaaaabkaabaaaabaaaaaadhaaaaajecaabaaaabaaaaaa
ckaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaaefaaaaajpcaabaaa
aaaaaaaaigaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaadbaaaaah
icaabaaaaaaaaaaaabeaaaaaaaaaaadpbkaabaaaaaaaaaaaefaaaaajpcaabaaa
acaaaaaaigaabaaaabaaaaaaeghobaaaabaaaaaaaagabaaaabaaaaaadbaaaaah
ccaabaaaabaaaaaaakaabaaaacaaaaaaabeaaaaaaaaaaadpdmaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaabpaaaeaddkaabaaaaaaaaaaa
diaaaaahicaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaamnmmmmdoaaaaaaai
ccaabaaaabaaaaaaakbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaah
iccabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaadgaaaaaihccabaaa
aaaaaaaaaceaaaaaaaaaiadoaaaaiadoaaaaiadoaaaaaaaadoaaaaabbfaaaaab
bnaaaaahicaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaajkjjjjdobnaaaaah
ccaabaaaabaaaaaaabeaaaaadddddddpakaabaaaaaaaaaaaabaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaabiaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaaaaaaabaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaadkaabaaaaaaaaaaabpaaaeadbkaabaaaaaaaaaaadgaaaaaihccabaaa
aaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadgaaaaaficcabaaa
aaaaaaaadkbabaaaacaaaaaadoaaaaabbcaaaaabdbaaaaahccaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaajkjjjjdobpaaaeadbkaabaaaaaaaaaaadbaaaaah
ccaabaaaaaaaaaaaakaabaaaacaaaaaaabeaaaaahbdnakdpbpaaaeadbkaabaaa
aaaaaaaadgaaaaaghccabaaaaaaaaaaaegiccaaaaaaaaaaaadaaaaaadgaaaaaf
iccabaaaaaaaaaaadkbabaaaacaaaaaadoaaaaabbcaaaaabdiaaaaahccaabaaa
aaaaaaaadkbabaaaacaaaaaaabeaaaaadddddddpaaaaaaaiicaabaaaaaaaaaaa
akbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaahiccabaaaaaaaaaaa
dkaabaaaaaaaaaaabkaabaaaaaaaaaaadgaaaaaihccabaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabbcaaaaabdiaaaaai
ccaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaaabeaaaaaaaaajgecaoaaaaai
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaaacaaaaaaaaaaaaai
ccaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaaakaabaaaabaaaaaadiaaaaai
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaaacaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaiadoenaaaaagccaabaaa
aaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaajccaabaaaaaaaaaaabkaabaaa
aaaaaaaaabeaaaaammmmmmdoabeaaaaaaaaaaadpdiaaaaahbcaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaadbaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadcaaaaajbcaabaaa
aaaaaaaaakbabaaaacaaaaaaabeaaaaamnmmmmloabeaaaaaaaaaaadpdiaaaaah
iccabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaaacaaaaaadgaaaaaihccabaaa
aaaaaaaaaceaaaaamnmmemdnmnmmemdnmnmmemdpaaaaaaaadoaaaaabbcaaaaab
diaaaaahbcaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaamnmmmmdoaaaaaaai
ccaabaaaaaaaaaaaakbabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaah
iccabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadgaaaaaihccabaaa
aaaaaaaaaceaaaaaaaaaiadoaaaaiadoaaaaiadoaaaaaaaadoaaaaabbfaaaaab
bfaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}