// Compiled shader for all platforms, uncompressed size: 58.1KB

Shader "Futile/DeepWater" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 165 math, 9 texture, 10 branch
 //       gles3 : 165 math, 9 texture, 10 branch
 //   glesdesktop : 165 math, 9 texture, 10 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 128 math, 9 texture, 13 branch
 //        d3d9 : 236 math, 9 texture, 8 branch
 //       metal : 165 math, 9 texture, 10 branch
 //      opengl : 215 math, 8 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 128 math, 9 textures, 13 branches
SetTexture 0 [_NoiseTex] 2D 2
SetTexture 1 [_LevelTex] 2D 1
SetTexture 2 [_GrabTexture] 2D 0
SetTexture 3 [_PalTex] 2D 3
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
Float 56 [_waterDepth]
BindCB  "$Globals" 0
"ps_4_0
eefiecedpbnoccinkgkgbalahfolmfpcpokgkopfabaaaaaanibeaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadacaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapahaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcoebdaaaaeaaaaaaapjaeaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaae
aahabaaaacaaaaaaffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaagcbaaaad
ccbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacahaaaaaadiaaaaaihcaabaaaaaaaaaaa
ogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafhcaabaaaaaaaaaaa
egacbaaaaaaaaaaaaoaaaaaihcaabaaaaaaaaaaaegacbaaaaaaaaaaaegiacaaa
aaaaaaaaadaaaaaaaaaaaaajhcaabaaaaaaaaaaaegacbaaaaaaaaaaaegiacaia
ebaaaaaaaaaaaaaaacaaaaaaaaaaaaakhcaabaaaabaaaaaaegiacaiaebaaaaaa
aaaaaaaaacaaaaaaogikcaaaaaaaaaaaacaaaaaaaoaaaaahhcaabaaaaaaaaaaa
egacbaaaaaaaaaaaegacbaaaabaaaaaadiaaaaakdcaabaaaabaaaaaaggakbaaa
aaaaaaaaaceaaaaajkjjjjdpjkjjjjdpaaaaaaaaaaaaaaaaefaaaaajpcaabaaa
abaaaaaaegaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadcaaaaak
icaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaeaeaakiacaaaaaaaaaaa
abaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaamdpfmiea
enaaaaagicaabaaaaaaaaaaaaanaaaaadkaabaaaaaaaaaaadcaaaaajicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaaj
icaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaagpbciddlabeaaaaagpbcadll
cpaaaaafbcaabaaaabaaaaaabkbabaaaabaaaaaadiaaaaakdcaabaaaabaaaaaa
agaabaaaabaaaaaaaceaaaaaaaaaeiedaaaacaebaaaaaaaaaaaaaaaabjaaaaaf
dcaabaaaabaaaaaaegaabaaaabaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaajiebabeaaaaaaaaaiadpdiaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaakaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaabkbabaaa
abaaaaaabkbabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaakaabaaa
abaaaaaadiaaaaaibcaabaaaabaaaaaaakaabaaaabaaaaaabkiacaaaaaaaaaaa
adaaaaaadiaaaaaiicaabaaaaaaaaaaadkaabaaaaaaaaaaaakiacaaaaaaaaaaa
adaaaaaaebaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaaoaaaaaibcaabaaa
acaaaaaadkaabaaaaaaaaaaaakiacaaaaaaaaaaaadaaaaaadiaaaaahicaabaaa
aaaaaaaaakaabaaaabaaaaaaabeaaaaaaknhkdlmebaaaaaficaabaaaaaaaaaaa
dkaabaaaaaaaaaaaaoaaaaaiccaabaaaacaaaaaadkaabaaaaaaaaaaabkiacaaa
aaaaaaaaadaaaaaaaaaaaaahfcaabaaaabaaaaaakgajbaaaaaaaaaaaagabbaaa
acaaaaaaefaaaaajpcaabaaaadaaaaaaigaabaaaabaaaaaaeghobaaaabaaaaaa
aagabaaaabaaaaaaaaaaaaaigcaabaaaaeaaaaaakgblbaaaabaaaaaaagbbbaia
ebaaaaaaacaaaaaaaoaaaaajicaabaaaaaaaaaaaakiacaaaaaaaaaaaadaaaaaa
bkiacaaaaaaaaaaaadaaaaaadiaaaaahbcaabaaaaeaaaaaadkaabaaaaaaaaaaa
bkaabaaaaeaaaaaaapaaaaajicaabaaaaaaaaaaaigaabaiaebaaaaaaaeaaaaaa
igaabaiaebaaaaaaaeaaaaaaelaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaa
dcaaaaajbcaabaaaabaaaaaackbabaaaacaaaaaaabeaaaaaaaaafambabeaaaaa
aaaakiebdicaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaa
dcaaaaajbcaabaaaabaaaaaaakaabaaaadaaaaaaabeaaaaaaaaahpedabeaaaaa
aaaaialpdiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaijiiaidn
bnaaaaaiecaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
bkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaadhaaaaakbcaabaaa
abaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
aaaaaaalgcaabaaaabaaaaaafgaebaiaebaaaaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaiadpaaaaaaaadiaaaaahicaabaaaabaaaaaackaabaaaabaaaaaa
ckaabaaaabaaaaaadcaaaaajicaabaaaaaaaaaaackaabaaaabaaaaaadkaabaaa
abaaaaaadkaabaaaaaaaaaaaddaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaaaaaiadpaaaaaaahbcaabaaaaeaaaaaaakaabaaaacaaaaaackbabaaa
abaaaaaaaaaaaaaiecaabaaaabaaaaaadkbabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaiadpaaaaaaaiccaabaaaaeaaaaaabkaabaiaebaaaaaaacaaaaaackaabaaa
abaaaaaaefaaaaajpcaabaaaaeaaaaaaegaabaaaaeaaaaaaeghobaaaacaaaaaa
aagabaaaaaaaaaaabiaaaaakhcaabaaaafaaaaaaegacbaaaaeaaaaaaaceaaaaa
aaaaaaaaibiaaadmaaaaaaaaaaaaaaaaabaaaaahecaabaaaabaaaaaabkaabaaa
afaaaaaaakaabaaaafaaaaaaabaaaaahecaabaaaabaaaaaackaabaaaafaaaaaa
ckaabaaaabaaaaaabpaaaeadckaabaaaabaaaaaadgaaaaafecaabaaaabaaaaaa
abeaaaaaaaaaiadpdgaaaaaihcaabaaaaeaaaaaaaceaaaaaaaaaaaaaibiaaadm
aaaaaaaaaaaaaaaabcaaaaabbiaaaaakhcaabaaaadaaaaaaegacbaaaadaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahicaabaaaabaaaaaa
bkaabaaaadaaaaaaakaabaaaadaaaaaaabaaaaahicaabaaaabaaaaaackaabaaa
adaaaaaadkaabaaaabaaaaaadhaaaaajecaabaaaabaaaaaadkaabaaaabaaaaaa
abeaaaaaaaaaiadpakaabaaaabaaaaaadbaaaaahbcaabaaaabaaaaaaabeaaaaa
mnmmemdockaabaaaabaaaaaabpaaaeadakaabaaaabaaaaaadbaaaaahbcaabaaa
abaaaaaaabeaaaaaibiaiadlakaabaaaaeaaaaaadjaaaaakmcaabaaaacaaaaaa
fgajbaaaaeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaackaabaaaacaaaaaadmaaaaahbcaabaaa
abaaaaaadkaabaaaacaaaaaaakaabaaaabaaaaaabpaaaeadakaabaaaabaaaaaa
biaaaaahbcaabaaaabaaaaaabkaabaaaaeaaaaaaabeaaaaaibiaiadlabaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaaakaabaaaafaaaaaaabaaaaahbcaabaaa
abaaaaaackaabaaaafaaaaaaakaabaaaabaaaaaabpaaaeadakaabaaaabaaaaaa
dgaaaaafecaabaaaabaaaaaaabeaaaaaaaaaiadpdgaaaaaipcaabaaaaeaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabcaaaaabefaaaaampcaabaaa
adaaaaaaaceaaaaaaaaadadoaaaahadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaa
aagabaaaadaaaaaaaaaaaaalpcaabaaaafaaaaaaegaobaiaebaaaaaaadaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpdcaaaaampcaabaaaadaaaaaa
egaobaaaafaaaaaaaceaaaaaaaaaeadpaaaaeadpaaaaeadpaaaaeadpegaobaaa
adaaaaaadiaaaaahpcaabaaaaeaaaaaaegaobaaaadaaaaaaegaobaaaaeaaaaaa
dgaaaaaficaabaaaaaaaaaaaabeaaaaaaaaaiadpdgaaaaafecaabaaaabaaaaaa
abeaaaaamnmmemdobfaaaaabbcaaaaabdgaaaaaigcaabaaaaeaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabfaaaaabbcaaaaabdgaaaaaipcaabaaa
aeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaiadpbfaaaaabbfaaaaab
efaaaaajpcaabaaaadaaaaaaggakbaaaaaaaaaaaeghobaaaabaaaaaaaagabaaa
abaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaadaaaaaaabeaaaaaaaaahped
abeaaaaaaaaaialpdiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaa
ijiiaidnbnaaaaaiicaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaa
abaaaaaabkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaadhaaaaak
bcaabaaaabaaaaaadkaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaa
abaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaapaeb
diaaaaaiicaabaaaabaaaaaackiacaaaaaaaaaaaadaaaaaaabeaaaaaaaaapieb
dbaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaadkaabaaaabaaaaaadeaaaaah
ccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaaadpcpaaaaafecaabaaa
abaaaaaackaabaaaabaaaaaadiaaaaahccaabaaaabaaaaaackaabaaaabaaaaaa
bkaabaaaabaaaaaabjaaaaafccaabaaaabaaaaaabkaabaaaabaaaaaadiaaaaah
ecaabaaaabaaaaaabkaabaaaabaaaaaabkbabaaaabaaaaaadiaaaaakmcaabaaa
acaaaaaakgakbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaklkkkkdomnmmemdo
aaaaaaalhcaabaaaadaaaaaaggakbaiaebaaaaaaaaaaaaaaaceaaaaaaaaaaadp
aaaaaadpaaaaaadpaaaaaaaadcaaaaajncaabaaaadaaaaaakgaobaaaacaaaaaa
agajbaaaadaaaaaaagajbaaaaaaaaaaadiaaaaakfcaabaaaaaaaaaaaagadbaaa
adaaaaaaaceaaaaaggggageaaaaaaaaaggggkgdpaaaaaaaadcaaaaamfcaabaaa
aaaaaaaakgakbaaaabaaaaaaaceaaaaamnmmmmdnaaaaaaaacfejbcdoaaaaaaaa
agacbaaaaaaaaaaaaaaaaaahdcaabaaaafaaaaaaagaabaaaacaaaaaaigaabaaa
aaaaaaaadcaaaaakbcaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaaabeaaaaa
mnmmmmdndkaabaaaacaaaaaadcaaaaajbcaabaaaaaaaaaaackaabaaaadaaaaaa
abeaaaaaggggageaakaabaaaaaaaaaaaaaaaaaahecaabaaaafaaaaaabkaabaaa
acaaaaaaakaabaaaaaaaaaaaefaaaaajpcaabaaaagaaaaaaigaabaaaafaaaaaa
eghobaaaaaaaaaaaaagabaaaacaaaaaadiaaaaakfcaabaaaaaaaaaaakgakbaaa
abaaaaaaaceaaaaaaaaaaadoaaaaaaaaklkkckdoaaaaaaaadcaaaaakbcaabaaa
aaaaaaaaakiacaaaaaaaaaaaabaaaaaaabeaaaaadnakfhloakaabaaaaaaaaaaa
dcaaaaajccaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaadaaaaaabkaabaaa
aaaaaaaadcaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaggggkgdp
akaabaaaaaaaaaaaaaaaaaahicaabaaaafaaaaaabkaabaaaacaaaaaaakaabaaa
aaaaaaaaefaaaaajpcaabaaaacaaaaaangafbaaaafaaaaaaeghobaaaaaaaaaaa
aagabaaaacaaaaaabpaaaeadakaabaaaabaaaaaadgaaaaaipccabaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabdiaaaaal
dcaabaaaaaaaaaaaagiacaaaaaaaaaaaabaaaaaaaceaaaaaaaaamaeamnmmcmea
aaaaaaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaagaaaaaaabeaaaaa
aaaaoaeaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaamdpfmieaenaaaaagbcaabaaaaaaaaaaaaanaaaaaakaabaaaaaaaaaaa
dcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaa
aaaaaadpdcaaaaajccaabaaaaaaaaaaaakaabaaaacaaaaaaabeaaaaafmipmkea
bkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
mdpfmieaenaaaaagccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadp
deaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaacpaaaaaf
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaadmecbjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
bnaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaamnmmemdpdcaaaaak
ccaabaaaaaaaaaaabkaabaiaebaaaaaaabaaaaaabkbabaaaabaaaaaaabeaaaaa
aaaaaadpdcaaaaakccaabaaaaaaaaaaabkaabaiambaaaaaaaaaaaaaaabeaaaaa
aaaaaaeaabeaaaaaaaaaiadpdiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaamnmmmmdndcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaabkbabaaa
abaaaaaackaabaaaabaaaaaaddaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaaiadpdhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaa
aaaaaaaackaabaaaabaaaaaadiaaaaahccaabaaaaaaaaaaadkaabaaaaaaaaaaa
dkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaa
aaaaaaaadcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaamnmmemdp
abeaaaaamnmmemdocpaaaaafecaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaabjaaaaafccaabaaa
aaaaaaaabkaabaaaaaaaaaaaaaaaaaaiccaabaaaaaaaaaaaakaabaiaebaaaaaa
aaaaaaaabkaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaackbabaaaacaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaaefaaaaampcaabaaaabaaaaaaaceaaaaa
aaaadadoaaaahadpaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaaadaaaaaa
efaaaaampcaabaaaacaaaaaaaceaaaaaaaaabadoaaaahadpaaaaaaaaaaaaaaaa
eghobaaaadaaaaaaaagabaaaadaaaaaaaaaaaaaipcaabaaaacaaaaaaegaobaia
ebaaaaaaabaaaaaaegaobaaaacaaaaaadcaaaaajpcaabaaaaaaaaaaaagaabaaa
aaaaaaaaegaobaaaacaaaaaaegaobaaaabaaaaaadbaaaaahbcaabaaaabaaaaaa
abeaaaaaibiaiadlakaabaaaaeaaaaaadjaaaaakgcaabaaaabaaaaaafgagbaaa
aeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahbcaabaaa
abaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaadmaaaaahbcaabaaaabaaaaaa
ckaabaaaabaaaaaaakaabaaaabaaaaaabpaaaeadakaabaaaabaaaaaaaaaaaaah
bcaabaaaabaaaaaabkbabaaaabaaaaaaabeaaaaagggggglpdicaaaahbcaabaaa
abaaaaaaakaabaaaabaaaaaaabeaaaaaaaaacaebdiaaaaahccaabaaaabaaaaaa
akaabaaaabaaaaaaakaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaabkaabaaa
abaaaaaaakaabaaaabaaaaaaaaaaaaaipcaabaaaacaaaaaaegaobaiaebaaaaaa
aaaaaaaaegaobaaaaeaaaaaadcaaaaajpccabaaaaaaaaaaaagaabaaaabaaaaaa
egaobaaaacaaaaaaegaobaaaaaaaaaaadoaaaaabbcaaaaabdgaaaaafpccabaaa
aaaaaaaaegaobaaaaaaaaaaadoaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}