// Compiled shader for all platforms, uncompressed size: 65.8KB

Shader "Futile/FlareBomb" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 202 math, 10 texture, 27 branch
 //       gles3 : 202 math, 10 texture, 27 branch
 //   glesdesktop : 202 math, 10 texture, 27 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 137 math, 10 texture, 10 branch
 //        d3d9 : 169 math, 4 texture, 8 branch
 //       metal : 202 math, 10 texture, 27 branch
 //      opengl : 271 math, 10 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 137 math, 10 textures, 10 branches
SetTexture 0 [_LevelTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 80
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedpbkkmmglokdellkfkchikfnhhembldalabaaaaaabibhaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefccebgaaaaeaaaaaaaijafaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaad
pcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacajaaaaaadiaaaaai
pcaabaaaaaaaaaaaogbobaaaabaaaaaaegiecaaaaaaaaaaaadaaaaaaebaaaaaf
pcaabaaaaaaaaaaaegaobaaaaaaaaaaaaoaaaaaipcaabaaaaaaaaaaaegaobaaa
aaaaaaaaegiecaaaaaaaaaaaadaaaaaaaaaaaaajpcaabaaaaaaaaaaaegaobaaa
aaaaaaaaegiecaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakpcaabaaaabaaaaaa
egiecaiaebaaaaaaaaaaaaaaacaaaaaaogiocaaaaaaaaaaaacaaaaaaaoaaaaah
pcaabaaaaaaaaaaaegaobaaaaaaaaaaaegaobaaaabaaaaaaefaaaaajpcaabaaa
abaaaaaaogakbaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaaj
icaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialp
diaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaijiiaidnbnaaaaai
bcaabaaaacaaaaaadkaabaaaabaaaaaadkaabaiaebaaaaaaabaaaaaabkaaaaag
icaabaaaabaaaaaadkaabaiaibaaaaaaabaaaaaadhaaaaakicaabaaaabaaaaaa
akaabaaaacaaaaaadkaabaaaabaaaaaadkaabaiaebaaaaaaabaaaaaabiaaaaak
hcaabaaaabaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaaaaaabaaaaahbcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaa
abaaaaahbcaabaaaabaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaadhaaaaaj
bcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaiadpdkaabaaaabaaaaaa
dbaaaaahccaabaaaabaaaaaaabeaaaaamnmmemdoakaabaaaabaaaaaadcaaaaap
mcaabaaaabaaaaaakgbobaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadp
aaaaialpaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaiadpefaaaaajpcaabaaa
acaaaaaaogakbaaaabaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabpaaaead
bkaabaaaabaaaaaadbaaaaahccaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaa
acaaaaaadjaaaaakmcaabaaaabaaaaaafgajbaaaacaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaabaaaaaackaabaaaabaaaaaa
bkaabaaaabaaaaaadmaaaaahccaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaa
abaaaaaadhaaaaajbcaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaamnmmemdo
akaabaaaabaaaaaabfaaaaabbiaaaaahccaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaaaaaaiadpaaaaaaakpcaabaaaacaaaaaaegbebaaaabaaaaaaaceaaaaa
aaaaaalpaaaaaalpaaaaaalpaaaaaalpapaaaaahecaabaaaabaaaaaaogakbaaa
acaaaaaaogakbaaaacaaaaaaeeaaaaaficaabaaaabaaaaaackaabaaaabaaaaaa
diaaaaahpcaabaaaacaaaaaapgapbaaaabaaaaaaegaobaaaacaaaaaaelaaaaaf
ecaabaaaabaaaaaackaabaaaabaaaaaaddaaaaahecaabaaaabaaaaaackaabaaa
abaaaaaaabeaaaaaaaaaaadpcpaaaaaficaabaaaabaaaaaackaabaaaabaaaaaa
diaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaaaaakadpbjaaaaaf
icaabaaaabaaaaaadkaabaaaabaaaaaadiaaaaahdcaabaaaadaaaaaapgapbaaa
abaaaaaaogakbaaaacaaaaaadiaaaaahicaabaaaabaaaaaaakaabaaaabaaaaaa
akaabaaaabaaaaaadiaaaaahpcaabaaaaeaaaaaapgapbaaaabaaaaaaegaebaaa
adaaaaaadcaaaaanpcaabaaaaaaaaaaaegaobaiaebaaaaaaaeaaaaaaaceaaaaa
jkjjjjdojkjjjjdojkjjjjdojkjjjjdoegaobaaaaaaaaaaacpaaaaaficaabaaa
abaaaaaaakaabaaaabaaaaaadiaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaa
abeaaaaaaaaamadpbjaaaaaficaabaaaabaaaaaadkaabaaaabaaaaaadiaaaaah
dcaabaaaadaaaaaapgapbaaaabaaaaaaegaabaaaadaaaaaadcaaaaandcaabaaa
adaaaaaaegaabaiaebaaaaaaadaaaaaaaceaaaaajkjjjjdojkjjjjdoaaaaaaaa
aaaaaaaaogbkbaaaabaaaaaaefaaaaajpcaabaaaaeaaaaaaogakbaaaaaaaaaaa
eghobaaaaaaaaaaaaagabaaaabaaaaaadiaaaaahdcaabaaaafaaaaaakgakbaaa
abaaaaaaogakbaaaacaaaaaaaaaaaaaiecaabaaaadaaaaaabkaabaiaebaaaaaa
adaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaagaaaaaaigaabaaaadaaaaaa
eghobaaaabaaaaaaaagabaaaaaaaaaaadcaaaaankcaabaaaadaaaaaaagaebaia
ebaaaaaaafaaaaaaaceaaaaaaaaaaaaaaknhkddmaaaaaaaaaknhkddmkgaobaaa
aaaaaaaaefaaaaajpcaabaaaahaaaaaangafbaaaadaaaaaaeghobaaaaaaaaaaa
aagabaaaabaaaaaadiaaaaakpcaabaaaacaaaaaaegaobaaaacaaaaaaaceaaaaa
aknhcddnaknhcddnipmchfdnipmchfdndcaaaaankcaabaaaadaaaaaaagaebaia
ebaaaaaaafaaaaaaaceaaaaaaaaaaaaaaknhkddmaaaaaaaaaknhkddmagaibaaa
adaaaaaaefaaaaajpcaabaaaafaaaaaangafbaaaadaaaaaaeghobaaaabaaaaaa
aagabaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegaobaiaebaaaaaaacaaaaaa
kgakbaaaabaaaaaaegaobaaaaaaaaaaaefaaaaajpcaabaaaaiaaaaaaegaabaaa
aaaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaakpcaabaaaacaaaaaa
egaobaiaebaaaaaaacaaaaaakgakbaaaabaaaaaaigaibaaaadaaaaaaefaaaaaj
pcaabaaaadaaaaaaegaabaaaacaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaa
efaaaaajpcaabaaaaaaaaaaaogakbaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaa
abaaaaaaefaaaaajpcaabaaaacaaaaaaogakbaaaacaaaaaaeghobaaaabaaaaaa
aagabaaaaaaaaaaabpaaaeadbkaabaaaabaaaaaadgaaaaaipccabaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabdcaaaaaj
icaabaaaaaaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialp
diaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaai
ccaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaaaaag
icaabaaaaaaaaaaadkaabaiaibaaaaaaaaaaaaaadhaaaaakicaabaaaaaaaaaaa
bkaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabiaaaaak
hcaabaaaaeaaaaaaegacbaaaaeaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaaaaaabaaaaahccaabaaaabaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaa
abaaaaahccaabaaaabaaaaaackaabaaaaeaaaaaabkaabaaaabaaaaaadhaaaaaj
icaabaaaaaaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaiadpdkaabaaaaaaaaaaa
dbaaaaahccaabaaaabaaaaaaabeaaaaamnmmemdodkaabaaaaaaaaaaabpaaaead
bkaabaaaabaaaaaadbaaaaahccaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaa
agaaaaaadjaaaaakdcaabaaaaeaaaaaajgafbaaaagaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaa
akaabaaaaeaaaaaadmaaaaahccaabaaaabaaaaaabkaabaaaaeaaaaaabkaabaaa
abaaaaaadhaaaaajicaabaaaaaaaaaaabkaabaaaabaaaaaaabeaaaaamnmmemdo
dkaabaaaaaaaaaaabfaaaaabdbaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
akaabaaaabaaaaaaabaaaaahccaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaaiadodcaaaaajicaabaaaabaaaaaaakaabaaaahaaaaaaabeaaaaaaaaahped
abeaaaaaaaaaialpdiaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
ijiiaidnbnaaaaaiicaabaaaacaaaaaadkaabaaaabaaaaaadkaabaiaebaaaaaa
abaaaaaabkaaaaagicaabaaaabaaaaaadkaabaiaibaaaaaaabaaaaaadhaaaaak
icaabaaaabaaaaaadkaabaaaacaaaaaadkaabaaaabaaaaaadkaabaiaebaaaaaa
abaaaaaabiaaaaakhcaabaaaaeaaaaaaegacbaaaahaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaaaaaabaaaaahicaabaaaacaaaaaabkaabaaaaeaaaaaa
akaabaaaaeaaaaaaabaaaaahicaabaaaacaaaaaackaabaaaaeaaaaaadkaabaaa
acaaaaaadhaaaaajicaabaaaabaaaaaadkaabaaaacaaaaaaabeaaaaaaaaaiadp
dkaabaaaabaaaaaadbaaaaahicaabaaaacaaaaaaabeaaaaamnmmemdodkaabaaa
abaaaaaabpaaaeaddkaabaaaacaaaaaadbaaaaahicaabaaaacaaaaaaabeaaaaa
ibiaiadlakaabaaaafaaaaaadjaaaaakdcaabaaaaeaaaaaajgafbaaaafaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahicaabaaaacaaaaaa
dkaabaaaacaaaaaaakaabaaaaeaaaaaadmaaaaahicaabaaaacaaaaaabkaabaaa
aeaaaaaadkaabaaaacaaaaaadhaaaaajicaabaaaabaaaaaadkaabaaaacaaaaaa
abeaaaaamnmmemdodkaabaaaabaaaaaabfaaaaabdbaaaaahicaabaaaabaaaaaa
dkaabaaaabaaaaaaakaabaaaabaaaaaadhaaaaajicaabaaaaaaaaaaadkaabaaa
aaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaiadodhaaaaajicaabaaaaaaaaaaa
dkaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaadcaaaaajccaabaaa
abaaaaaaakaabaaaaiaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaah
ccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaa
abaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaabkaaaaagccaabaaa
abaaaaaabkaabaiaibaaaaaaabaaaaaadhaaaaakccaabaaaabaaaaaadkaabaaa
abaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaabiaaaaakhcaabaaa
aeaaaaaaegacbaaaaiaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
abaaaaahicaabaaaabaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaaabaaaaah
icaabaaaabaaaaaackaabaaaaeaaaaaadkaabaaaabaaaaaadhaaaaajccaabaaa
abaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaiadpbkaabaaaabaaaaaadbaaaaah
icaabaaaabaaaaaaabeaaaaamnmmemdobkaabaaaabaaaaaabpaaaeaddkaabaaa
abaaaaaadbaaaaahicaabaaaabaaaaaaabeaaaaaibiaiadlakaabaaaadaaaaaa
djaaaaakdcaabaaaadaaaaaajgafbaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadmaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaakaabaaa
adaaaaaadmaaaaahicaabaaaabaaaaaabkaabaaaadaaaaaadkaabaaaabaaaaaa
dhaaaaajccaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaamnmmemdobkaabaaa
abaaaaaabfaaaaabdbaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaa
abaaaaaaaaaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaiado
dhaaaaajicaabaaaaaaaaaaabkaabaaaabaaaaaadkaabaaaabaaaaaadkaabaaa
aaaaaaaadcaaaaajccaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaahped
abeaaaaaaaaaialpdiaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaa
ijiiaidnbnaaaaaiicaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaa
abaaaaaabkaaaaagccaabaaaabaaaaaabkaabaiaibaaaaaaabaaaaaadhaaaaak
ccaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaabaaaaaabkaabaiaebaaaaaa
abaaaaaabiaaaaakhcaabaaaaaaaaaaaegacbaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaa
aaaaaaaadhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadp
bkaabaaaabaaaaaadbaaaaahccaabaaaaaaaaaaaabeaaaaamnmmemdoakaabaaa
aaaaaaaabpaaaeadbkaabaaaaaaaaaaadbaaaaahccaabaaaaaaaaaaaabeaaaaa
ibiaiadlakaabaaaacaaaaaadjaaaaakkcaabaaaabaaaaaafgajbaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaabkaabaaaabaaaaaadmaaaaahccaabaaaaaaaaaaadkaabaaa
abaaaaaabkaabaaaaaaaaaaadhaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaamnmmemdoakaabaaaaaaaaaaabfaaaaabdbaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaabaaaaaaaaaaaaahccaabaaaaaaaaaaadkaabaaa
aaaaaaaaabeaaaaaaaaaiadodhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
bkaabaaaaaaaaaaadkaabaaaaaaaaaaadbaaaaahccaabaaaaaaaaaaaakaabaaa
abaaaaaaabeaaaaamnmmemdodcaaaaakecaabaaaaaaaaaaaakaabaiaebaaaaaa
abaaaaaaabeaaaaaaaaakaeaabeaaaaaaaaaiadpaaaaaaahicaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaamnmmemlodicaaaahicaabaaaaaaaaaaadkaabaaa
aaaaaaaaabeaaaaaggggkgdpdhaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaa
ckaabaaaaaaaaaaadkaabaaaaaaaaaaaaaaaaaaldcaabaaaaaaaaaaaegaabaia
ebaaaaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaaeeaaaaaf
ecaabaaaaaaaaaaaakaabaaaabaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaaiicaabaaa
aaaaaaaabkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdcaaaaajccaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaaaaaaaaah
ecaabaaaaaaaaaaackaabaaaabaaaaaackaabaaaabaaaaaadcaaaaakecaabaaa
aaaaaaaackaabaiaebaaaaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaiadp
cpaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaabeaaaaaaaaamadpdcaaaaajicaabaaaaaaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaaadpdiaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaadkaabaaaaaaaaaaabjaaaaafecaabaaaaaaaaaaackaabaaa
aaaaaaaadiaaaaahccaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaa
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaaacaaaaaacpaaaaafbcaabaaa
aaaaaaaaakaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaamnmmmmdobjaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaadcaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaamnmmemlpabeaaaaaaaaaiadp
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaabjaaaaaf
bcaabaaaaaaaaaaaakaabaaaaaaaaaaadcaaaaakccaabaaaaaaaaaaackaabaia
ebaaaaaaabaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaiadpdiaaaaahecaabaaa
aaaaaaaabkaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaa
ckaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaadkbabaaaacaaaaaaaaaaaaaiecaabaaaaaaaaaaaakaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpdcaaaaajbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaaaaaaaaadbaaaaahccaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaaadpbpaaaeadbkaabaaaaaaaaaaaaaaaaaahiccabaaa
aaaaaaaaakaabaaaaaaaaaaaakaabaaaaaaaaaaadgaaaaafhccabaaaaaaaaaaa
egbcbaaaacaaaaaadoaaaaabbcaaaaabaaaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaaalpaaaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
akaabaaaaaaaaaaaaaaaaaalocaabaaaaaaaaaaaagbjbaiaebaaaaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaiadpaaaaiadpaaaaiadpdcaaaaajhccabaaaaaaaaaaa
agaabaaaaaaaaaaajgahbaaaaaaaaaaaegbcbaaaacaaaaaadgaaaaaficcabaaa
aaaaaaaaabeaaaaaaaaaiadpdoaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}