// Compiled shader for all platforms, uncompressed size: 38.8KB

Shader "Futile/LevelMelt2" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 109 math, 5 texture
 //       gles3 : 109 math, 5 texture
 //   glesdesktop : 109 math, 5 texture
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 64 math, 3 texture, 1 branch
 //        d3d9 : 129 math, 3 texture, 5 branch
 //       metal : 109 math, 5 texture
 //      opengl : 123 math, 5 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 64 math, 3 textures, 1 branches
SetTexture 0 [_NoiseTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 80
Float 16 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
Vector 56 [_realRenderScreenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedjpbgjnfekoiogfbdmljpgnhljkkdmolgabaaaaaaleakaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapajaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcmaajaaaaeaaaaaaahaacaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaa
ffffaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadjcbabaaaacaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacahaaaaaadiaaaaaihcaabaaaaaaaaaaaogbkbaaa
abaaaaaaegiccaaaaaaaaaaaadaaaaaaebaaaaafhcaabaaaaaaaaaaaegacbaaa
aaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaa
adaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaa
aaaaaaaaacaaaaaaaaaaaaakdcaabaaaabaaaaaaegiacaiaebaaaaaaaaaaaaaa
acaaaaaaogikcaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaaabaaaaaaegaabaaa
aaaaaaaaegaabaaaabaaaaaaaaaaaaaibcaabaaaaaaaaaaadkbabaiaebaaaaaa
abaaaaaaabeaaaaaaaaaiadpdiaaaaahccaabaaaaaaaaaaabkaabaaaabaaaaaa
abeaaaaailombaecdiaaaaaiicaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaa
abeaaaaapaifejdmdcaaaaajecaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaa
mnmmemdndkaabaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaigaabaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaajccaabaaaaaaaaaaaakaabaaa
abaaaaaaabeaaaaamdpfmiebbkaabaaaaaaaaaaadcaaaaakccaabaaaaaaaaaaa
akiacaaaaaaaaaaaabaaaaaaabeaaaaapplckdeabkaabaaaaaaaaaaaenaaaaag
ccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaajccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaapdcaabaaa
abaaaaaaagbabaaaacaaaaaaaceaaaaalmhebdlmaknhcdlnaaaaaaaaaaaaaaaa
aceaaaaaaknhcddmmnmmemdnaaaaaaaaaaaaaaaaaaaaaaahmcaabaaaabaaaaaa
agaebaaaabaaaaaaagaebaaaabaaaaaadcaaaaakicaabaaaaaaaaaaabkaabaaa
aaaaaaaackaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaadcaaaaajbcaabaaa
aaaaaaaadkaabaaaaaaaaaaadkbabaaaacaaaaaaakaabaaaaaaaaaaaaaaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaadpdiaaaaaibcaabaaa
aaaaaaaaakaabaaaaaaaaaaadkiacaaaaaaaaaaaadaaaaaaebaaaaafbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaaaaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaaadpaoaaaaaidcaabaaaacaaaaaacgakbaaaaaaaaaaaogikcaaa
aaaaaaaaadaaaaaaefaaaaajpcaabaaaadaaaaaaegaabaaaacaaaaaaeghobaaa
abaaaaaaaagabaaaaaaaaaaadgaaaaafpcaabaaaaeaaaaaaegaobaaaadaaaaaa
dgaaaaaffcaabaaaaaaaaaaaagabbaaaacaaaaaadgaaaaaficaabaaaaaaaaaaa
abeaaaaaabaaaaaadaaaaaabcbaaaaahbcaabaaaabaaaaaadkaabaaaaaaaaaaa
abeaaaaaaeaaaaaaadaaaeadakaabaaaabaaaaaaclaaaaafbcaabaaaabaaaaaa
dkaabaaaaaaaaaaadiaaaaahbcaabaaaabaaaaaabkaabaaaaaaaaaaaakaabaaa
abaaaaaadcaaaaakbcaabaaaabaaaaaaakaabaaaabaaaaaadkaabaaaabaaaaaa
bkaabaiaebaaaaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaa
dkbabaaaacaaaaaaabaaaaahecaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaa
abaaaaaacaaaaaahecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaabaaaaaa
dhaaaaajecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaaaaaialpabeaaaaa
aaaaiadpdcaaaaakbcaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaackaabaaa
abaaaaaackaabaaaaaaaaaaadiaaaaaiecaabaaaabaaaaaaakaabaaaaaaaaaaa
ckiacaaaaaaaaaaaadaaaaaaebaaaaafecaabaaaabaaaaaackaabaaaabaaaaaa
aaaaaaahecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaaaaaaadpdiaaaaai
bcaabaaaabaaaaaaakaabaaaabaaaaaadkiacaaaaaaaaaaaadaaaaaaebaaaaaf
bcaabaaaabaaaaaaakaabaaaabaaaaaaaaaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaaaadpaoaaaaaifcaabaaaaaaaaaaakgaibaaaabaaaaaa
kgilcaaaaaaaaaaaadaaaaaaefaaaaajpcaabaaaafaaaaaaigaabaaaaaaaaaaa
eghobaaaabaaaaaaaagabaaaaaaaaaaaaaaaaaaipcaabaaaafaaaaaaegaobaia
ebaaaaaaaeaaaaaaegaobaaaafaaaaaaaaaaaaahpcaabaaaagaaaaaaegaobaaa
aeaaaaaaegaobaaaaeaaaaaadcaaaaampcaabaaaaeaaaaaaegaobaaaafaaaaaa
aceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaadpegaobaaaagaaaaaaboaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaabaaaaaabgaaaaabdiaaaaak
pcaabaaaaaaaaaaaegaobaaaaeaaaaaaaceaaaaamnmmemdomnmmemdomnmmemdo
mnmmemdodcaaaabahcaabaaaabaaaaaaegacbaiaebaaaaaaaeaaaaaaaceaaaaa
mnmmemdomnmmemdomnmmemdoaaaaaaaaaceaaaaailgmahdpeioblkdohpgkdmdo
aaaaaaaaaaaaaaajbcaabaaaabaaaaaabkaabaiaibaaaaaaabaaaaaaakaabaia
ibaaaaaaabaaaaaaaaaaaaaibcaabaaaabaaaaaackaabaiaibaaaaaaabaaaaaa
akaabaaaabaaaaaadcaaaabadcaabaaaabaaaaaaagaabaiaebaaaaaaabaaaaaa
aceaaaaaklkkkkdoklkkkkdoaaaaaaaaaaaaaaaaaceaaaaaaaaaiadpaaaaeaea
aaaaaaaaaaaaaaaacpaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaadiaaaaah
bcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaacaebbjaaaaafbcaabaaa
abaaaaaaakaabaaaabaaaaaadcaaaaappcaabaaaacaaaaaaagaabaaaabaaaaaa
aceaaaaailgmihdpeiobdkdphpgklmdoaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaiadpaaaaaaakfcaabaaaabaaaaaapgbpbaaaacaaaaaaaceaaaaa
ggggcglpaaaaaaaaaaaaaalpaaaaaaaadeaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaagonldgeadcaaaaanpcaabaaaacaaaaaaegaobaiaebaaaaaaaeaaaaaa
aceaaaaamnmmemdomnmmemdomnmmemdomnmmemdoegaobaaaacaaaaaadcaaaaaj
pcaabaaaaaaaaaaaagaabaaaabaaaaaaegaobaaaacaaaaaaegaobaaaaaaaaaaa
aaaaaaahbcaabaaaabaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaaaaaaaaah
bcaabaaaabaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaadiaaaaakfcaabaaa
abaaaaaaagacbaaaabaaaaaaaceaaaaaklkkkkdoaaaaaaaaaaaagaeaaaaaaaaa
ddaaaaahecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaaaaaiadpdiaaaaah
icaabaaaabaaaaaackaabaaaabaaaaaackaabaaaabaaaaaadiaaaaahecaabaaa
abaaaaaadkaabaaaabaaaaaackaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaa
ckaabaaaabaaaaaaakaabaaaabaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaa
abaaaaaabkaabaaaabaaaaaaabeaaaaaaaaaiadpdiaaaaahpccabaaaaaaaaaaa
egaobaaaaaaaaaaaagaabaaaabaaaaaadoaaaaab"
}




}
 }
}
}