// Compiled shader for all platforms, uncompressed size: 45.4KB

Shader "Futile/UnderWaterLight" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 128 math, 5 texture, 6 branch
 //       gles3 : 128 math, 5 texture, 6 branch
 //   glesdesktop : 128 math, 5 texture, 6 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 109 math, 5 texture, 1 branch
 //        d3d9 : 201 math, 5 texture, 1 branch
 //       metal : 128 math, 5 texture, 6 branch
 //      opengl : 153 math, 5 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 109 math, 5 textures, 1 branches
SetTexture 0 [_NoiseTex] 2D 2
SetTexture 1 [_LevelTex] 2D 1
SetTexture 2 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 80
Float 20 [_RAIN]
Vector 32 [_spriteRect]
Vector 48 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedpkdimjpopekdakioejcbkmhlgnaniofaabaaaaaadibaaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefceeapaaaaeaaaaaaanbadaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacagaaaaaadiaaaaaidcaabaaa
aaaaaaaaogbkbaaaabaaaaaaegiacaaaaaaaaaaaadaaaaaaebaaaaafdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaadaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaadiaaaaakmcaabaaaaaaaaaaa
agaebaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaajkjjjjdpjkjjjjdpefaaaaaj
pcaabaaaabaaaaaaogakbaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaa
dcaaaaakecaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaeaeabkiacaaa
aaaaaaaaabaaaaaadiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
mdpfmieaenaaaaagecaabaaaaaaaaaaaaanaaaaackaabaaaaaaaaaaadcaaaaaj
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadp
dcaaaaajecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaagpbciddlabeaaaaa
gpbcadllcpaaaaaficaabaaaaaaaaaaabkbabaaaabaaaaaadiaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaeiedbjaaaaaficaabaaaaaaaaaaa
dkaabaaaaaaaaaaadcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaajiebabeaaaaaaaaaiadpdiaaaaahecaabaaaaaaaaaaadkaabaaaaaaaaaaa
ckaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaabkbabaaaabaaaaaabkbabaaa
abaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaadkaabaaaaaaaaaaa
diaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaai
icaabaaaaaaaaaaadkaabaaaaaaaaaaabkiacaaaaaaaaaaaadaaaaaadiaaaaai
ecaabaaaaaaaaaaackaabaaaaaaaaaaaakiacaaaaaaaaaaaadaaaaaaebaaaaaf
ecaabaaaaaaaaaaackaabaaaaaaaaaaaaoaaaaaibcaabaaaabaaaaaackaabaaa
aaaaaaaaakiacaaaaaaaaaaaadaaaaaadiaaaaahecaabaaaaaaaaaaadkaabaaa
aaaaaaaaabeaaaaaaknhkdlmebaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaa
aoaaaaaiccaabaaaabaaaaaackaabaaaaaaaaaaabkiacaaaaaaaaaaaadaaaaaa
aaaaaaahmcaabaaaaaaaaaaaagaebaaaaaaaaaaaagaebaaaabaaaaaaefaaaaaj
pcaabaaaabaaaaaaogakbaaaaaaaaaaaeghobaaaabaaaaaaaagabaaaabaaaaaa
dcaaaaajecaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaa
aaaaialpdiaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaijiiaidn
bnaaaaaiicaabaaaaaaaaaaackaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaa
bkaaaaagecaabaaaaaaaaaaackaabaiaibaaaaaaaaaaaaaadhaaaaakecaabaaa
aaaaaaaadkaabaaaaaaaaaaackaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaa
biaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadp
aaaaiadpaaaaaaaaabaaaaahicaabaaaaaaaaaaabkaabaaaabaaaaaaakaabaaa
abaaaaaaabaaaaahicaabaaaaaaaaaaackaabaaaabaaaaaadkaabaaaaaaaaaaa
dhaaaaajecaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaiadpckaabaaa
aaaaaaaadbaaaaahicaabaaaaaaaaaaaabeaaaaamnmmemdockaabaaaaaaaaaaa
dcaaaaapdcaabaaaabaaaaaaogbkbaaaabaaaaaaaceaaaaaaaaaiadpaaaaialp
aaaaaaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaaefaaaaaj
pcaabaaaabaaaaaaegaabaaaabaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaa
bpaaaeaddkaabaaaaaaaaaaadbaaaaahicaabaaaaaaaaaaaabeaaaaaibiaiadl
akaabaaaabaaaaaadjaaaaakdcaabaaaabaaaaaajgafbaaaabaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahicaabaaaaaaaaaaadkaabaaa
aaaaaaaaakaabaaaabaaaaaadmaaaaahicaabaaaaaaaaaaabkaabaaaabaaaaaa
dkaabaaaaaaaaaaadhaaaaajecaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
mnmmemdockaabaaaaaaaaaaabfaaaaabaaaaaaakdcaabaaaabaaaaaaegbabaaa
abaaaaaaaceaaaaaaaaaaalpaaaaaalpaaaaaaaaaaaaaaaaapaaaaahicaabaaa
aaaaaaaaegaabaaaabaaaaaaegaabaaaabaaaaaaeeaaaaafecaabaaaabaaaaaa
dkaabaaaaaaaaaaadiaaaaahdcaabaaaabaaaaaakgakbaaaabaaaaaaegaabaaa
abaaaaaaelaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaaaaaaaahicaabaaa
aaaaaaaadkaabaaaaaaaaaaadkaabaaaaaaaaaaaddaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahmcaabaaaabaaaaaaagaebaaa
abaaaaaapgapbaaaaaaaaaaadcaaaaamdcaabaaaaaaaaaaaogakbaaaabaaaaaa
aceaaaaaaknhkddmaknhkddmaaaaaaaaaaaaaaaaegaabaaaaaaaaaaadbaaaaah
ecaabaaaabaaaaaackaabaaaaaaaaaaaabeaaaaamnmmemdodiaaaaahicaabaaa
abaaaaaackaabaaaaaaaaaaaabeaaaaaklkkkkdodcaaaaakbcaabaaaacaaaaaa
ckaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaakaeaabeaaaaaaaaaiadpcpaaaaaf
bcaabaaaacaaaaaaakaabaaaacaaaaaadiaaaaahbcaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaddddlddobjaaaaafbcaabaaaacaaaaaaakaabaaaacaaaaaa
aaaaaaahccaabaaaacaaaaaackaabaaaaaaaaaaaabeaaaaamnmmemlodicaaaah
ccaabaaaacaaaaaabkaabaaaacaaaaaaabeaaaaaggggkgdpdhaaaaajecaabaaa
abaaaaaackaabaaaabaaaaaaakaabaaaacaaaaaabkaabaaaacaaaaaaaaaaaaai
ecaabaaaabaaaaaackaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadpdcaaaaaj
bcaabaaaacaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaadpdkaabaaaaaaaaaaa
ddaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaaaaaaiadpdcaaaaak
bcaabaaaacaaaaaaakaabaiaebaaaaaaacaaaaaaakaabaaaacaaaaaaabeaaaaa
aaaaiadpcpaaaaafbcaabaaaacaaaaaaakaabaaaacaaaaaadiaaaaahbcaabaaa
acaaaaaaakaabaaaacaaaaaaabeaaaaaaaaagaeabjaaaaafbcaabaaaacaaaaaa
akaabaaaacaaaaaadiaaaaahecaabaaaabaaaaaackaabaaaabaaaaaaakaabaaa
acaaaaaaaaaaaaaldcaabaaaacaaaaaaegaabaiaebaaaaaaaaaaaaaaaceaaaaa
aaaaaadpaaaaaadpaaaaaaaaaaaaaaaadcaaaaajdcaabaaaacaaaaaapgapbaaa
abaaaaaaegaabaaaacaaaaaaegaabaaaaaaaaaaadiaaaaahicaabaaaabaaaaaa
akaabaaaacaaaaaaabeaaaaaggggageadcaaaaajbcaabaaaadaaaaaackaabaaa
aaaaaaaaabeaaaaamnmmmmdndkaabaaaabaaaaaadiaaaaalfcaabaaaacaaaaaa
fgifcaaaaaaaaaaaabaaaaaaaceaaaaaaaaamaeaaaaaaaaamnmmcmeaaaaaaaaa
diaaaaakhcaabaaaaeaaaaaakgakbaaaaaaaaaaaaceaaaaamnmmemdoaaaaaado
klkkckdoaaaaaaaadcaaaaanmcaabaaaadaaaaaafgifcaaaaaaaaaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaamnmmmmdndnakfhloagaebaaaaeaaaaaadcaaaaaj
ccaabaaaadaaaaaabkaabaaaacaaaaaaabeaaaaaggggageackaabaaaadaaaaaa
efaaaaajpcaabaaaafaaaaaaegaabaaaadaaaaaaeghobaaaaaaaaaaaaagabaaa
acaaaaaadcaaaaajicaabaaaabaaaaaaakaabaaaafaaaaaaabeaaaaaaaaaoaea
akaabaaaacaaaaaadiaaaaaklcaabaaaabaaaaaaegambaaaabaaaaaaaceaaaaa
jkjjbjdojkjjbjdoaaaaaaaamdpfmieaenaaaaagicaabaaaabaaaaaaaanaaaaa
dkaabaaaabaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
aaaaaadpabeaaaaaaaaaaadpaaaaaaaibcaabaaaacaaaaaadkaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpcpaaaaafbcaabaaaacaaaaaaakaabaaaacaaaaaa
diaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaajkjjnjdpbjaaaaaf
bcaabaaaacaaaaaaakaabaaaacaaaaaadcaaaaajdcaabaaaaaaaaaaaegaabaaa
abaaaaaaagaabaaaacaaaaaaegaabaaaaaaaaaaaaaaaaaaldcaabaaaabaaaaaa
egaabaiaebaaaaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaaaaaaaaaaaa
dcaaaaajdcaabaaaaaaaaaaaigaabaaaaeaaaaaaegaabaaaabaaaaaaegaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaggggkgdp
dcaaaaajbcaabaaaabaaaaaackaabaaaaaaaaaaaabeaaaaacfejbcdoakaabaaa
aaaaaaaadcaaaaajccaabaaaabaaaaaabkaabaaaaaaaaaaaabeaaaaaggggkgdp
dkaabaaaadaaaaaaefaaaaajpcaabaaaadaaaaaaegaabaaaabaaaaaaeghobaaa
aaaaaaaaaagabaaaacaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaadaaaaaa
abeaaaaafmipmkeackaabaaaacaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaamdpfmieaenaaaaagbcaabaaaaaaaaaaaaanaaaaaakaabaaa
aaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaadp
abeaaaaaaaaaaadpdeaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaa
abaaaaaacpaaaaafccaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaadmecbjaaaaafccaabaaaaaaaaaaa
bkaabaaaaaaaaaaabnaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
mnmmemdpdcaaaaapdcaabaaaabaaaaaapgapbaaaaaaaaaaaaceaaaaamnmmmmdo
aaaaialoaaaaaaaaaaaaaaaaaceaaaaajkjjbjdpaaaaeadpaaaaaaaaaaaaaaaa
cpaaaaafecaabaaaaaaaaaaackaabaaaabaaaaaadiaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaabaaaaaabjaaaaafecaabaaaaaaaaaaackaabaaa
aaaaaaaadhaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaackaabaaaaaaaaaaa
ckaabaaaabaaaaaacpaaaaafecaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaamadpbjaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaaaaaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaialpdcaaaaajbcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaaaiadpdiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
bkaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkbabaaa
acaaaaaadiaaaaahiccabaaaaaaaaaaabkaabaaaabaaaaaaakaabaaaaaaaaaaa
dgaaaaafhccabaaaaaaaaaaaegbcbaaaacaaaaaadoaaaaab"
}




}
 }
}
}