// Compiled shader for all platforms, uncompressed size: 42.2KB

Shader "Futile/Projection" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 111 math, 5 texture, 11 branch
 //       gles3 : 111 math, 5 texture, 11 branch
 //   glesdesktop : 111 math, 5 texture, 11 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 61 math, 5 texture, 7 branch
 //        d3d9 : 127 math, 5 texture, 5 branch
 //       metal : 111 math, 5 texture, 11 branch
 //      opengl : 142 math, 5 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 112
Vector 96 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedpenjlbbpmejpnecgfecobllklbmkepmkabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaahaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaagaaaaaa
ogikcaaaaaaaaaaaagaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 61 math, 5 textures, 7 branches
SetTexture 0 [_LevelTex] 2D 2
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_MainTex] 2D 1
ConstBuffer "$Globals" 112
Vector 32 [_lightDirAndPixelSize]
Vector 64 [_spriteRect]
Vector 80 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedjcplkdddghlajopbhjalmgnmpifgdkfoabaaaaaajealaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapalaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefckaakaaaaeaaaaaaakiacaaaafjaaaaae
egiocaaaaaaaaaaaagaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadlcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacagaaaaaadiaaaaaidcaabaaa
aaaaaaaaogbkbaaaabaaaaaaegiacaaaaaaaaaaaafaaaaaaebaaaaafdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaafaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaiaebaaaaaaaaaaaaaaaeaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaaeaaaaaakgiocaaaaaaaaaaaaeaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaa
egaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadcaaaaajecaabaaa
aaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaa
aaaaaaaackaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaabkaaaaagecaabaaa
aaaaaaaackaabaiaibaaaaaaaaaaaaaadhaaaaakecaabaaaaaaaaaaadkaabaaa
aaaaaaaackaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaadiaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaapaebblaaaaafbcaabaaaacaaaaaa
ckaabaaaaaaaaaaadiaaaaakdcaabaaaadaaaaaaogikcaaaaaaaaaaaacaaaaaa
egiacaiaebaaaaaaaaaaaaaaacaaaaaaboaaaaahicaabaaaaaaaaaaaakaabaaa
acaaaaaaabeaaaaaplppppppclaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaa
dcaaaaajbcaabaaaaeaaaaaaakaabaaaadaaaaaadkaabaaaaaaaaaaackbabaaa
abaaaaaaaaaaaaaiicaabaaaabaaaaaadkbabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaiadpdcaaaaajccaabaaaaeaaaaaabkaabaaaadaaaaaadkaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaakdcaabaaaadaaaaaaegaabaaaaeaaaaaaaceaaaaa
aaaaaalpjkjjjjloaaaaaaaaaaaaaaaaedaaaaafecaabaaaaaaaaaaackaabaaa
aaaaaaaaaaaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaakama
dcaaaaajecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaadfhiaodlabeaaaaa
aaaaiadpdcaaaaamdcaabaaaadaaaaaaegaabaaaadaaaaaakgakbaaaaaaaaaaa
aceaaaaaaaaaaadpjkjjjjdoaaaaaaaaaaaaaaaadcaaaaapmcaabaaaadaaaaaa
kgbobaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaialpaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaiadpefaaaaajpcaabaaaaeaaaaaaogakbaaa
adaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaabnaaaaahecaabaaaaaaaaaaa
abeaaaaaibiaiadlakaabaaaaeaaaaaabiaaaaakmcaabaaaadaaaaaafgajbaaa
aeaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaackaabaaaadaaaaaaabaaaaahecaabaaaaaaaaaaa
dkaabaaaadaaaaaackaabaaaaaaaaaaaccaaaaakmcaabaaaadaaaaaaagaabaaa
acaaaaaaaceaaaaaaaaaaaaaaaaaaaaaabaaaaaaafaaaaaadmaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaadaaaaaadiaaaaajdcaabaaaaeaaaaaa
ogikcaaaaaaaaaaaacaaaaaaegiacaaaaaaaaaaaacaaaaaaefaaaaajpcaabaaa
afaaaaaaegaabaaaadaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaadcaaaaak
bcaabaaaadaaaaaaakaabaiaebaaaaaaaeaaaaaadkaabaaaaaaaaaaaakaabaaa
aaaaaaaadcaaaaajccaabaaaadaaaaaabkaabaaaaeaaaaaadkaabaaaaaaaaaaa
bkaabaaaaaaaaaaaefaaaaajpcaabaaaaeaaaaaaegaabaaaadaaaaaaeghobaaa
aaaaaaaaaagabaaaacaaaaaabpaaaeadckaabaaaaaaaaaaabiaaaaakhcaabaaa
aaaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
abaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaah
bcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaabnaaaaahccaabaaa
aaaaaaaaabeaaaaalfleledoakaabaaaabaaaaaadmaaaaahccaabaaaacaaaaaa
akaabaaaaaaaaaaabkaabaaaaaaaaaaaccaaaaahbcaabaaaaaaaaaaaabeaaaaa
afaaaaaaakaabaaaacaaaaaabpaaaeadakaabaaaaaaaaaaadbaaaaahbcaabaaa
aaaaaaaaabeaaaaaibiaiadlakaabaaaafaaaaaadjaaaaakgcaabaaaaaaaaaaa
fgagbaaaafaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaah
bcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaahbcaabaaa
aaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaahccaabaaaacaaaaaa
bkaabaaaacaaaaaaakaabaaaaaaaaaaabfaaaaabbcaaaaabdjaaaaakhcaabaaa
aaaaaaaaegacbaaaaeaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaa
dmaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaadmaaaaah
bcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaadcaaaaajccaabaaa
aaaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiecaabaaa
aaaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaabkaaaaagccaabaaa
aaaaaaaabkaabaiaibaaaaaaaaaaaaaadhaaaaakccaabaaaaaaaaaaackaabaaa
aaaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaadiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaapaebblaaaaafccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaccaaaaahecaabaaaacaaaaaabkaabaaaaaaaaaaaabeaaaaa
agaaaaaadgaaaaaikcaabaaaacaaaaaaaceaaaaaaaaaaaaaafaaaaaaaaaaaaaa
aaaaaaaadhaaaaajdcaabaaaacaaaaaaagaabaaaaaaaaaaajgafbaaaacaaaaaa
mgaabaaaacaaaaaabfaaaaabboaaaaahbcaabaaaaaaaaaaaakaabaaaacaaaaaa
abeaaaaaplppppppclaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaai
dcaabaaaaaaaaaaaagaabaaaaaaaaaaaogikcaaaaaaaaaaaacaaaaaadiaaaaaj
dcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaaaaaaaaaaacaaaaaa
aoaaaaalmcaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadp
kgiocaaaaaaaaaaaacaaaaaadcaaaaapdcaabaaaabaaaaaaegbabaaaacaaaaaa
aceaaaaaaamahjeeaamahjeeaaaaaaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadp
aaaaaaaaaaaaaaaaaoaaaaahmcaabaaaaaaaaaaakgaobaaaaaaaaaaaagaebaaa
abaaaaaadiaaaaahdcaabaaaaaaaaaaaogakbaaaaaaaaaaaegaabaaaaaaaaaaa
dgaaaaagecaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaaaaaaaaahdcaabaaa
aaaaaaaaigaabaaaaaaaaaaaegbabaaaabaaaaaaefaaaaajpcaabaaaaaaaaaaa
egaabaaaaaaaaaaaeghobaaaacaaaaaaaagabaaaabaaaaaabpaaaeadckaabaaa
adaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadoaaaaabbfaaaaabbpaaaeadbkaabaaaacaaaaaadgaaaaaipccabaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaab
diaaaaahiccabaaaaaaaaaaadkaabaaaaaaaaaaadkbabaaaacaaaaaadgaaaaaf
hccabaaaaaaaaaaaegacbaaaaaaaaaaadoaaaaab"
}




}
 }
}
}