// Compiled shader for all platforms, uncompressed size: 36.7KB

Shader "Futile/HologramImage" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 83 math, 3 texture, 7 branch
 //       gles3 : 83 math, 3 texture, 7 branch
 //   glesdesktop : 83 math, 3 texture, 7 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 64 math, 3 texture, 5 branch
 //        d3d9 : 123 math, 3 texture
 //       metal : 83 math, 3 texture, 7 branch
 //      opengl : 120 math, 3 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 112
Vector 96 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedpenjlbbpmejpnecgfecobllklbmkepmkabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaahaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaagaaaaaa
ogikcaaaaaaaaaaaagaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 64 math, 3 textures, 5 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_NoiseTex2] 2D 2
ConstBuffer "$Globals" 112
Float 48 [_RAIN]
Vector 64 [_spriteRect]
Vector 80 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefiecedamflaglechphgiljcdcmemlpmfkicnomabaaaaaadaamaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcdmalaaaaeaaaaaaampacaaaafjaaaaae
egiocaaaaaaaaaaaagaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadpcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacafaaaaaadiaaaaaidcaabaaa
aaaaaaaaogbkbaaaabaaaaaaegiacaaaaaaaaaaaafaaaaaaebaaaaafdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaafaaaaaaaaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaiaebaaaaaaaaaaaaaaaeaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaia
ebaaaaaaaaaaaaaaaeaaaaaakgiocaaaaaaaaaaaaeaaaaaaaoaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaaaaaaaakmcaabaaaaaaaaaaa
agbebaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaalpaaaaaalpapaaaaah
ecaabaaaaaaaaaaaogakbaaaaaaaaaaaogakbaaaaaaaaaaaelaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaaaaaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
ckaabaaaaaaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
aaaaiadpdiaaaaakhcaabaaaabaaaaaaegbcbaaaacaaaaaaaceaaaaaaaaaaadp
aaaaaadpaaaamiebaaaaaaaadcaaaaamdcaabaaaabaaaaaaegbabaaaabaaaaaa
aceaaaaaaaaaaadpaaaaaadpaaaaaaaaaaaaaaaaegaabaaaabaaaaaaaaaaaaal
dcaabaaaacaaaaaaegbabaiaebaaaaaaabaaaaaaaceaaaaaaaaaaadpaaaaaadp
aaaaaaaaaaaaaaaadiaaaaakdcaabaaaacaaaaaaegaabaaaacaaaaaaaceaaaaa
mnmmemdomnmmemdoaaaaaaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaackaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
dkaabaaaaaaaaaaadcaaaaajdcaabaaaabaaaaaaegaabaaaacaaaaaapgapbaaa
aaaaaaaaegaabaaaabaaaaaaeaaaaaaficaabaaaaaaaaaaackaabaaaabaaaaaa
blaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaabaaaaahecaabaaaabaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaaaiaceaaaaaiicaabaaaabaaaaaadkaabaaa
aaaaaaaadkaabaiaebaaaaaaaaaaaaaaeoaaaaajbcaabaaaacaaaaaabcaabaaa
adaaaaaadkaabaaaabaaaaaaabeaaaaaafaaaaaaciaaaaaficaabaaaabaaaaaa
akaabaaaadaaaaaadhaaaaajecaabaaaabaaaaaackaabaaaabaaaaaadkaabaaa
abaaaaaaakaabaaaadaaaaaaclaaaaafecaabaaaabaaaaaackaabaaaabaaaaaa
diaaaaakdcaabaaaabaaaaaaegaabaaaabaaaaaaaceaaaaamnmmemdomnmmemdo
aaaaaaaaaaaaaaaadcaaaaajbcaabaaaadaaaaaackaabaaaabaaaaaaabeaaaaa
mnmmemdoakaabaaaabaaaaaafhaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaafaaaaaaciaaaaafbcaabaaaabaaaaaaakaabaaaacaaaaaaabaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaaiadhaaaaajicaabaaa
aaaaaaaadkaabaaaaaaaaaaaakaabaaaabaaaaaaakaabaaaacaaaaaaclaaaaaf
icaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaajccaabaaaadaaaaaadkaabaaa
aaaaaaaaabeaaaaamnmmemdobkaabaaaabaaaaaaefaaaaajpcaabaaaabaaaaaa
egaabaaaadaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaadcaaaaapdcaabaaa
acaaaaaaogbkbaaaabaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaaaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaaefaaaaajpcaabaaaacaaaaaa
egaabaaaacaaaaaaeghobaaaabaaaaaaaagabaaaaaaaaaaadiaaaaakdcaabaaa
adaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaiaeaaaaaaaebaaaaaaaaaaaaaaaa
dcaaaaalecaabaaaadaaaaaaakiacaiaebaaaaaaaaaaaaaaadaaaaaaabeaaaaa
aaaacaebbkaabaaaadaaaaaaefaaaaajpcaabaaaadaaaaaaigaabaaaadaaaaaa
eghobaaaacaaaaaaaagabaaaacaaaaaabnaaaaahbcaabaaaaaaaaaaackaabaaa
aaaaaaaaabeaaaaaaaaaiadpbpaaaeadakaabaaaaaaaaaaadgaaaaaipccabaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaab
dcaaaaalbcaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaaadaaaaaaabeaaaaa
jkjjbjdobkaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaamiedeaaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkkkdobnaaaaaiccaabaaa
aaaaaaaaakaabaaaaaaaaaaaakaabaiaebaaaaaaaaaaaaaabkaaaaagbcaabaaa
aaaaaaaaakaabaiaibaaaaaaaaaaaaaadhaaaaakbcaabaaaaaaaaaaabkaabaaa
aaaaaaaaakaabaaaaaaaaaaaakaabaiaebaaaaaaaaaaaaaabiaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaa
dkbabaaaacaaaaaaabeaaaaaaaaaaadpdcaaaaapgcaabaaaadaaaaaapgbpbaaa
acaaaaaaaceaaaaaaaaaaaaamnmmemloaaaabiebaaaaaaaaaceaaaaaaaaaaaaa
aaaaiadoaaaaaadpaaaaaaaaaaaaaaahicaabaaaaaaaaaaabkaabaaaadaaaaaa
akaabaaaadaaaaaadhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaa
aaaaaaaaakaabaaaadaaaaaaaaaaaaaiicaabaaaaaaaaaaackaabaiaebaaaaaa
adaaaaaaabeaaaaaaaaaaadpdcaaaaajecaabaaaaaaaaaaackaabaaaaaaaaaaa
dkaabaaaaaaaaaaackaabaaaadaaaaaacpaaaaafbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaa
bjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadbaaaaahbcaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaadgaaaaai
pccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaab
bcaaaaabdbaaaaakhcaabaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaegacbaaaabaaaaaadhaaaaajbcaabaaaadaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaiadpakaabaaaabaaaaaaaaaaaaaljcaabaaaaaaaaaaafgajbaia
ebaaaaaaabaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaiadpdcaaaaba
jcaabaaaaaaaaaaaagambaiaebaaaaaaaaaaaaaaaceaaaaammmmemdoaaaaaaaa
aaaaaaaadddddddpaceaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaiadpdiaaaaak
dcaabaaaaeaaaaaajgafbaaaabaaaaaaaceaaaaamnmmemdpjkjjjjdoaaaaaaaa
aaaaaaaadhaaaaajgcaabaaaadaaaaaafgagbaaaaaaaaaaaagadbaaaaaaaaaaa
agabbaaaaeaaaaaadcaaaaajbcaabaaaaaaaaaaadkbabaaaacaaaaaaabeaaaaa
koehobloabeaaaaaaaaaiadpdgaaaaaficaabaaaadaaaaaadkaabaaaabaaaaaa
aaaaaaaipcaabaaaadaaaaaaegaobaiaebaaaaaaabaaaaaaegaobaaaadaaaaaa
dcaaaaajpcaabaaaaaaaaaaaagaabaaaaaaaaaaaegaobaaaadaaaaaaegaobaaa
abaaaaaaaaaaaaalhcaabaaaabaaaaaaegacbaiaebaaaaaaaaaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaaaaaaaaaaaalhcaabaaaacaaaaaaegacbaia
ebaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadcaaaaan
hcaabaaaaaaaaaaaegacbaiaebaaaaaaabaaaaaaegacbaaaacaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaaaaaaaaaaaaibcaabaaaabaaaaaadkbabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaiadpcpaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaamadp
bjaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaaaaaaaaalpcaabaaaacaaaaaa
egaobaiaebaaaaaaaaaaaaaaaceaaaaaaaaaiadpmnmmemdpjkjjjjdoaaaaiadp
dcaaaaajpccabaaaaaaaaaaaagaabaaaabaaaaaaegaobaaaacaaaaaaegaobaaa
aaaaaaaadoaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}