// Compiled shader for all platforms, uncompressed size: 51.6KB

Shader "Futile/LevelColorDark" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 5 math
 //        d3d9 : 5 math
 //        gles : 165 math, 10 texture, 15 branch
 //       gles3 : 165 math, 10 texture, 15 branch
 //   glesdesktop : 165 math, 10 texture, 15 branch
 //       metal : 3 math
 //      opengl : 5 math
 // Stats for Fragment shader:
 //       d3d11 : 87 math, 10 texture, 7 branch
 //        d3d9 : 182 math, 10 texture, 6 branch
 //       metal : 165 math, 10 texture, 15 branch
 //      opengl : 182 math, 10 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 96
Vector 80 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedgalfkkmeejbgnejmlejlkjffjjghdjkaabaaaaaacmacaaaaadaaaaaa
cmaaaaaakaaaaaaapiaaaaaaejfdeheogmaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaafjaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahaaaaaagaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apadaaaafaepfdejfeejepeoaaeoepfcenebemaafeeffiedepepfceeaaklklkl
epfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaeeaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
fdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieefccmabaaaa
eaaaabaaelaaaaaafjaaaaaeegiocaaaaaaaaaaaagaaaaaafjaaaaaeegiocaaa
abaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaacaaaaaa
ghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaal
dccabaaaabaaaaaaegbabaaaacaaaaaaegiacaaaaaaaaaaaafaaaaaaogikcaaa
aaaaaaaaafaaaaaadoaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 87 math, 10 textures, 7 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_NoiseTex] 2D 3
SetTexture 2 [_GrabTexture] 2D 0
SetTexture 3 [_PalTex] 2D 2
ConstBuffer "$Globals" 96
Float 20 [_RAIN]
Float 24 [_light]
Vector 32 [_spriteRect]
Vector 48 [_lightDirAndPixelSize]
BindCB  "$Globals" 0
"ps_4_0
eefiecedmdkodfgipinhlpifhblofmcpbkmkjlgdabaaaaaamabaaaaaadaaaaaa
cmaaaaaaieaaaaaaliaaaaaaejfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaeeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieefcaabaaaaa
eaaaaaaaaaaeaaaafjaaaaaeegiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaa
aaaaaaaafkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaad
aagabaaaadaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaa
abaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaafibiaaaeaahabaaa
adaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacakaaaaaaaaaaaaakdcaabaaaaaaaaaaaegiacaiaebaaaaaaaaaaaaaa
acaaaaaaogikcaaaaaaaaaaaacaaaaaadcaaaaakgcaabaaaaaaaaaaaagbbbaaa
abaaaaaaagabbaaaaaaaaaaaagibcaaaaaaaaaaaacaaaaaaefaaaaajpcaabaaa
abaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaabaaaaaabiaaaaak
hcaabaaaacaaaaaaegacbaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaaaaaabaaaaahicaabaaaabaaaaaabkaabaaaacaaaaaaakaabaaaacaaaaaa
abaaaaahicaabaaaabaaaaaackaabaaaacaaaaaadkaabaaaabaaaaaadiaaaaak
dcaabaaaabaaaaaaegaabaaaabaaaaaaaceaaaaaaaaahpedaaaahpedaaaaaaaa
aaaaaaaablaaaaafdcaabaaaacaaaaaaegaabaaaabaaaaaadiaaaaaibcaabaaa
abaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmmmdndcaaaaajbcaabaaa
abaaaaaaakbabaaaabaaaaaaabeaaaaaaaaaaadpakaabaaaabaaaaaaboaaaaak
hcaabaaaadaaaaaaagabbaaaacaaaaaaaceaaaaappppppppkgpppppppmpppppp
aaaaaaaaclaaaaafccaabaaaabaaaaaaakaabaaaadaaaaaadiaaaaahccaabaaa
abaaaaaabkaabaaaabaaaaaaabeaaaaaijiiaidnbnaaaaaiicaabaaaacaaaaaa
bkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaabkaaaaagccaabaaaabaaaaaa
bkaabaiaibaaaaaaabaaaaaadhaaaaakccaabaaaabaaaaaadkaabaaaacaaaaaa
bkaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaadcaaaaakbcaabaaaaeaaaaaa
bkaabaiaebaaaaaaabaaaaaaabeaaaaaomfblidnakaabaaaabaaaaaadcaaaaak
bcaabaaaabaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaaadpabeaaaaa
aaaaiadpdcaaaaakbcaabaaaabaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaa
mnmmemdoakaabaaaabaaaaaadcaaaaakccaabaaaaeaaaaaabkaabaiaebaaaaaa
abaaaaaaabeaaaaaomfblidnakaabaaaabaaaaaaefaaaaajpcaabaaaaeaaaaaa
egaabaaaaeaaaaaaeghobaaaabaaaaaaaagabaaaadaaaaaadcaaaaakbcaabaaa
abaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmmmdnakaabaaaaeaaaaaa
aaaaaaaibcaabaaaabaaaaaaakaabaaaabaaaaaabkbabaiaebaaaaaaabaaaaaa
bnaaaaaiccaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
bkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaadhaaaaakbcaabaaa
abaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaa
diaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaamdpfmieaenaaaaag
bcaabaaaabaaaaaaaanaaaaaakaabaaaabaaaaaadcaaaaajbcaabaaaabaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaaeaeaabeaaaaaaaaaaadpdccaaaalicaabaaa
adaaaaaackiacaiaebaaaaaaaaaaaaaaabaaaaaaabeaaaaaaaaaiaeaakaabaaa
abaaaaaaccaaaaakdcaabaaaabaaaaaaaceaaaaafkaaaaaaadaaaaaaaaaaaaaa
aaaaaaaaegaabaaaacaaaaaadgaaaaafecaabaaaacaaaaaaabeaaaaaaaaaiadp
dhaaaaajhcaabaaaacaaaaaaagabbaaaabaaaaaahgaobaaaadaaaaaacgajbaaa
acaaaaaaclaaaaafbcaabaaaabaaaaaabkaabaaaacaaaaaadiaaaaahbcaabaaa
abaaaaaaakaabaaaabaaaaaaabeaaaaaijiiaidnebaaaaafbcaabaaaabaaaaaa
akaabaaaabaaaaaablaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaaboaaaaah
ccaabaaaacaaaaaabkaabaaaacaaaaaaabeaaaaappppppppclaaaaafccaabaaa
acaaaaaabkaabaaaacaaaaaadiaaaaahccaabaaaacaaaaaabkaabaaaacaaaaaa
abeaaaaaijiiaidnbnaaaaaiicaabaaaacaaaaaabkaabaaaacaaaaaabkaabaia
ebaaaaaaacaaaaaabkaaaaagccaabaaaacaaaaaabkaabaiaibaaaaaaacaaaaaa
dhaaaaakccaabaaaacaaaaaadkaabaaaacaaaaaabkaabaaaacaaaaaabkaabaia
ebaaaaaaacaaaaaadiaaaaahccaabaaaacaaaaaabkaabaaaacaaaaaaabeaaaaa
aaaapaebblaaaaaficaabaaaacaaaaaabkaabaaaacaaaaaaedaaaaafccaabaaa
acaaaaaabkaabaaaacaaaaaadiaaaaakdcaabaaaadaaaaaaogikcaaaaaaaaaaa
adaaaaaaegiacaiaebaaaaaaaaaaaaaaadaaaaaaboaaaaahecaabaaaadaaaaaa
dkaabaaaacaaaaaaabeaaaaaplppppppclaaaaafecaabaaaadaaaaaackaabaaa
adaaaaaadiaaaaahdcaabaaaadaaaaaakgakbaaaadaaaaaaegaabaaaadaaaaaa
dcaaaaajbcaabaaaaeaaaaaaakaabaaaadaaaaaaabeaaaaajkjjjjdpbkaabaaa
aaaaaaaaaaaaaaaljcaabaaaaaaaaaaakgakbaiaebaaaaaaaaaaaaaaaceaaaaa
aaaaiadpaaaaaaaaaaaaaaaaaaaaiadpdcaaaaajccaabaaaaeaaaaaabkaabaaa
adaaaaaaabeaaaaajkjjjjdpakaabaaaaaaaaaaaefaaaaajpcaabaaaadaaaaaa
egaabaaaaeaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaadiaaaaahbcaabaaa
aaaaaaaabkaabaaaacaaaaaaabeaaaaaaaaaaadnboaaaaahbcaabaaaabaaaaaa
akaabaaaabaaaaaaabeaaaaaadaaaaaaclaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaaaaaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaadp
diaaaaahecaabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaadoefaaaaaj
pcaabaaaaeaaaaaaigaabaaaaaaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaa
aaaaaaahfcaabaaaaaaaaaaaagbbbaaaabaaaaaaagbbbaaaabaaaaaaefaaaaaj
pcaabaaaafaaaaaaigaabaaaaaaaaaaaeghobaaaabaaaaaaaagabaaaadaaaaaa
dcaaaaakbcaabaaaaaaaaaaaakaabaaaafaaaaaaabeaaaaaaaaaiaeabkiacaaa
aaaaaaaaabaaaaaadcaaaaajbcaabaaaaaaaaaaabkaabaaaacaaaaaaabeaaaaa
klkkkkdnakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaamdpfmieaenaaaaagbcaabaaaaaaaaaaaaanaaaaaakaabaaaaaaaaaaa
dcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaa
aaaaaadpdcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaamieb
abeaaaaaaaaalaeadiaaaaahbcaabaaaafaaaaaaakaabaaaaaaaaaaaabeaaaaa
aaaaaadndgaaaaafccaabaaaafaaaaaaabeaaaaaaaaafadpefaaaaajpcaabaaa
afaaaaaaegaabaaaafaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaacjaaaaah
bcaabaaaaaaaaaaackaabaaaacaaaaaaabeaaaaaabaaaaaaboaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaapoppppppclaaaaafbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaaaaaaaalfcaabaaaaaaaaaaaagaabaiaebaaaaaaaaaaaaaa
aceaaaaaaaaalaeaaaaaaaaaaaaajaeaaaaaaaaadiaaaaakdcaabaaaagaaaaaa
igaabaaaaaaaaaaaaceaaaaaaaaaaadoaaaaaadoaaaaaaaaaaaaaaaadgaaaaai
mcaabaaaagaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaahedpaaaahmdpefaaaaaj
pcaabaaaahaaaaaacgakbaaaagaaaaaaeghobaaaadaaaaaaaagabaaaacaaaaaa
efaaaaajpcaabaaaaiaaaaaaggakbaaaagaaaaaaeghobaaaadaaaaaaaagabaaa
acaaaaaaefaaaaajpcaabaaaagaaaaaahgapbaaaagaaaaaaeghobaaaadaaaaaa
aagabaaaacaaaaaabpaaaeaddkaabaaaabaaaaaadgaaaaaihccabaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaafbcaabaaaajaaaaaa
abeaaaaaaaaaiadpdgaaaaafbcaabaaaaaaaaaaaabeaaaaappppppppbcaaaaab
djaaaaahecaabaaaaaaaaaaaakaabaaaacaaaaaaabeaaaaaaaaaiadpccaaaaah
bcaabaaaaaaaaaaaabeaaaaaafaaaaaadkaabaaaacaaaaaaabaaaaahecaabaaa
aaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaabpaaaeadckaabaaaaaaaaaaa
djaaaaakhcaabaaaadaaaaaaegacbaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadmaaaaahecaabaaaaaaaaaaabkaabaaaadaaaaaaakaabaaa
adaaaaaadmaaaaahecaabaaaaaaaaaaackaabaaaadaaaaaackaabaaaaaaaaaaa
dhaaaaajbcaabaaaacaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaiadpakaabaaa
acaaaaaabfaaaaabaaaaaaalpcaabaaaadaaaaaaegaobaiaebaaaaaaaeaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaiadpdcaaaaajpcaabaaaadaaaaaa
agaabaaaacaaaaaaegaobaaaadaaaaaaegaobaaaaeaaaaaaabaaaaahecaabaaa
aaaaaaaabkaabaaaabaaaaaaabeaaaaamnmmmmdnaaaaaaaibcaabaaaabaaaaaa
akaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaabaaaaaaaaaaaaaipcaabaaaaeaaaaaaegaobaia
ebaaaaaaadaaaaaaegaobaaaafaaaaaadcaaaaajpcaabaaaadaaaaaakgakbaaa
aaaaaaaaegaobaaaaeaaaaaaegaobaaaadaaaaaaccaaaaahecaabaaaaaaaaaaa
abeaaaaaaaaaaaaackaabaaaacaaaaaaccaaaaahbcaabaaaabaaaaaackaabaaa
acaaaaaaabeaaaaaadaaaaaaabaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaabaaaaaabpaaaeadckaabaaaaaaaaaaaaaaaaaalpcaabaaaaeaaaaaa
egaobaiaebaaaaaaahaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaiadp
dcaaaaajpcaabaaaaeaaaaaaagaabaaaacaaaaaaegaobaaaaeaaaaaaegaobaaa
ahaaaaaaaaaaaaaipcaabaaaafaaaaaaegaobaiaebaaaaaaaiaaaaaaegaobaaa
agaaaaaadcaaaaajpcaabaaaafaaaaaaagaabaaaacaaaaaaegaobaaaafaaaaaa
egaobaaaaiaaaaaadiaaaaahecaabaaaaaaaaaaabkaabaaaacaaaaaaabeaaaaa
ijiiaidnaaaaaaaipcaabaaaafaaaaaaegaobaiaebaaaaaaaeaaaaaaegaobaaa
afaaaaaadcaaaaajpcaabaaaaeaaaaaakgakbaaaaaaaaaaaegaobaaaafaaaaaa
egaobaaaaeaaaaaaaaaaaaaipcaabaaaaeaaaaaaegaobaiaebaaaaaaadaaaaaa
egaobaaaaeaaaaaadcaaaaajpcaabaaaajaaaaaakgakbaaaabaaaaaadgajbaaa
aeaaaaaadgajbaaaadaaaaaadgaaaaafhccabaaaaaaaaaaajgahbaaaajaaaaaa
bcaaaaabcaaaaaahecaabaaaaaaaaaaackaabaaaacaaaaaaabeaaaaaadaaaaaa
aaaaaaalpcaabaaaacaaaaaaegaobaiaebaaaaaaadaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpdcaaaaajpcaabaaaabaaaaaakgakbaaaabaaaaaa
egaobaaaacaaaaaaegaobaaaadaaaaaadhaaaaajpcaabaaaajaaaaaakgakbaaa
aaaaaaaadgajbaaaabaaaaaadgajbaaaadaaaaaadgaaaaafhccabaaaaaaaaaaa
jgahbaaaajaaaaaabfaaaaabbfaaaaabefaaaaajpcaabaaaabaaaaaangafbaaa
aaaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaabpaaaeadakaabaaaaaaaaaaa
dbaaaaahbcaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaaabaaaaaadjaaaaak
gcaabaaaaaaaaaaafgagbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadmaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaa
dmaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaadhaaaaaj
iccabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaaaakaabaaaajaaaaaa
bcaaaaabdgaaaaaficcabaaaaaaaaaaaakaabaaaajaaaaaabfaaaaabdoaaaaab
"
}




}
 }
}
}