// Compiled shader for all platforms, uncompressed size: 48.6KB

Shader "Futile/SceneBlur" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 123 math, 10 texture, 5 branch
 //       gles3 : 123 math, 10 texture, 5 branch
 //   glesdesktop : 123 math, 10 texture, 5 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 56 math, 10 texture, 4 branch
 //        d3d9 : 99 math, 10 texture, 8 branch
 //       metal : 123 math, 10 texture, 5 branch
 //      opengl : 347 math, 42 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 64
Vector 48 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedobbfnlbielpdbdjbfkojielgagjmifddabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaaeaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaadaaaaaa
ogikcaaaaaaaaaaaadaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 56 math, 10 textures, 4 branches
SetTexture 0 [_MainTex] 2D 0
ConstBuffer "$Globals" 64
Float 16 [_BlurDepth]
Vector 20 [_MenuCamPos] 2
Float 28 [_BlurRange]
BindCB  "$Globals" 0
"ps_4_0
eefiecedkdgaehhkffdghjjjgegjblnmgbejjjcgabaaaaaaiialaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amaaaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcjeakaaaaeaaaaaaakfacaaaafjaaaaae
egiocaaaaaaaaaaaacaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacakaaaaaadiaaaaahbcaabaaaaaaaaaaa
ckbabaaaacaaaaaaabeaaaaaaaaacaebdcaaaaapgcaabaaaaaaaaaaaagbbbaaa
acaaaaaaaceaaaaaaaaaaaaaaaoakoeeaamaeheeaaaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaiadpaaaaaaaadiaaaaakdcaabaaaabaaaaaaegbabaaaabaaaaaa
aceaaaaaaaaaiadpaaaaaadpaaaaaaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaa
egaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaaiicaabaaa
aaaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadpdcaaaaajbcaabaaa
abaaaaaabkbabaaaabaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpaaaaaaaj
gcaabaaaabaaaaaaagbbbaiaebaaaaaaabaaaaaafgigcaaaaaaaaaaaabaaaaaa
diaaaaahgcaabaaaabaaaaaapgapbaaaaaaaaaaafgagbaaaabaaaaaadcaaaaak
ecaabaaaacaaaaaabkaabaiaebaaaaaaabaaaaaaabeaaaaamnmmmmdmakbabaaa
abaaaaaadcaaaaakbcaabaaaabaaaaaackaabaiaebaaaaaaabaaaaaaabeaaaaa
mnmmmmdmakaabaaaabaaaaaaaoaaaaakccaabaaaabaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaabeaaaaaaaaaaadpdeaaaaahccaabaaaacaaaaaaakaabaaa
abaaaaaabkaabaaaabaaaaaaefaaaaajpcaabaaaadaaaaaaggakbaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaoaaaaahccaabaaaaaaaaaaackaabaaa
aaaaaaaabkaabaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaadkaabaaaaaaaaaaa
abeaaaaaaaaaaaeaakaabaaaaaaaaaaaaaaaaaajbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaakiacaiaebaaaaaaaaaaaaaaabaaaaaadicaaaajbcaabaaaaaaaaaaa
akaabaiaibaaaaaaaaaaaaaadkiacaaaaaaaaaaaabaaaaaadiaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaagpbciddkdgaaaaafpcaabaaaaeaaaaaa
egaobaaaadaaaaaadgaaaaaimcaabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaiadpaaaaiadpdgaaaaaifcaabaaaabaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaaaaaaaaaaaaadaaaaaabcbaaaaahicaabaaaabaaaaaackaabaaaabaaaaaa
abeaaaaaafaaaaaaadaaaeaddkaabaaaabaaaaaaaaaaaaahbcaabaaaabaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaaiadpdiaaaaahbcaabaaaafaaaaaadkaabaaa
aaaaaaaaabeaaaaabpifgldpdiaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaa
akaabaaaabaaaaaadcaaaaakicaabaaaacaaaaaaakaabaiaebaaaaaaabaaaaaa
akaabaaaaaaaaaaabkaabaaaacaaaaaadbaaaaahccaabaaaafaaaaaabkaabaaa
abaaaaaadkaabaaaacaaaaaaefaaaaajpcaabaaaagaaaaaaogakbaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaabpaaaeadbkaabaaaafaaaaaadgaaaaaf
icaabaaaafaaaaaadkaabaaaagaaaaaadiaaaaahpcaabaaaagaaaaaaagambaaa
afaaaaaaegaobaaaagaaaaaadcaaaaajpcaabaaaaeaaaaaaegaobaaaagaaaaaa
pgadbaaaafaaaaaaegaobaaaaeaaaaaadcaaaaajecaabaaaaaaaaaaadkaabaaa
aaaaaaaaabeaaaaabpifgldpckaabaaaaaaaaaaabfaaaaabdcaaaaakbcaabaaa
acaaaaaadkaabaiaebaaaaaaabaaaaaabkaabaaaaaaaaaaackaabaaaacaaaaaa
efaaaaajpcaabaaaagaaaaaaegaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaadgaaaaaficaabaaaafaaaaaadkaabaaaagaaaaaadiaaaaahpcaabaaa
agaaaaaaagambaaaafaaaaaaegaobaaaagaaaaaadcaaaaajpcaabaaaagaaaaaa
egaobaaaagaaaaaapgadbaaaafaaaaaaegaobaaaaeaaaaaadcaaaaajbcaabaaa
acaaaaaadkaabaaaabaaaaaabkaabaaaaaaaaaaackaabaaaacaaaaaaefaaaaaj
pcaabaaaahaaaaaaegaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaa
dgaaaaafbcaabaaaaiaaaaaaakaabaaaafaaaaaadgaaaaaficaabaaaaiaaaaaa
dkaabaaaahaaaaaadiaaaaahpcaabaaaahaaaaaaegaobaaaahaaaaaaagambaaa
aiaaaaaadcaaaaajpcaabaaaagaaaaaaegaobaaaahaaaaaapgadbaaaaiaaaaaa
egaobaaaagaaaaaadcaaaaajicaabaaaacaaaaaaakaabaaaabaaaaaaakaabaaa
aaaaaaaabkaabaaaacaaaaaaefaaaaajpcaabaaaahaaaaaaogakbaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaadgaaaaaficaabaaaaiaaaaaadkaabaaa
ahaaaaaadiaaaaahpcaabaaaahaaaaaaegaobaaaahaaaaaaagambaaaaiaaaaaa
dcaaaaajpcaabaaaagaaaaaaegaobaaaahaaaaaapgadbaaaaiaaaaaaegaobaaa
agaaaaaadcaaaaajbcaabaaaacaaaaaadkaabaaaaaaaaaaaabeaaaaanhkddaea
ckaabaaaaaaaaaaadiaaaaahicaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaa
omfbdidpdcaaaaakecaabaaaahaaaaaadkaabaiaebaaaaaaabaaaaaaabeaaaaa
omfbdidpbkaabaaaacaaaaaadbaaaaahccaabaaaafaaaaaabkaabaaaabaaaaaa
ckaabaaaahaaaaaadcaaaaakccaabaaaahaaaaaadkaabaiaebaaaaaaacaaaaaa
bkaabaaaaaaaaaaackaabaaaacaaaaaaefaaaaajpcaabaaaajaaaaaajgafbaaa
ahaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaabpaaaeadbkaabaaaafaaaaaa
dgaaaaaficaabaaaaiaaaaaadkaabaaaajaaaaaadiaaaaahpcaabaaaajaaaaaa
agambaaaaiaaaaaaegaobaaaajaaaaaadcaaaaajpcaabaaaagaaaaaaegaobaaa
ajaaaaaapgadbaaaaiaaaaaaegaobaaaagaaaaaadcaaaaajbcaabaaaacaaaaaa
dkaabaaaaaaaaaaaabeaaaaabpifgldpakaabaaaacaaaaaabfaaaaabdcaaaaaj
bcaabaaaahaaaaaadkaabaaaacaaaaaabkaabaaaaaaaaaaackaabaaaacaaaaaa
efaaaaajpcaabaaaajaaaaaaigaabaaaahaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaabpaaaeadbkaabaaaafaaaaaadgaaaaaficaabaaaaiaaaaaadkaabaaa
ajaaaaaadiaaaaahpcaabaaaajaaaaaaagambaaaaiaaaaaaegaobaaaajaaaaaa
dcaaaaajpcaabaaaagaaaaaaegaobaaaajaaaaaapgadbaaaaiaaaaaaegaobaaa
agaaaaaadcaaaaajbcaabaaaacaaaaaadkaabaaaaaaaaaaaabeaaaaabpifgldp
akaabaaaacaaaaaabfaaaaabdcaaaaajicaabaaaahaaaaaadkaabaaaabaaaaaa
abeaaaaaomfbdidpbkaabaaaacaaaaaaefaaaaajpcaabaaaajaaaaaangafbaaa
ahaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaadgaaaaaficaabaaaaiaaaaaa
dkaabaaaajaaaaaadiaaaaahpcaabaaaajaaaaaaagambaaaaiaaaaaaegaobaaa
ajaaaaaadcaaaaajpcaabaaaagaaaaaaegaobaaaajaaaaaapgadbaaaaiaaaaaa
egaobaaaagaaaaaaefaaaaajpcaabaaaahaaaaaamgaabaaaahaaaaaaeghobaaa
aaaaaaaaaagabaaaaaaaaaaadgaaaaaficaabaaaaiaaaaaadkaabaaaahaaaaaa
diaaaaahpcaabaaaahaaaaaaegaobaaaahaaaaaaagambaaaaiaaaaaadcaaaaaj
pcaabaaaaeaaaaaaegaobaaaahaaaaaapgadbaaaaiaaaaaaegaobaaaagaaaaaa
dcaaaaajecaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaabpifoldpakaabaaa
acaaaaaaboaaaaahecaabaaaabaaaaaackaabaaaabaaaaaaabeaaaaaabaaaaaa
dgaaaaaficaabaaaaaaaaaaaakaabaaaafaaaaaabgaaaaabaoaaaaahpcaabaaa
aaaaaaaaegaobaaaaeaaaaaakgakbaaaaaaaaaaadiaaaaahiccabaaaaaaaaaaa
dkaabaaaaaaaaaaadkbabaaaacaaaaaadgaaaaafhccabaaaaaaaaaaaegacbaaa
aaaaaaaadoaaaaab"
}




}
 }
}
}