// Compiled shader for all platforms, uncompressed size: 45.5KB

Shader "Futile/DeathRain" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 125 math, 7 texture, 5 branch
 //       gles3 : 125 math, 7 texture, 5 branch
 //   glesdesktop : 125 math, 7 texture, 5 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 88 math, 7 texture
 //        d3d9 : 204 math, 7 texture
 //       metal : 125 math, 7 texture, 5 branch
 //      opengl : 142 math, 7 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 88 math, 7 textures
SetTexture 0 [_NoiseTex] 2D 2
SetTexture 1 [_MainTex] 2D 1
SetTexture 2 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 80
Float 16 [_rainDirection]
Float 20 [_rainEverywhere]
Float 24 [_rainIntensity]
Float 28 [_waterLevel]
Float 32 [_RAIN]
Vector 48 [_RainSpriteRect]
BindCB  "$Globals" 0
"ps_4_0
eefiecedpccmcdphadcpbkdieappdbjleicldkgmabaaaaaaoeaoaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcpaanaaaaeaaaaaaahmadaaaafjaaaaae
egiocaaaaaaaaaaaaeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacagaaaaaadiaaaaaibcaabaaaaaaaaaaabkbabaaaabaaaaaa
akiacaaaaaaaaaaaabaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaamnmmemdnakbabaaaabaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaaaganceeebaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
dcaaaaakccaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaadjlgjldmakiacaaa
aaaaaaaaacaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaa
adoilpdkdcaaaaajicaabaaaabaaaaaaakaabaaaaaaaaaaaabeaaaaaadoilpdk
abeaaaaaadoilpdkdgaaaaagecaabaaaabaaaaaaakiacaaaaaaaaaaaacaaaaaa
efaaaaajpcaabaaaacaaaaaaigaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaa
acaaaaaaaaaaaaakpcaabaaaadaaaaaaagaibaaaabaaaaaaaceaaaaaadoilpdk
adoilplkadoilplkaaaaaaaaefaaaaajpcaabaaaabaaaaaalgapbaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaacaaaaaaaaaaaaaibcaabaaaaaaaaaaabkaabaaa
aaaaaaaaakaabaiaebaaaaaaacaaaaaaenaaaaagbcaabaaaaaaaaaaaaanaaaaa
akaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaa
imoockehdcaaaaangcaabaaaaaaaaaaaagabbaaaadaaaaaaaceaaaaaaaaaaaaa
jflhepebjflhepebaaaaaaaaagiacaaaaaaaaaaaacaaaaaaefaaaaajpcaabaaa
acaaaaaaogakbaaaadaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaaaaaaaaai
ecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaiaebaaaaaaacaaaaaaaaaaaaai
ccaabaaaaaaaaaaaakaabaiaebaaaaaaabaaaaaabkaabaaaaaaaaaaaenaaaaag
ccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaimoockehbkaaaaafdcaabaaaaaaaaaaaegaabaaa
aaaaaaaaaaaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaa
enaaaaagccaabaaaaaaaaaaaaanaaaaackaabaaaaaaaaaaadiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaimoockehbkaaaaafccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaaaaaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaakdcaabaaaabaaaaaaagaabaaaaaaaaaaaaceaaaaaklkkkkdo
mommemdnaaaaaaaaaaaaaaaadcaaaaalccaabaaaaaaaaaaabkiacaiaebaaaaaa
aaaaaaaaabaaaaaaabeaaaaaaaaamadpabeaaaaaaaaaiadpdbaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaadcaaaaakecaabaaaaaaaaaaa
akaabaiaebaaaaaaaaaaaaaaabeaaaaaklkkkkdoabeaaaaaaaaaiadpdbaaaaai
ecaabaaaaaaaaaaackiacaaaaaaaaaaaabaaaaaackaabaaaaaaaaaaadcaaaaal
dcaabaaaacaaaaaaegbabaaaabaaaaaaogikcaaaaaaaaaaaadaaaaaaegiacaaa
aaaaaaaaadaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaaeghobaaa
abaaaaaaaagabaaaabaaaaaaaaaaaaamgcaabaaaacaaaaaakgilcaiaebaaaaaa
aaaaaaaaabaaaaaaaceaaaaaaaaaaaaaaaaaiadppgcifmdpaaaaaaaaaaaaaaai
icaabaaaaaaaaaaabkaabaiaebaaaaaaacaaaaaaakaabaaaacaaaaaadeaaaaah
icaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaaaadhaaaaajbcaabaaa
adaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaadkaabaaaaaaaaaaaaaaaaaai
ecaabaaaaaaaaaaaakaabaiaebaaaaaaadaaaaaaabeaaaaaaaaaiadpdiaaaaal
kcaabaaaacaaaaaaagiacaaaaaaaaaaaacaaaaaaaceaaaaaaaaaaaaamnmmemdo
aaaaaaaaaaaaeaeadcaaaaajccaabaaaaeaaaaaabkbabaaaabaaaaaaabeaaaaa
aaaaiadodkaabaaaacaaaaaadcaaaaajbcaabaaaaeaaaaaaakbabaaaabaaaaaa
abeaaaaaaaaaaaeabkaabaaaacaaaaaaefaaaaajpcaabaaaafaaaaaaegaabaaa
aeaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadiaaaaahicaabaaaaaaaaaaa
akaabaaaaeaaaaaaabeaaaaaggggigeadcaaaaakicaabaaaabaaaaaaakiacaaa
aaaaaaaaacaaaaaaabeaaaaaaaaaeaeaakaabaaaafaaaaaadiaaaaakhcaabaaa
aeaaaaaafgbebaaaabaaaaaaaceaaaaaaaaaiadoaaaaoaeaggggkgdpaaaaaaaa
dcaaaaakicaabaaaaeaaaaaaakiacaaaaaaaaaaaacaaaaaaabeaaaaaaaaaaaea
akaabaaaaeaaaaaaefaaaaajpcaabaaaafaaaaaaogakbaaaaeaaaaaaeghobaaa
aaaaaaaaaagabaaaacaaaaaadcaaaaakccaabaaaacaaaaaaakiacaaaaaaaaaaa
acaaaaaaabeaaaaaaaaakaeaakaabaaaafaaaaaadiaaaaahccaabaaaacaaaaaa
bkaabaaaacaaaaaaabeaaaaamdpfmieaenaaaaagccaabaaaacaaaaaaaanaaaaa
bkaabaaaacaaaaaadcaaaaajccaabaaaacaaaaaabkaabaaaacaaaaaaabeaaaaa
aaaaaadpabeaaaaaaaaaaadpaaaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaa
bkaabaaaacaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
mdpfmieabkaabaaaaeaaaaaadcaaaaakicaabaaaabaaaaaaakiacaaaaaaaaaaa
acaaaaaaabeaaaaaaaaadiecdkaabaaaabaaaaaadcaaaaakicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaakiacaaaaaaaaaaaabaaaaaadkaabaaaabaaaaaaenaaaaag
icaabaaaaaaaaaaaaanaaaaadkaabaaaaaaaaaaadcaaaaajicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpaaaaaaaiicaabaaa
abaaaaaadkaabaiaebaaaaaaaaaaaaaabkaabaaaacaaaaaadcaaaaajicaabaaa
aaaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaadpdkaabaaaaaaaaaaadiaaaaah
icaabaaaabaaaaaadkaabaaaaaaaaaaaabeaaaaamnmmemdodcaaaaakicaabaaa
acaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaamnmmemdoabeaaaaaaaaaiadp
aaaaaaalmcaabaaaadaaaaaafgifcaaaaaaaaaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaaaaajkjjfjlpmnmmemlpdeaaaaakmcaabaaaadaaaaaakgaobaaaadaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadiaaaaakmcaabaaaadaaaaaa
kgaobaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaacaebaaaaeaeadcaaaaaj
icaabaaaabaaaaaackaabaaaadaaaaaadkaabaaaacaaaaaadkaabaaaabaaaaaa
dcaaaaajbcaabaaaaeaaaaaadkaabaaaabaaaaaackaabaaaaaaaaaaaakaabaaa
adaaaaaadcaaaaakbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkkkdo
dkaabaiaebaaaaaaaaaaaaaadcaaaaamfcaabaaaaaaaaaaaagaabaaaaaaaaaaa
aceaaaaaaaaaaadpaaaaaaaamnmmemdpaaaaaaaapgapbaaaaaaaaaaadcaaaaaj
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaialp
cpaaaaagicaabaaaaaaaaaaackiacaaaaaaaaaaaabaaaaaadiaaaaakmcaabaaa
aeaaaaaapgapbaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadomnmmmmdn
bjaaaaafmcaabaaaaeaaaaaakgaobaaaaeaaaaaadiaaaaahccaabaaaaeaaaaaa
akaabaaaaaaaaaaadkaabaaaaeaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaa
acaaaaaaakaabaaaaaaaaaaadiaaaaahccaabaaaadaaaaaackaabaaaaeaaaaaa
akaabaaaaaaaaaaadhaaaaajdcaabaaaaaaaaaaafgafbaaaaaaaaaaaegaabaaa
aeaaaaaaegaabaaaadaaaaaaaaaaaaaiicaabaaaaaaaaaaackaabaaaacaaaaaa
dkbabaiaebaaaaaaabaaaaaadbaaaaahicaabaaaabaaaaaadkbabaaaabaaaaaa
ckaabaaaacaaaaaadicaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaakaeadcaaaaakbcaabaaaadaaaaaadkaabaaaaaaaaaaaakaabaiaebaaaaaa
aaaaaaaaakaabaaaaaaaaaaadiaaaaahccaabaaaadaaaaaabkaabaaaaaaaaaaa
akaabaaaadaaaaaadhaaaaajdcaabaaaaaaaaaaapgapbaaaabaaaaaaegaabaaa
adaaaaaaegaabaaaaaaaaaaadiaaaaaijcaabaaaaaaaaaaaagaibaaaaaaaaaaa
kgiccaaaaaaaaaaaabaaaaaaaaaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
abeaaaaaaaaaaalpdiaaaaahicaabaaaaaaaaaaaakaabaaaabaaaaaadkaabaaa
aaaaaaaadiaaaaakmcaabaaaaaaaaaaakgaobaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaiadomnmmemdndiaaaaahicaabaaaaaaaaaaabkaabaaaacaaaaaa
dkaabaaaaaaaaaaadcaaaaakbcaabaaaacaaaaaadkaabaiaebaaaaaaaaaaaaaa
akaabaaaaaaaaaaackbabaaaabaaaaaaaaaaaaaiicaabaaaaaaaaaaadkbabaia
ebaaaaaaabaaaaaaabeaaaaaaaaaiadpdcaaaaakccaabaaaacaaaaaackaabaia
ebaaaaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaaaaaaaaaefaaaaajpcaabaaa
acaaaaaaegaabaaaacaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaadgaaaaaf
ecaabaaaabaaaaaaabeaaaaaaaaaiadpaaaaaaaipcaabaaaabaaaaaafgajbaaa
abaaaaaaegaobaiaebaaaaaaacaaaaaadcaaaaajpcaabaaaabaaaaaapgapbaaa
adaaaaaaegaobaaaabaaaaaaegaobaaaacaaaaaacpaaaaafncaabaaaaaaaaaaa
agajbaaaabaaaaaadiaaaaakncaabaaaaaaaaaaaagaobaaaaaaaaaaaaceaaaaa
mnmmemdpaaaaaaaamnmmemdpmnmmemdpbjaaaaafncaabaaaaaaaaaaaagaobaaa
aaaaaaaadbaaaaahbcaabaaaacaaaaaaabeaaaaaaaaaaadpbkaabaaaaaaaaaaa
dbaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaajkjjjjlodhaaaaaj
ncaabaaaaaaaaaaaagaabaaaacaaaaaaagaobaaaaaaaaaaaagajbaaaabaaaaaa
diaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaaaceaaaaaggggggdpggggggdp
ggggggdpaaaaaaaadgaaaaaficcabaaaaaaaaaaadkaabaaaabaaaaaadhaaaaaj
hccabaaaaaaaaaaafgafbaaaaaaaaaaaegacbaaaabaaaaaaigadbaaaaaaaaaaa
doaaaaab"
}




}
 }
}
}