// Compiled shader for all platforms, uncompressed size: 62.4KB

Shader "Futile/LevelColorDebug" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
 GrabPass {
 }


 // Stats for Vertex shader:
 //       d3d11 : 5 math
 //        d3d9 : 5 math
 //        gles : 210 math, 15 texture, 17 branch
 //       gles3 : 210 math, 15 texture, 17 branch
 //   glesdesktop : 210 math, 15 texture, 17 branch
 //       metal : 3 math
 //      opengl : 5 math
 // Stats for Fragment shader:
 //       d3d11 : 109 math, 15 texture, 5 branch
 //        d3d9 : 222 math, 15 texture, 5 branch
 //       metal : 210 math, 15 texture, 17 branch
 //      opengl : 216 math, 15 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 96
Vector 80 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedgalfkkmeejbgnejmlejlkjffjjghdjkaabaaaaaacmacaaaaadaaaaaa
cmaaaaaakaaaaaaapiaaaaaaejfdeheogmaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaafjaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahaaaaaagaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apadaaaafaepfdejfeejepeoaaeoepfcenebemaafeeffiedepepfceeaaklklkl
epfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaeeaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
fdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieefccmabaaaa
eaaaabaaelaaaaaafjaaaaaeegiocaaaaaaaaaaaagaaaaaafjaaaaaeegiocaaa
abaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaacaaaaaa
ghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaal
dccabaaaabaaaaaaegbabaaaacaaaaaaegiacaaaaaaaaaaaafaaaaaaogikcaaa
aaaaaaaaafaaaaaadoaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 109 math, 15 textures, 5 branches
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_NoiseTex] 2D 3
SetTexture 2 [_PalTex] 2D 2
SetTexture 3 [_GrabTexture] 2D 0
ConstBuffer "$Globals" 96
Float 20 [_RAIN]
Float 24 [_light]
Vector 32 [_spriteRect]
Vector 48 [_lightDirAndPixelSize]
Float 64 [_fogAmount]
Float 68 [_waterLevel]
BindCB  "$Globals" 0
"ps_4_0
eefiecedhgbkfphgigpnihghbabhekajjhebahddabaaaaaaeebeaaaaadaaaaaa
cmaaaaaaieaaaaaaliaaaaaaejfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaeeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieefciebdaaaa
eaaaaaaaobaeaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaafkaaaaadaagabaaa
aaaaaaaafkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaad
aagabaaaadaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaa
abaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaafibiaaaeaahabaaa
adaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacalaaaaaaefaaaaajpcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaa
aaaaaaaaaagabaaaabaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaafgffdfeabnaaaaaiccaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaabkaaaaagbcaabaaaaaaaaaaaakaabaiaibaaaaaaaaaaaaaa
dhaaaaakbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaa
aaaaleecabeaaaaaaaaaialpdiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaijiiaidnbnaaaaaiccaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaabkaaaaagbcaabaaaaaaaaaaaakaabaiaibaaaaaaaaaaaaaa
dhaaaaakbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaia
ebaaaaaaaaaaaaaadiaaaaakgcaabaaaaaaaaaaaagbbbaaaabaaaaaaaceaaaaa
aaaaaaaaaaaamadpaaaaiadoaaaaaaaadcaaaaandcaabaaaaaaaaaaaagaabaia
ebaaaaaaaaaaaaaaaceaaaaamnmmmmdnmnmmmmdnaaaaaaaaaaaaaaaajgafbaaa
aaaaaaaadiaaaaaiecaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaa
mnmmmmdndcaaaaandcaabaaaaaaaaaaafgifcaaaaaaaaaaaabaaaaaaaceaaaaa
aknhcddmmnmmemdnaaaaaaaaaaaaaaaaegaabaaaaaaaaaaaefaaaaajpcaabaaa
abaaaaaaegaabaaaaaaaaaaaeghobaaaabaaaaaaaagabaaaadaaaaaaaaaaaaah
bcaabaaaaaaaaaaaakaabaaaabaaaaaaakbabaaaabaaaaaaaaaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaabkbabaaaabaaaaaadcaaaaakbcaabaaaaaaaaaaa
bkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmmmdnakaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaafclibgebenaaaaagbcaabaaa
aaaaaaaaaanaaaaaakaabaaaaaaaaaaaaaaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaabeaaaaaddddhdlpdicaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaakaebaaaaaaakkcaabaaaaaaaaaaaagiecaiaebaaaaaaaaaaaaaa
acaaaaaakgiocaaaaaaaaaaaacaaaaaadcaaaaakkcaabaaaaaaaaaaaagbebaaa
abaaaaaafganbaaaaaaaaaaaagiecaaaaaaaaaaaacaaaaaaaaaaaaaiicaabaaa
aaaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdbaaaaaibcaabaaa
abaaaaaabkiacaaaaaaaaaaaaeaaaaaadkaabaaaaaaaaaaadiaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaagpbciddkdhaaaaajbcaabaaaaaaaaaaa
akaabaaaabaaaaaaabeaaaaaaaaaaaaaakaabaaaaaaaaaaaaaaaaaahccaabaaa
abaaaaaaakaabaaaaaaaaaaabkbabaaaabaaaaaadgaaaaafbcaabaaaabaaaaaa
akbabaaaabaaaaaaefaaaaajpcaabaaaabaaaaaaegaabaaaabaaaaaaeghobaaa
aaaaaaaaaagabaaaabaaaaaabiaaaaakhcaabaaaacaaaaaaegacbaaaabaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
bkaabaaaacaaaaaaakaabaaaacaaaaaaabaaaaahbcaabaaaaaaaaaaackaabaaa
acaaaaaaakaabaaaaaaaaaaadiaaaaakdcaabaaaabaaaaaaegaabaaaabaaaaaa
aceaaaaaaaaahpedaaaahpedaaaaaaaaaaaaaaaablaaaaafdcaabaaaacaaaaaa
egaabaaaabaaaaaadcaaaaajecaabaaaaaaaaaaaakbabaaaabaaaaaaabeaaaaa
aaaaaadpckaabaaaaaaaaaaaboaaaaakhcaabaaaadaaaaaaagabbaaaacaaaaaa
aceaaaaappppppppkgpppppppmppppppaaaaaaaaclaaaaafbcaabaaaabaaaaaa
akaabaaaadaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaa
ijiiaidnbnaaaaaiccaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaa
abaaaaaabkaaaaagbcaabaaaabaaaaaaakaabaiaibaaaaaaabaaaaaadhaaaaak
bcaabaaaabaaaaaabkaabaaaabaaaaaaakaabaaaabaaaaaaakaabaiaebaaaaaa
abaaaaaadcaaaaakbcaabaaaaeaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaa
omfblidnckaabaaaaaaaaaaadcaaaaakecaabaaaaaaaaaaabkbabaiaebaaaaaa
abaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaiadpdcaaaaakecaabaaaaaaaaaaa
bkiacaaaaaaaaaaaabaaaaaaabeaaaaamnmmemdockaabaaaaaaaaaaadcaaaaak
ccaabaaaaeaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaaomfblidnckaabaaa
aaaaaaaaefaaaaajpcaabaaaaeaaaaaaegaabaaaaeaaaaaaeghobaaaabaaaaaa
aagabaaaadaaaaaadcaaaaakecaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaa
abeaaaaamnmmmmdnakaabaaaaeaaaaaaaaaaaaaiecaabaaaaaaaaaaackaabaaa
aaaaaaaabkbabaiaebaaaaaaabaaaaaabnaaaaaibcaabaaaabaaaaaackaabaaa
aaaaaaaackaabaiaebaaaaaaaaaaaaaabkaaaaagecaabaaaaaaaaaaackaabaia
ibaaaaaaaaaaaaaadhaaaaakecaabaaaaaaaaaaaakaabaaaabaaaaaackaabaaa
aaaaaaaackaabaiaebaaaaaaaaaaaaaadiaaaaahecaabaaaaaaaaaaackaabaaa
aaaaaaaaabeaaaaamdpfmieaenaaaaagecaabaaaaaaaaaaaaanaaaaackaabaaa
aaaaaaaadcaaaaajecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaeaea
abeaaaaaaaaaaadpdccaaaalicaabaaaadaaaaaackiacaiaebaaaaaaaaaaaaaa
abaaaaaaabeaaaaaaaaaiaeackaabaaaaaaaaaaaccaaaaakdcaabaaaabaaaaaa
aceaaaaafkaaaaaaadaaaaaaaaaaaaaaaaaaaaaaegaabaaaacaaaaaadcaaaaak
ecaabaaaacaaaaaadkaabaiaebaaaaaaadaaaaaaabeaaaaamnmmmmdnabeaaaaa
aaaaiadpdhaaaaajhcaabaaaacaaaaaaagabbaaaabaaaaaahgaobaaaadaaaaaa
cgajbaaaacaaaaaaclaaaaafecaabaaaaaaaaaaabkaabaaaacaaaaaadiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaijiiaidnebaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaablaaaaafbcaabaaaabaaaaaackaabaaaaaaaaaaa
boaaaaahicaabaaaabaaaaaabkaabaaaacaaaaaaabeaaaaappppppppclaaaaaf
icaabaaaabaaaaaadkaabaaaabaaaaaadiaaaaahicaabaaaabaaaaaadkaabaaa
abaaaaaaabeaaaaaijiiaidnbnaaaaaiccaabaaaacaaaaaadkaabaaaabaaaaaa
dkaabaiaebaaaaaaabaaaaaabkaaaaagicaabaaaabaaaaaadkaabaiaibaaaaaa
abaaaaaadhaaaaakicaabaaaabaaaaaabkaabaaaacaaaaaadkaabaaaabaaaaaa
dkaabaiaebaaaaaaabaaaaaadiaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaa
abeaaaaaaaaapaebblaaaaafccaabaaaacaaaaaadkaabaaaabaaaaaaedaaaaaf
icaabaaaabaaaaaadkaabaaaabaaaaaadiaaaaakdcaabaaaadaaaaaaogikcaaa
aaaaaaaaadaaaaaaegiacaiaebaaaaaaaaaaaaaaadaaaaaaboaaaaahicaabaaa
acaaaaaabkaabaaaacaaaaaaabeaaaaaplppppppclaaaaaficaabaaaacaaaaaa
dkaabaaaacaaaaaadiaaaaahdcaabaaaadaaaaaapgapbaaaacaaaaaaegaabaaa
adaaaaaadcaaaaajbcaabaaaaeaaaaaaakaabaaaadaaaaaaabeaaaaajkjjjjdp
bkaabaaaaaaaaaaadcaaaaajccaabaaaaeaaaaaabkaabaaaadaaaaaaabeaaaaa
jkjjjjdpdkaabaaaaaaaaaaaefaaaaajpcaabaaaadaaaaaaegaabaaaaeaaaaaa
eghobaaaadaaaaaaaagabaaaaaaaaaaadiaaaaahbcaabaaaaeaaaaaadkaabaaa
abaaaaaaabeaaaaaaaaaaadnboaaaaahccaabaaaaaaaaaaaakaabaaaabaaaaaa
abeaaaaaadaaaaaaclaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaaaaaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadpdiaaaaahecaabaaa
aeaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadoefaaaaajpcaabaaaafaaaaaa
igaabaaaaeaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaaaaaaaaahccaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaadpdiaaaaahicaabaaaaeaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaaaadoefaaaaajpcaabaaaaeaaaaaamgaabaaa
aeaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaaaaaaaaahgcaabaaaaaaaaaaa
agbbbaaaabaaaaaaagbbbaaaabaaaaaaefaaaaajpcaabaaaagaaaaaajgafbaaa
aaaaaaaaeghobaaaabaaaaaaaagabaaaadaaaaaadcaaaaakccaabaaaaaaaaaaa
akaabaaaagaaaaaaabeaaaaaaaaaiaeabkiacaaaaaaaaaaaabaaaaaadcaaaaaj
ccaabaaaaaaaaaaadkaabaaaabaaaaaaabeaaaaaklkkkkdnbkaabaaaaaaaaaaa
diaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaamdpfmieaenaaaaag
ccaabaaaaaaaaaaaaanaaaaabkaabaaaaaaaaaaadcaaaaajccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaajccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaamiebabeaaaaaaaaalaeadiaaaaah
bcaabaaaagaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaadndgaaaaafccaabaaa
agaaaaaaabeaaaaaaaaafadpefaaaaajpcaabaaaagaaaaaaegaabaaaagaaaaaa
eghobaaaacaaaaaaaagabaaaacaaaaaacjaaaaahccaabaaaaaaaaaaackaabaaa
acaaaaaaabeaaaaaabaaaaaaboaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaapoppppppclaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaaaaaaaaal
gcaabaaaaaaaaaaafgafbaiaebaaaaaaaaaaaaaaaceaaaaaaaaaaaaaaaaalaea
aaaajaeaaaaaaaaadiaaaaakdcaabaaaahaaaaaajgafbaaaaaaaaaaaaceaaaaa
aaaaaadoaaaaaadoaaaaaaaaaaaaaaaadgaaaaaimcaabaaaahaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaahedpaaaahmdpefaaaaajpcaabaaaaiaaaaaacgakbaaa
ahaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaaefaaaaajpcaabaaaajaaaaaa
dgapbaaaahaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaaefaaaaajpcaabaaa
akaaaaaaggakbaaaahaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaaefaaaaaj
pcaabaaaahaaaaaahgapbaaaahaaaaaaeghobaaaacaaaaaaaagabaaaacaaaaaa
bpaaaeadakaabaaaaaaaaaaaefaaaaampcaabaaaaaaaaaaaaceaaaaaaaaaiadm
aaaahadpaaaaaaaaaaaaaaaadghjbaaaacaaaaaaaagabaaaacaaaaaadgaaaaaf
hccabaaaaaaaaaaajgahbaaaaaaaaaaadgaaaaafbcaabaaaabaaaaaaabeaaaaa
ppppppppbcaaaaabdjaaaaahicaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaa
aaaaiadpccaaaaahbcaabaaaabaaaaaaabeaaaaaafaaaaaabkaabaaaacaaaaaa
abaaaaahccaabaaaacaaaaaaakaabaaaabaaaaaadkaabaaaacaaaaaabpaaaead
bkaabaaaacaaaaaadjaaaaakhcaabaaaadaaaaaaegacbaaaadaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaahccaabaaaacaaaaaabkaabaaa
adaaaaaaakaabaaaadaaaaaadmaaaaahccaabaaaacaaaaaackaabaaaadaaaaaa
bkaabaaaacaaaaaadhaaaaajbcaabaaaacaaaaaabkaabaaaacaaaaaaabeaaaaa
aaaaiadpakaabaaaacaaaaaabfaaaaabaaaaaaaipcaabaaaadaaaaaaegaobaia
ebaaaaaaafaaaaaaegaobaaaaeaaaaaadcaaaaajpcaabaaaadaaaaaaagaabaaa
acaaaaaaegaobaaaadaaaaaaegaobaaaafaaaaaaabaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaabeaaaaamnmmmmdnaaaaaaaipcaabaaaaeaaaaaaegaobaia
ebaaaaaaadaaaaaaegaobaaaagaaaaaadcaaaaajpcaabaaaadaaaaaafgafbaaa
abaaaaaaegaobaaaaeaaaaaaegaobaaaadaaaaaaccaaaaahccaabaaaabaaaaaa
abeaaaaaaaaaaaaackaabaaaacaaaaaaccaaaaahccaabaaaacaaaaaackaabaaa
acaaaaaaabeaaaaaadaaaaaaabaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaa
bkaabaaaacaaaaaabpaaaeadbkaabaaaabaaaaaaaaaaaaaipcaabaaaaeaaaaaa
egaobaiaebaaaaaaaiaaaaaaegaobaaaajaaaaaadcaaaaajpcaabaaaaeaaaaaa
agaabaaaacaaaaaaegaobaaaaeaaaaaaegaobaaaaiaaaaaaaaaaaaaipcaabaaa
afaaaaaaegaobaiaebaaaaaaakaaaaaaegaobaaaahaaaaaadcaaaaajpcaabaaa
afaaaaaaagaabaaaacaaaaaaegaobaaaafaaaaaaegaobaaaakaaaaaadiaaaaah
ccaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaijiiaidnaaaaaaaipcaabaaa
afaaaaaaegaobaiaebaaaaaaaeaaaaaaegaobaaaafaaaaaadcaaaaajpcaabaaa
aeaaaaaafgafbaaaabaaaaaaegaobaaaafaaaaaaegaobaaaaeaaaaaaaaaaaaai
pcaabaaaaeaaaaaaegaobaiaebaaaaaaadaaaaaaegaobaaaaeaaaaaadcaaaaaj
pcaabaaaaeaaaaaakgakbaaaabaaaaaaegaobaaaaeaaaaaaegaobaaaadaaaaaa
bcaaaaabcaaaaaahccaabaaaabaaaaaackaabaaaacaaaaaaabeaaaaaadaaaaaa
aaaaaaalpcaabaaaacaaaaaaegaobaiaebaaaaaaadaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpdcaaaaajpcaabaaaacaaaaaakgakbaaaabaaaaaa
egaobaaaacaaaaaaegaobaaaadaaaaaadhaaaaajpcaabaaaaeaaaaaafgafbaaa
abaaaaaaegaobaaaacaaaaaaegaobaaaadaaaaaabfaaaaabefaaaaampcaabaaa
acaaaaaaaceaaaaaaaaaeadnaaaahadpaaaaaaaaaaaaaaaaeghobaaaacaaaaaa
aagabaaaacaaaaaadiaaaaaiccaabaaaabaaaaaadkaabaaaabaaaaaaakiacaaa
aaaaaaaaaeaaaaaadiaaaaahccaabaaaabaaaaaabkaabaaaabaaaaaaabeaaaaa
ijiiaidnaaaaaaaipcaabaaaacaaaaaaegaobaiaebaaaaaaaeaaaaaaegaobaaa
acaaaaaadcaaaaajpcaabaaaaaaaaaaafgafbaaaabaaaaaadgajbaaaacaaaaaa
dgajbaaaaeaaaaaadgaaaaafhccabaaaaaaaaaaajgahbaaaaaaaaaaabfaaaaab
diaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaadddddddpdhaaaaaj
iccabaaaaaaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaaaaakaabaaaaaaaaaaa
doaaaaab"
}




}
 }
}
}