// Compiled shader for all platforms, uncompressed size: 43.7KB

Shader "Futile/Fog" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 111 math, 8 texture, 10 branch
 //       gles3 : 111 math, 8 texture, 10 branch
 //   glesdesktop : 111 math, 8 texture, 10 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 87 math, 8 texture, 7 branch
 //        d3d9 : 154 math, 8 texture, 6 branch
 //       metal : 111 math, 8 texture, 10 branch
 //      opengl : 129 math, 7 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 80
Vector 64 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedghmpondecomckjonnofelkflhfaeemaoabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaafaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaaeaaaaaa
ogikcaaaaaaaaaaaaeaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 87 math, 8 textures, 7 branches
SetTexture 0 [_NoiseTex] 2D 2
SetTexture 1 [_LevelTex] 2D 1
SetTexture 2 [_GrabTexture] 2D 0
SetTexture 3 [_PalTex] 2D 3
ConstBuffer "$Globals" 80
Float 16 [_waterLevel]
Float 20 [_RAIN]
Vector 32 [_spriteRect]
BindCB  "$Globals" 0
"ps_4_0
eefiecedodfkmbkcegoihcfkpjpnecnbbfgbimfoabaaaaaajaaoaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcjmanaaaaeaaaaaaaghadaaaafjaaaaae
egiocaaaaaaaaaaaadaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaae
aahabaaaacaaaaaaffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaagcbaaaad
dcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaadicbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacadaaaaaaaaaaaaajdcaabaaaaaaaaaaa
ogbkbaaaabaaaaaaegiacaiaebaaaaaaaaaaaaaaacaaaaaaaaaaaaakmcaabaaa
aaaaaaaaagiecaiaebaaaaaaaaaaaaaaacaaaaaakgiocaaaaaaaaaaaacaaaaaa
aoaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaaogakbaaaaaaaaaaaaaaaaaaj
ecaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaaabaaaaaaabeaaaaaaknhgddp
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaadkbabaaaabaaaaaa
dicaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaeaeadiaaaaal
dcaabaaaabaaaaaafgifcaaaaaaaaaaaabaaaaaaaceaaaaaaknhkddnilgmohdn
aaaaaaaaaaaaaaaadcaaaaajbcaabaaaacaaaaaaakaabaaaaaaaaaaaabeaaaaa
jkjjbjdpakaabaaaabaaaaaadcaaaaalccaabaaaacaaaaaabkiacaiaebaaaaaa
aaaaaaaaabaaaaaaabeaaaaaaknhcddmbkaabaaaaaaaaaaaefaaaaajpcaabaaa
acaaaaaaegaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaadcaaaaak
icaabaaaaaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaaaknhcddnakaabaaa
acaaaaaaaaaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaakbabaaaabaaaaaa
diaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaamdpfmieaenaaaaag
icaabaaaaaaaaaaaaanaaaaadkaabaaaaaaaaaaadcaaaaajicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpdcaaaaakbcaabaaa
acaaaaaaakaabaaaaaaaaaaaabeaaaaakoehobdobkaabaiaebaaaaaaabaaaaaa
diaaaaaibcaabaaaabaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaabhlhfbdl
dcaaaaakccaabaaaacaaaaaabkaabaaaaaaaaaaaabeaaaaajkjjjjdpakaabaia
ebaaaaaaabaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaaeghobaaa
aaaaaaaaaagabaaaacaaaaaadcaaaaakbcaabaaaabaaaaaabkiacaaaaaaaaaaa
abaaaaaaabeaaaaamnmmemdnakaabaaaacaaaaaaaaaaaaahbcaabaaaabaaaaaa
akaabaaaabaaaaaabkbabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaamdpfmieaenaaaaagbcaabaaaabaaaaaaaanaaaaaakaabaaa
abaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaadp
abeaaaaaaaaaaadpaaaaaaaiicaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaia
ebaaaaaaabaaaaaadcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaa
aaaaaadpakaabaaaabaaaaaaefaaaaajpcaabaaaacaaaaaaegaabaaaaaaaaaaa
eghobaaaabaaaaaaaagabaaaabaaaaaadcaaaaajbcaabaaaaaaaaaaaakaabaaa
acaaaaaaabeaaaaaaaaahpedabeaaaaaaaaaialpdiaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaijiiaidnbnaaaaaiccaabaaaaaaaaaaaakaabaaa
aaaaaaaaakaabaiaebaaaaaaaaaaaaaabkaaaaagbcaabaaaaaaaaaaaakaabaia
ibaaaaaaaaaaaaaadhaaaaakbcaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaa
aaaaaaaaakaabaiaebaaaaaaaaaaaaaabiaaaaakncaabaaaabaaaaaaagajbaaa
acaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaiadpaaaaiadpabaaaaahccaabaaa
aaaaaaaackaabaaaabaaaaaaakaabaaaabaaaaaaabaaaaahccaabaaaaaaaaaaa
dkaabaaaabaaaaaabkaabaaaaaaaaaaadhaaaaajbcaabaaaaaaaaaaabkaabaaa
aaaaaaaaabeaaaaaaaaaiadpakaabaaaaaaaaaaadbaaaaahccaabaaaaaaaaaaa
abeaaaaamnmmemdoakaabaaaaaaaaaaadcaaaaapfcaabaaaabaaaaaakgblbaaa
abaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaialpaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaiadpaaaaaaaaefaaaaajpcaabaaaacaaaaaaigaabaaaabaaaaaa
eghobaaaacaaaaaaaagabaaaaaaaaaaabpaaaeadbkaabaaaaaaaaaaadbaaaaah
ccaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaaacaaaaaadjaaaaakfcaabaaa
abaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
dmaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaadmaaaaah
ccaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaaaaaaaaaadhaaaaajbcaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaamnmmemdoakaabaaaaaaaaaaabfaaaaab
biaaaaahccaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadpdcaaaaaj
bcaabaaaabaaaaaaakbabaaaabaaaaaaabeaaaaajkjjnjdpbkaabaaaabaaaaaa
diaaaaahccaabaaaabaaaaaabkbabaaaabaaaaaaabeaaaaaobhkdeeaefaaaaaj
pcaabaaaabaaaaaaegaabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaacaaaaaa
bpaaaeadbkaabaaaaaaaaaaadcaaaaakccaabaaaaaaaaaaabkiacaaaaaaaaaaa
abaaaaaaabeaaaaacjfmapdoakaabaaaabaaaaaaaaaaaaaiccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakbabaiaebaaaaaaabaaaaaadiaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaabeaaaaamdpfmieaenaaaaagccaabaaaaaaaaaaaaanaaaaa
bkaabaaaaaaaaaaadcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaadpabeaaaaaaaaaaadpaaaaaaakdcaabaaaabaaaaaaegbabaaaabaaaaaa
aceaaaaaaaaaaaiagggggglpaaaaaaaaaaaaaaaaapaaaaahbcaabaaaabaaaaaa
egaabaaaabaaaaaaegaabaaaabaaaaaaelaaaaafbcaabaaaabaaaaaaakaabaaa
abaaaaaaaaaaaaaibcaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaa
aaaaiadpdeaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaaabeaaaaaaaaaaaaa
diaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaacpaaaaaf
ccaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaaabeaaaaamnmmemdobjaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaa
diaaaaahccaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaacpaaaaaf
bcaabaaaabaaaaaadkaabaaaaaaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaabeaaaaaaaaamadpbjaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaa
aaaaaaaibcaabaaaabaaaaaaakaabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
diaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaadkbabaaaacaaaaaadbaaaaahbcaabaaa
abaaaaaaabeaaaaaaaaaaadpbkaabaaaaaaaaaaabpaaaeadakaabaaaabaaaaaa
efaaaaampcaabaaaabaaaaaaaceaaaaaaaaaaaaaaaaagadpaaaaaaaaaaaaaaaa
eghobaaaadaaaaaaaagabaaaadaaaaaadbaaaaahccaabaaaaaaaaaaaabeaaaaa
jkjjbjdpbkaabaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaaiadoabeaaaaamnmmmmdnaaaaaaalpcaabaaaacaaaaaaegaobaia
ebaaaaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpdcaaaaaj
pccabaaaaaaaaaaafgafbaaaaaaaaaaaegaobaaaacaaaaaaegaobaaaabaaaaaa
doaaaaabbfaaaaabbfaaaaabdiaaaaahccaabaaaaaaaaaaadkaabaaaaaaaaaaa
dkaabaaaaaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaa
aaaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaadkbabaaaacaaaaaa
cpaaaaaficaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaa
dkaabaaaaaaaaaaaabeaaaaamnmmmmdnbjaaaaaficaabaaaaaaaaaaadkaabaaa
aaaaaaaaaaaaaaaiicaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaa
aaaaiadpdcaaaaajicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaapaeb
abeaaaaaaaaaiadpcpaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaaaaaaaaaabjaaaaafccaabaaa
aaaaaaaabkaabaaaaaaaaaaaaaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaa
aaaaaaaaabeaaaaaaaaaiadpaaaaaaaiccaabaaaaaaaaaaackaabaiaebaaaaaa
aaaaaaaabkaabaaaaaaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaaaaaacpaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaamnmmemdobjaaaaafccaabaaa
aaaaaaaabkaabaaaaaaaaaaadbaaaaahecaabaaaaaaaaaaaabeaaaaamnmmmmdn
bkaabaaaaaaaaaaabpaaaeadckaabaaaaaaaaaaaefaaaaampcaabaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaiadoaaaaaaaaaaaaaaaaeghobaaaadaaaaaaaagabaaa
adaaaaaaefaaaaampcaabaaaacaaaaaaaceaaaaaaaaaaaaaaaaagadpaaaaaaaa
aaaaaaaaeghobaaaadaaaaaaaagabaaaadaaaaaadcaaaaajbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaaadpaaaaaaaihcaabaaa
acaaaaaaegacbaiaebaaaaaaabaaaaaaegacbaaaacaaaaaadcaaaaajhccabaaa
aaaaaaaaagaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaabaaaaaadbaaaaah
bcaabaaaaaaaaaaaabeaaaaaaaaaaadpbkaabaaaaaaaaaaadhaaaaajiccabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaajkjjbjdpabeaaaaamnmmemdodoaaaaab
bcaaaaabdgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadoaaaaabbfaaaaabdoaaaaab"
}




}
 }
}
}