// Compiled shader for all platforms, uncompressed size: 57.8KB

Shader "Futile/House" {
Properties {
 _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 7 math
 //        d3d9 : 9 math
 //        gles : 112 math, 18 texture, 4 branch
 //       gles3 : 112 math, 18 texture, 4 branch
 //   glesdesktop : 112 math, 18 texture, 4 branch
 //       metal : 5 math
 //      opengl : 9 math
 // Stats for Fragment shader:
 //       d3d11 : 87 math, 18 texture, 6 branch
 //        d3d9 : 171 math, 18 texture, 3 branch
 //       metal : 112 math, 18 texture, 4 branch
 //      opengl : 173 math, 18 texture
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  BindChannels {
   Bind "vertex", Vertex
   Bind "color", Color
   Bind "texcoord", TexCoord
  }
  ZWrite Off
  Cull Off
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha OneMinusSrcAlpha
Program "vp" {


SubProgram "d3d11 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 96
Vector 80 [_MainTex_ST]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedkioagoejkaaojogofkbibfacjaabnikgabaaaaaaeeadaaaaadaaaaaa
cmaaaaaapeaaaaaaiaabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapapaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoieaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamadaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaakl
fdeieefclmabaaaaeaaaabaagpaaaaaafjaaaaaeegiocaaaaaaaaaaaagaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaadaaaaaafpaaaaadpcbabaaaafaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaad
pccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaak
hcaabaaaaaaaaaaaegadbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadp
aaaaaaaaaaaaaaahmccabaaaabaaaaaakgakbaaaaaaaaaaaagaebaaaaaaaaaaa
dcaaaaaldccabaaaabaaaaaaegbabaaaadaaaaaaegiacaaaaaaaaaaaafaaaaaa
ogikcaaaaaaaaaaaafaaaaaadgaaaaafpccabaaaacaaaaaaegbobaaaafaaaaaa
doaaaaab"
}




}
Program "fp" {


SubProgram "d3d11 " {
// Stats: 87 math, 18 textures, 6 branches
SetTexture 0 [_LevelTex] 2D 2
SetTexture 1 [_GrabTexture] 2D 0
SetTexture 2 [_NoiseTex2] 2D 3
SetTexture 3 [_MainTex] 2D 1
SetTexture 4 [_ApartmentsTex] 2D 4
SetTexture 5 [_CityPalette] 2D 5
ConstBuffer "$Globals" 96
Vector 16 [_AboveCloudsAtmosphereColor]
Vector 48 [_spriteRect]
Vector 64 [_screenSize] 2
BindCB  "$Globals" 0
"ps_4_0
eefieceddlofojbiidjgbpbbaloegkefkpklbcokabaaaaaapeapaaaaadaaaaaa
cmaaaaaaliaaaaaaomaaaaaaejfdeheoieaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaahnaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaaapahaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaedepemepfcaaklepfdeheocmaaaaaa
abaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaa
fdfgfpfegbhcghgfheaaklklfdeieefcaaapaaaaeaaaaaaamaadaaaafjaaaaae
egiocaaaaaaaaaaaafaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaadaagabaaaadaaaaaafkaaaaad
aagabaaaaeaaaaaafkaaaaadaagabaaaafaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaa
ffffaaaafibiaaaeaahabaaaadaaaaaaffffaaaafibiaaaeaahabaaaaeaaaaaa
ffffaaaafibiaaaeaahabaaaafaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaa
gcbaaaadmcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacahaaaaaadiaaaaaidcaabaaaaaaaaaaaogbkbaaaabaaaaaa
egiacaaaaaaaaaaaaeaaaaaaebaaaaafdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
aoaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaaaeaaaaaa
aaaaaaajdcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaiaebaaaaaaaaaaaaaa
adaaaaaaaaaaaaakmcaabaaaaaaaaaaaagiecaiaebaaaaaaaaaaaaaaadaaaaaa
kgiocaaaaaaaaaaaadaaaaaaaoaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaa
ogakbaaaaaaaaaaaefaaaaajpcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghobaaa
aaaaaaaaaagabaaaacaaaaaadjaaaaakhcaabaaaaaaaaaaaegacbaaaaaaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaackaabaaa
aaaaaaaaakaabaaaaaaaaaaadcaaaaapgcaabaaaaaaaaaaakgblbaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaiadpaaaaialpaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaiadpaaaaaaaaefaaaaajpcaabaaaabaaaaaajgafbaaaaaaaaaaaeghobaaa
abaaaaaaaagabaaaaaaaaaaaaoaaaaakccaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckbabaaaacaaaaaadiaaaaakmcaabaaaaaaaaaaa
fgafbaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaknhcddmmnmmmmdmdiaaaaak
dcaabaaaacaaaaaaegbabaaaacaaaaaaaceaaaaaaaaahkefaaialleeaaaaaaaa
aaaaaaaadiaaaaahmcaabaaaaaaaaaaakgaobaaaaaaaaaaaagaebaaaacaaaaaa
diaaaaahpcaabaaaacaaaaaaogaobaaaaaaaaaaaegbebaaaabaaaaaaebaaaaaf
pcaabaaaacaaaaaaegaobaaaacaaaaaaaoaaaaahpcaabaaaadaaaaaaegaobaaa
acaaaaaaogaobaaaaaaaaaaadiaaaaakfcaabaaaacaaaaaakgakbaaaacaaaaaa
aceaaaaaaaaaiadlaaaaaaaagdapdddlaaaaaaaadgaaaaaikcaabaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaaadlaaaaaaaagdaplddkefaaaaajpcaabaaaaeaaaaaa
egaabaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaaefaaaaajpcaabaaa
acaaaaaaogakbaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaadiaaaaah
icaabaaaabaaaaaaakaabaaaacaaaaaaakaabaaaaeaaaaaadcaaaaajicaabaaa
abaaaaaadkaabaaaabaaaaaaabeaaaaaddddlddpabeaaaaaddddddlpaoaaaaah
icaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaaaaaaaaaaaaaaaahicaabaaa
abaaaaaadkaabaaaabaaaaaabkbabaaaabaaaaaadiaaaaakpcaabaaaacaaaaaa
egaobaaaadaaaaaaaceaaaaaifglmmdohkkflgdohhpliodofnibhpdoefaaaaaj
pcaabaaaadaaaaaaegaabaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaa
efaaaaajpcaabaaaacaaaaaaogakbaaaacaaaaaaeghobaaaacaaaaaaaagabaaa
adaaaaaadiaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaakaabaaaadaaaaaa
dcaaaaajbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaamnmmemdoabeaaaaa
mnmmmmlnaoaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaadkaabaaaaaaaaaaa
aaaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaakbabaaaabaaaaaadiaaaaah
bcaabaaaacaaaaaackaabaaaaaaaaaaaakaabaaaacaaaaaaebaaaaafbcaabaaa
acaaaaaaakaabaaaacaaaaaaaoaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaa
ckaabaaaaaaaaaaadiaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaadkaabaaa
abaaaaaaebaaaaaficaabaaaabaaaaaadkaabaaaabaaaaaaaoaaaaahccaabaaa
acaaaaaadkaabaaaabaaaaaadkaabaaaaaaaaaaaefaaaaajpcaabaaaacaaaaaa
egaabaaaacaaaaaaeghobaaaadaaaaaaaagabaaaabaaaaaaaaaaaaaiicaabaaa
abaaaaaaakaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaahicaabaaa
abaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaiaeaebaaaaaficaabaaaabaaaaaa
dkaabaaaabaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
aaaabadpabeaaaaaaaaaeadpdiaaaaahmcaabaaaaaaaaaaakgaobaaaaaaaaaaa
pgapbaaaabaaaaaadiaaaaahpcaabaaaacaaaaaaogaobaaaaaaaaaaaegbebaaa
abaaaaaaebaaaaafpcaabaaaacaaaaaaegaobaaaacaaaaaaaoaaaaahpcaabaaa
adaaaaaaegaobaaaacaaaaaaogaobaaaaaaaaaaadiaaaaakfcaabaaaacaaaaaa
kgakbaaaacaaaaaaaceaaaaaaaaaiadlaaaaaaaagdapdddlaaaaaaaadgaaaaai
kcaabaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaadlaaaaaaaagdaplddkefaaaaaj
pcaabaaaaeaaaaaaegaabaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaa
efaaaaajpcaabaaaacaaaaaaogakbaaaacaaaaaaeghobaaaacaaaaaaaagabaaa
adaaaaaadiaaaaahicaabaaaabaaaaaaakaabaaaacaaaaaaakaabaaaaeaaaaaa
dcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaddddlddpabeaaaaa
ddddddlpaoaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaaaaaaaaa
aaaaaaahccaabaaaacaaaaaadkaabaaaabaaaaaabkbabaaaabaaaaaadiaaaaak
pcaabaaaadaaaaaaegaobaaaadaaaaaaaceaaaaaifglmmdohkkflgdohhpliodo
fnibhpdoefaaaaajpcaabaaaaeaaaaaaegaabaaaadaaaaaaeghobaaaacaaaaaa
aagabaaaadaaaaaaefaaaaajpcaabaaaadaaaaaaogakbaaaadaaaaaaeghobaaa
acaaaaaaaagabaaaadaaaaaadiaaaaahicaabaaaabaaaaaaakaabaaaadaaaaaa
akaabaaaaeaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
mnmmemdoabeaaaaamnmmmmlnaoaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaa
dkaabaaaaaaaaaaaaaaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaakbabaaa
abaaaaaadiaaaaahmcaabaaaacaaaaaakgaobaaaaaaaaaaaagaebaaaacaaaaaa
ebaaaaafmcaabaaaacaaaaaakgaobaaaacaaaaaaaoaaaaahgcaabaaaadaaaaaa
kgalbaaaacaaaaaakgalbaaaaaaaaaaaefaaaaajpcaabaaaaeaaaaaajgafbaaa
adaaaaaaeghobaaaadaaaaaaaagabaaaabaaaaaadiaaaaakpcaabaaaafaaaaaa
jgajbaaaadaaaaaaaceaaaaahbindmeajofokjdldlocadeaknoogmdlefaaaaaj
pcaabaaaagaaaaaaegaabaaaafaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaa
efaaaaajpcaabaaaafaaaaaaogakbaaaafaaaaaaeghobaaaacaaaaaaaagabaaa
adaaaaaadiaaaaahncaabaaaafaaaaaaagajbaaaafaaaaaaagajbaaaagaaaaaa
diaaaaakmcaabaaaacaaaaaaagaibaaaafaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaakaeaaaaakaeaebaaaaafmcaabaaaacaaaaaakgaobaaaacaaaaaaaaaaaaai
dcaabaaaacaaaaaaegaabaaaacaaaaaajgafbaiaebaaaaaaadaaaaaadiaaaaah
mcaabaaaaaaaaaaakgaobaaaaaaaaaaaagaebaaaacaaaaaadiaaaaakmcaabaaa
aaaaaaaakgaobaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaamnmmemdomnmmemdo
dcaaaaammcaabaaaaaaaaaaakgaobaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
mnmmemdomnmmemdokgaobaaaaaaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaa
afaaaaaaabeaaaaaaaaaiaebabeaaaaaaaaadaecdiaaaaahbcaabaaaadaaaaaa
dkaabaaaabaaaaaabkaabaaaadaaaaaadiaaaaakpcaabaaaacaaaaaaigaibaaa
adaaaaaaaceaaaaaaaaaiadleifapmdjgdapdddlenhlladjefaaaaajpcaabaaa
adaaaaaaegaabaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaaefaaaaaj
pcaabaaaacaaaaaaogakbaaaacaaaaaaeghobaaaacaaaaaaaagabaaaadaaaaaa
diaaaaahicaabaaaabaaaaaackaabaaaacaaaaaackaabaaaadaaaaaadiaaaaah
icaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaecebaaaaaficaabaaa
abaaaaaadkaabaaaabaaaaaadiaaaaahccaabaaaacaaaaaadkaabaaaabaaaaaa
abeaaaaaaaaaaadnefaaaaajpcaabaaaadaaaaaaogakbaaaaaaaaaaaeghobaaa
aeaaaaaaaagabaaaaeaaaaaaaaaaaaaibcaabaaaacaaaaaaakaabaiaebaaaaaa
adaaaaaaabeaaaaaaaaaiadpefaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaa
eghobaaaafaaaaaaaagabaaaafaaaaaabpaaaeadakaabaaaaaaaaaaadgaaaaai
pccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaab
bfaaaaabdbaaaaahbcaabaaaaaaaaaaaabeaaaaaibiaiadlakaabaaaabaaaaaa
djaaaaakmcaabaaaaaaaaaaafgajbaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaadmaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaa
aaaaaaaadmaaaaahbcaabaaaaaaaaaaadkaabaaaaaaaaaaaakaabaaaaaaaaaaa
bpaaaeadakaabaaaaaaaaaaadgaaaaaipccabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadoaaaaabbfaaaaabdbaaaaahbcaabaaaaaaaaaaa
akaabaaaaeaaaaaaabeaaaaamnmmmmdnbpaaaeadakaabaaaaaaaaaaadgaaaaai
pccabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadoaaaaab
bfaaaaabaaaaaaaibcaabaaaaaaaaaaackaabaiaebaaaaaaaeaaaaaaabeaaaaa
aaaaiadpapaaaaahbcaabaaaaaaaaaaaagaabaaaaaaaaaaapgapbaaaafaaaaaa
dcaaaaajbcaabaaaaaaaaaaabkaabaaaagaaaaaabkaabaaaafaaaaaaakaabaaa
aaaaaaaadbaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaajjjjbjdp
diaaaaakhcaabaaaabaaaaaaegacbaaaacaaaaaaaceaaaaajkjjbjdpjkjjbjdp
jkjjbjdpaaaaaaaadhaaaaajhcaabaaaacaaaaaaagaabaaaaaaaaaaaegacbaaa
abaaaaaaegacbaaaacaaaaaadicaaaahbcaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaijiiiidncpaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaajkjjbjdpbjaaaaafbcaabaaa
aaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaggggggdpaaaaaaajpcaabaaaabaaaaaaegaobaiaebaaaaaaacaaaaaa
egiocaaaaaaaaaaaabaaaaaadcaaaaajpccabaaaaaaaaaaaagaabaaaaaaaaaaa
egaobaaaabaaaaaaegaobaaaacaaaaaadoaaaaab"
}




}
 }
}
}